// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package taxfilingdb

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
	"kamarapms/internal/platform/civil"
)

const accountByCode = `-- name: AccountByCode :one
SELECT id, account_type, is_postable, is_active FROM gl_accounts WHERE tenant_id = $1 AND property_id = $2 AND code = $3
`

type AccountByCodeParams struct {
	TenantID   int64
	PropertyID int64
	Code       string
}

type AccountByCodeRow struct {
	ID          int64
	AccountType string
	IsPostable  bool
	IsActive    bool
}

func (q *Queries) AccountByCode(ctx context.Context, arg AccountByCodeParams) (AccountByCodeRow, error) {
	row := q.db.QueryRow(ctx, accountByCode, arg.TenantID, arg.PropertyID, arg.Code)
	var i AccountByCodeRow
	err := row.Scan(
		&i.ID,
		&i.AccountType,
		&i.IsPostable,
		&i.IsActive,
	)
	return i, err
}

const accountCreditBalance = `-- name: AccountCreditBalance :one
SELECT COALESCE(sum(l.credit - l.debit), 0)::numeric AS balance
FROM gl_journal_lines l
JOIN gl_journals j ON j.property_id = l.property_id AND j.id = l.journal_id
JOIN gl_accounts a ON a.property_id = l.property_id AND a.id = l.account_id
WHERE l.tenant_id = $1 AND l.property_id = $2 AND a.code = $3 AND j.journal_date <= $4::date
`

type AccountCreditBalanceParams struct {
	TenantID   int64
	PropertyID int64
	Code       string
	AsOf       civil.Date
}

// The account of the books as of a date: credit balance (what is owed).
func (q *Queries) AccountCreditBalance(ctx context.Context, arg AccountCreditBalanceParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, accountCreditBalance,
		arg.TenantID,
		arg.PropertyID,
		arg.Code,
		arg.AsOf,
	)
	var balance decimal.Decimal
	err := row.Scan(&balance)
	return balance, err
}

const accountingStart = `-- name: AccountingStart :one
SELECT start_date FROM accounting_settings WHERE tenant_id = $1 AND property_id = $2
`

type AccountingStartParams struct {
	TenantID   int64
	PropertyID int64
}

func (q *Queries) AccountingStart(ctx context.Context, arg AccountingStartParams) (civil.Date, error) {
	row := q.db.QueryRow(ctx, accountingStart, arg.TenantID, arg.PropertyID)
	var start_date civil.Date
	err := row.Scan(&start_date)
	return start_date, err
}

const collectedBetween = `-- name: CollectedBetween :one
SELECT COALESCE(sum(k.amount), 0)::numeric AS tax
FROM folio_item_components k
JOIN folio_items i ON i.property_id = k.property_id AND i.id = k.folio_item_id
WHERE k.tenant_id = $1 AND k.property_id = $2 AND k.component_type = 'TAX' AND k.tax_id = $3
  AND i.business_date BETWEEN $4::date AND $5::date
`

type CollectedBetweenParams struct {
	TenantID   int64
	PropertyID int64
	TaxID      *int64
	FromDate   civil.Date
	ToDate     civil.Date
}

func (q *Queries) CollectedBetween(ctx context.Context, arg CollectedBetweenParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, collectedBetween,
		arg.TenantID,
		arg.PropertyID,
		arg.TaxID,
		arg.FromDate,
		arg.ToDate,
	)
	var tax decimal.Decimal
	err := row.Scan(&tax)
	return tax, err
}

const collectedToDate = `-- name: CollectedToDate :many

SELECT k.tax_id, sum(k.amount)::numeric AS tax
FROM folio_item_components k
JOIN folio_items i ON i.property_id = k.property_id AND i.id = k.folio_item_id
WHERE k.tenant_id = $1 AND k.property_id = $2 AND k.component_type = 'TAX' AND i.business_date <= $3::date
GROUP BY k.tax_id
`

type CollectedToDateParams struct {
	TenantID   int64
	PropertyID int64
	AsOf       civil.Date
}

type CollectedToDateRow struct {
	TaxID *int64
	Tax   decimal.Decimal
}

// ---------------------------------------------------------------------------------------------------------------
// Liability
// Tax collected on folios up to a date, by tax.
func (q *Queries) CollectedToDate(ctx context.Context, arg CollectedToDateParams) ([]CollectedToDateRow, error) {
	rows, err := q.db.Query(ctx, collectedToDate, arg.TenantID, arg.PropertyID, arg.AsOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectedToDateRow{}
	for rows.Next() {
		var i CollectedToDateRow
		if err := rows.Scan(&i.TaxID, &i.Tax); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLivePayments = `-- name: CountLivePayments :one
SELECT count(*)::int FROM tax_payments WHERE tenant_id = $1 AND property_id = $2 AND return_id = $3 AND status = 'POSTED'
`

type CountLivePaymentsParams struct {
	TenantID   int64
	PropertyID int64
	ReturnID   int64
}

func (q *Queries) CountLivePayments(ctx context.Context, arg CountLivePaymentsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countLivePayments, arg.TenantID, arg.PropertyID, arg.ReturnID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPostedDays = `-- name: CountPostedDays :one
SELECT count(*)::int FROM business_days b
JOIN gl_day_posts d ON d.property_id = b.property_id AND d.business_date = b.business_date
WHERE b.tenant_id = $1 AND b.property_id = $2 AND b.status = 'CLOSED' AND b.business_date BETWEEN $3::date AND $4::date
`

type CountPostedDaysParams struct {
	TenantID   int64
	PropertyID int64
	FromDate   civil.Date
	ToDate     civil.Date
}

// Days of a range that are closed business days with their journal.
func (q *Queries) CountPostedDays(ctx context.Context, arg CountPostedDaysParams) (int32, error) {
	row := q.db.QueryRow(ctx, countPostedDays,
		arg.TenantID,
		arg.PropertyID,
		arg.FromDate,
		arg.ToDate,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const filedAndPaidToDate = `-- name: FiledAndPaidToDate :many
SELECT r.tax_id, COALESCE(sum(r.tax_amount), 0)::numeric AS filed, count(*)::int AS returns,
       COALESCE(sum((SELECT COALESCE(sum(x.amount), 0) FROM tax_payments x LEFT JOIN gl_journals xv ON xv.property_id = x.property_id AND xv.id = x.void_journal_id
                      WHERE x.property_id = r.property_id AND x.return_id = r.id AND x.payment_date <= $1::date AND (x.status = 'POSTED' OR xv.journal_date > $1::date))), 0)::numeric AS paid
FROM tax_returns r
WHERE r.tenant_id = $2 AND r.property_id = $3 AND r.filed_on <= $1::date AND (r.status = 'FILED' OR r.voided_at::date > $1::date)
GROUP BY r.tax_id
`

type FiledAndPaidToDateParams struct {
	AsOf       civil.Date
	TenantID   int64
	PropertyID int64
}

type FiledAndPaidToDateRow struct {
	TaxID   int64
	Filed   decimal.Decimal
	Returns int32
	Paid    decimal.Decimal
}

// Returns filed (not voided, or voided after the date) with a period ended by a date, and what was paid on them by it.
func (q *Queries) FiledAndPaidToDate(ctx context.Context, arg FiledAndPaidToDateParams) ([]FiledAndPaidToDateRow, error) {
	rows, err := q.db.Query(ctx, filedAndPaidToDate, arg.AsOf, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FiledAndPaidToDateRow{}
	for rows.Next() {
		var i FiledAndPaidToDateRow
		if err := rows.Scan(
			&i.TaxID,
			&i.Filed,
			&i.Returns,
			&i.Paid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findReturnByKey = `-- name: FindReturnByKey :one
SELECT id FROM tax_returns WHERE tenant_id = $1 AND property_id = $2 AND idempotency_key = $3
`

type FindReturnByKeyParams struct {
	TenantID       int64
	PropertyID     int64
	IdempotencyKey *string
}

func (q *Queries) FindReturnByKey(ctx context.Context, arg FindReturnByKeyParams) (int64, error) {
	row := q.db.QueryRow(ctx, findReturnByKey, arg.TenantID, arg.PropertyID, arg.IdempotencyKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findTaxPaymentByKey = `-- name: FindTaxPaymentByKey :one
SELECT id FROM tax_payments WHERE tenant_id = $1 AND property_id = $2 AND idempotency_key = $3
`

type FindTaxPaymentByKeyParams struct {
	TenantID       int64
	PropertyID     int64
	IdempotencyKey *string
}

func (q *Queries) FindTaxPaymentByKey(ctx context.Context, arg FindTaxPaymentByKeyParams) (int64, error) {
	row := q.db.QueryRow(ctx, findTaxPaymentByKey, arg.TenantID, arg.PropertyID, arg.IdempotencyKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const firstTaxSettingsID = `-- name: FirstTaxSettingsID :one
SELECT id FROM property_tax_settings WHERE tenant_id = $1 AND property_id = $2 ORDER BY effective_from, id LIMIT 1
`

type FirstTaxSettingsIDParams struct {
	TenantID   int64
	PropertyID int64
}

// The first row of a property always exists: the changes of the settings lock it.
func (q *Queries) FirstTaxSettingsID(ctx context.Context, arg FirstTaxSettingsIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, firstTaxSettingsID, arg.TenantID, arg.PropertyID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const gLCollected = `-- name: GLCollected :one
SELECT COALESCE(sum(l.credit - l.debit), 0)::numeric AS collected
FROM gl_journal_lines l
JOIN gl_journals j ON j.property_id = l.property_id AND j.id = l.journal_id
WHERE l.tenant_id = $1 AND l.property_id = $2 AND l.source_type = 'TAX' AND l.source_ref = $3
  AND j.journal_type = 'DAY_CLOSE' AND j.journal_date BETWEEN $4::date AND $5::date
`

type GLCollectedParams struct {
	TenantID   int64
	PropertyID int64
	TaxCode    *string
	FromDate   civil.Date
	ToDate     civil.Date
}

// What the day close journals credited for a tax in a range (the lines carry the tax code as their source).
func (q *Queries) GLCollected(ctx context.Context, arg GLCollectedParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, gLCollected,
		arg.TenantID,
		arg.PropertyID,
		arg.TaxCode,
		arg.FromDate,
		arg.ToDate,
	)
	var collected decimal.Decimal
	err := row.Scan(&collected)
	return collected, err
}

const insertProfile = `-- name: InsertProfile :one
INSERT INTO tax_filing_profiles (tenant_id, property_id, tax_id, authority, registration_number, due_day, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8)
RETURNING id
`

type InsertProfileParams struct {
	TenantID           int64
	PropertyID         int64
	TaxID              int64
	Authority          string
	RegistrationNumber *string
	DueDay             int16
	IsActive           bool
	ActorID            *int64
}

func (q *Queries) InsertProfile(ctx context.Context, arg InsertProfileParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertProfile,
		arg.TenantID,
		arg.PropertyID,
		arg.TaxID,
		arg.Authority,
		arg.RegistrationNumber,
		arg.DueDay,
		arg.IsActive,
		arg.ActorID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertReturn = `-- name: InsertReturn :one

INSERT INTO tax_returns (tenant_id, property_id, return_number, tax_id, period_start, period_end, due_date, base_amount, tax_amount, filed_on, filing_reference, notes,
                         filed_at, filed_by, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
        $12, $13, $14, $15)
RETURNING id
`

type InsertReturnParams struct {
	TenantID        int64
	PropertyID      int64
	ReturnNumber    string
	TaxID           int64
	PeriodStart     civil.Date
	PeriodEnd       civil.Date
	DueDate         civil.Date
	BaseAmount      decimal.Decimal
	TaxAmount       decimal.Decimal
	FiledOn         civil.Date
	FilingReference *string
	Notes           *string
	Now             time.Time
	ActorID         *int64
	IdempotencyKey  *string
}

// ---------------------------------------------------------------------------------------------------------------
// Returns
func (q *Queries) InsertReturn(ctx context.Context, arg InsertReturnParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertReturn,
		arg.TenantID,
		arg.PropertyID,
		arg.ReturnNumber,
		arg.TaxID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.DueDate,
		arg.BaseAmount,
		arg.TaxAmount,
		arg.FiledOn,
		arg.FilingReference,
		arg.Notes,
		arg.Now,
		arg.ActorID,
		arg.IdempotencyKey,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertReturnLine = `-- name: InsertReturnLine :exec
INSERT INTO tax_return_lines (tenant_id, property_id, return_id, line_no, charge_code, charge_name, rate, items, base_amount, tax_amount)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertReturnLineParams struct {
	TenantID   int64
	PropertyID int64
	ReturnID   int64
	LineNo     int32
	ChargeCode string
	ChargeName *string
	Rate       decimal.Decimal
	Items      int32
	BaseAmount decimal.Decimal
	TaxAmount  decimal.Decimal
}

func (q *Queries) InsertReturnLine(ctx context.Context, arg InsertReturnLineParams) error {
	_, err := q.db.Exec(ctx, insertReturnLine,
		arg.TenantID,
		arg.PropertyID,
		arg.ReturnID,
		arg.LineNo,
		arg.ChargeCode,
		arg.ChargeName,
		arg.Rate,
		arg.Items,
		arg.BaseAmount,
		arg.TaxAmount,
	)
	return err
}

const insertTaxPayment = `-- name: InsertTaxPayment :one

INSERT INTO tax_payments (tenant_id, property_id, payment_number, return_id, payment_date, amount, penalty, payment_method, reference_number, remarks, journal_id, idempotency_key, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
        $12, $13)
RETURNING id
`

type InsertTaxPaymentParams struct {
	TenantID        int64
	PropertyID      int64
	PaymentNumber   string
	ReturnID        int64
	PaymentDate     civil.Date
	Amount          decimal.Decimal
	Penalty         decimal.Decimal
	PaymentMethod   string
	ReferenceNumber *string
	Remarks         *string
	JournalID       int64
	IdempotencyKey  *string
	ActorID         *int64
}

// ---------------------------------------------------------------------------------------------------------------
// Payments
func (q *Queries) InsertTaxPayment(ctx context.Context, arg InsertTaxPaymentParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertTaxPayment,
		arg.TenantID,
		arg.PropertyID,
		arg.PaymentNumber,
		arg.ReturnID,
		arg.PaymentDate,
		arg.Amount,
		arg.Penalty,
		arg.PaymentMethod,
		arg.ReferenceNumber,
		arg.Remarks,
		arg.JournalID,
		arg.IdempotencyKey,
		arg.ActorID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTaxSettings = `-- name: InsertTaxSettings :one
INSERT INTO property_tax_settings (tenant_id, property_id, effective_from, is_pkp, npwp, pkp_number, pkp_confirmed_on, input_vat_treatment, signer_name, signer_title, approved_by, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12)
RETURNING id
`

type InsertTaxSettingsParams struct {
	TenantID          int64
	PropertyID        int64
	EffectiveFrom     civil.Date
	IsPkp             bool
	Npwp              *string
	PkpNumber         *string
	PkpConfirmedOn    *civil.Date
	InputVatTreatment string
	SignerName        *string
	SignerTitle       *string
	ApprovedBy        *int64
	ActorID           *int64
}

func (q *Queries) InsertTaxSettings(ctx context.Context, arg InsertTaxSettingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertTaxSettings,
		arg.TenantID,
		arg.PropertyID,
		arg.EffectiveFrom,
		arg.IsPkp,
		arg.Npwp,
		arg.PkpNumber,
		arg.PkpConfirmedOn,
		arg.InputVatTreatment,
		arg.SignerName,
		arg.SignerTitle,
		arg.ApprovedBy,
		arg.ActorID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listProfiles = `-- name: ListProfiles :many


SELECT p.id, p.tax_id, t.code AS tax_code, t.name AS tax_name, t.rate AS tax_rate, t.gl_account_code, p.authority, p.registration_number, p.due_day, p.is_active, p.created_at
FROM tax_filing_profiles p
JOIN taxes t ON t.property_id = p.property_id AND t.id = p.tax_id
WHERE p.tenant_id = $1 AND p.property_id = $2
  AND ($3::bigint IS NULL OR p.id = $3::bigint)
  AND ($4::bigint IS NULL OR p.tax_id = $4::bigint)
ORDER BY t.code, p.id
`

type ListProfilesParams struct {
	TenantID   int64
	PropertyID int64
	ID         *int64
	TaxID      *int64
}

type ListProfilesRow struct {
	ID                 int64
	TaxID              int64
	TaxCode            string
	TaxName            string
	TaxRate            decimal.Decimal
	GlAccountCode      *string
	Authority          string
	RegistrationNumber *string
	DueDay             int16
	IsActive           bool
	CreatedAt          time.Time
}

// Tax filing (sqlc): filing profiles, monthly returns with their worksheet lines, and tax payments. Every query is scoped by
// tenant_id and property_id.
// ---------------------------------------------------------------------------------------------------------------
// Profiles
func (q *Queries) ListProfiles(ctx context.Context, arg ListProfilesParams) ([]ListProfilesRow, error) {
	rows, err := q.db.Query(ctx, listProfiles,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
		arg.TaxID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfilesRow{}
	for rows.Next() {
		var i ListProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.TaxID,
			&i.TaxCode,
			&i.TaxName,
			&i.TaxRate,
			&i.GlAccountCode,
			&i.Authority,
			&i.RegistrationNumber,
			&i.DueDay,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturnLines = `-- name: ListReturnLines :many
SELECT line_no, charge_code, charge_name, rate, items, base_amount, tax_amount FROM tax_return_lines
WHERE tenant_id = $1 AND property_id = $2 AND return_id = $3 ORDER BY line_no
`

type ListReturnLinesParams struct {
	TenantID   int64
	PropertyID int64
	ReturnID   int64
}

type ListReturnLinesRow struct {
	LineNo     int32
	ChargeCode string
	ChargeName *string
	Rate       decimal.Decimal
	Items      int32
	BaseAmount decimal.Decimal
	TaxAmount  decimal.Decimal
}

func (q *Queries) ListReturnLines(ctx context.Context, arg ListReturnLinesParams) ([]ListReturnLinesRow, error) {
	rows, err := q.db.Query(ctx, listReturnLines, arg.TenantID, arg.PropertyID, arg.ReturnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReturnLinesRow{}
	for rows.Next() {
		var i ListReturnLinesRow
		if err := rows.Scan(
			&i.LineNo,
			&i.ChargeCode,
			&i.ChargeName,
			&i.Rate,
			&i.Items,
			&i.BaseAmount,
			&i.TaxAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturns = `-- name: ListReturns :many
SELECT r.id, r.return_number, r.tax_id, t.code AS tax_code, t.name AS tax_name, r.period_start, r.period_end, r.due_date, r.base_amount, r.tax_amount, r.status, r.filed_on,
       r.filing_reference, r.notes, r.filed_at, r.voided_at, r.void_reason,
       COALESCE((SELECT sum(x.amount) FROM tax_payments x WHERE x.property_id = r.property_id AND x.return_id = r.id AND x.status = 'POSTED'), 0)::numeric AS paid
FROM tax_returns r
JOIN taxes t ON t.property_id = r.property_id AND t.id = r.tax_id
WHERE r.tenant_id = $1 AND r.property_id = $2
  AND ($3::bigint IS NULL OR r.id = $3::bigint)
  AND ($4::bigint IS NULL OR r.tax_id = $4::bigint)
  AND ($5::text IS NULL OR r.status = $5::text)
ORDER BY r.period_start DESC, r.id DESC
LIMIT $6
`

type ListReturnsParams struct {
	TenantID   int64
	PropertyID int64
	ID         *int64
	TaxID      *int64
	Status     *string
	RowLimit   int32
}

type ListReturnsRow struct {
	ID              int64
	ReturnNumber    string
	TaxID           int64
	TaxCode         string
	TaxName         string
	PeriodStart     civil.Date
	PeriodEnd       civil.Date
	DueDate         civil.Date
	BaseAmount      decimal.Decimal
	TaxAmount       decimal.Decimal
	Status          string
	FiledOn         civil.Date
	FilingReference *string
	Notes           *string
	FiledAt         time.Time
	VoidedAt        *time.Time
	VoidReason      *string
	Paid            decimal.Decimal
}

func (q *Queries) ListReturns(ctx context.Context, arg ListReturnsParams) ([]ListReturnsRow, error) {
	rows, err := q.db.Query(ctx, listReturns,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
		arg.TaxID,
		arg.Status,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReturnsRow{}
	for rows.Next() {
		var i ListReturnsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReturnNumber,
			&i.TaxID,
			&i.TaxCode,
			&i.TaxName,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.DueDate,
			&i.BaseAmount,
			&i.TaxAmount,
			&i.Status,
			&i.FiledOn,
			&i.FilingReference,
			&i.Notes,
			&i.FiledAt,
			&i.VoidedAt,
			&i.VoidReason,
			&i.Paid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxPayments = `-- name: ListTaxPayments :many
SELECT x.id, x.payment_number, x.return_id, r.return_number, t.code AS tax_code, t.name AS tax_name, r.period_start, x.payment_date, x.amount, x.penalty, x.payment_method,
       x.reference_number, x.remarks, x.status, x.journal_id, jn.journal_number, x.void_journal_id, x.voided_at, x.void_reason, x.created_at
FROM tax_payments x
JOIN tax_returns r ON r.property_id = x.property_id AND r.id = x.return_id
JOIN taxes t ON t.property_id = r.property_id AND t.id = r.tax_id
JOIN gl_journals jn ON jn.property_id = x.property_id AND jn.id = x.journal_id
WHERE x.tenant_id = $1 AND x.property_id = $2
  AND ($3::bigint IS NULL OR x.id = $3::bigint)
  AND ($4::bigint IS NULL OR x.return_id = $4::bigint)
  AND ($5::text IS NULL OR x.status = $5::text)
ORDER BY x.payment_date DESC, x.id DESC
LIMIT $6
`

type ListTaxPaymentsParams struct {
	TenantID   int64
	PropertyID int64
	ID         *int64
	ReturnID   *int64
	Status     *string
	RowLimit   int32
}

type ListTaxPaymentsRow struct {
	ID              int64
	PaymentNumber   string
	ReturnID        int64
	ReturnNumber    string
	TaxCode         string
	TaxName         string
	PeriodStart     civil.Date
	PaymentDate     civil.Date
	Amount          decimal.Decimal
	Penalty         decimal.Decimal
	PaymentMethod   string
	ReferenceNumber *string
	Remarks         *string
	Status          string
	JournalID       int64
	JournalNumber   string
	VoidJournalID   *int64
	VoidedAt        *time.Time
	VoidReason      *string
	CreatedAt       time.Time
}

func (q *Queries) ListTaxPayments(ctx context.Context, arg ListTaxPaymentsParams) ([]ListTaxPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listTaxPayments,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
		arg.ReturnID,
		arg.Status,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaxPaymentsRow{}
	for rows.Next() {
		var i ListTaxPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentNumber,
			&i.ReturnID,
			&i.ReturnNumber,
			&i.TaxCode,
			&i.TaxName,
			&i.PeriodStart,
			&i.PaymentDate,
			&i.Amount,
			&i.Penalty,
			&i.PaymentMethod,
			&i.ReferenceNumber,
			&i.Remarks,
			&i.Status,
			&i.JournalID,
			&i.JournalNumber,
			&i.VoidJournalID,
			&i.VoidedAt,
			&i.VoidReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxSettings = `-- name: ListTaxSettings :many

SELECT id, effective_from, is_pkp, npwp, pkp_number, pkp_confirmed_on, input_vat_treatment, signer_name, signer_title, approved_by, created_at
FROM property_tax_settings
WHERE tenant_id = $1 AND property_id = $2
ORDER BY effective_from DESC, id DESC
`

type ListTaxSettingsParams struct {
	TenantID   int64
	PropertyID int64
}

type ListTaxSettingsRow struct {
	ID                int64
	EffectiveFrom     civil.Date
	IsPkp             bool
	Npwp              *string
	PkpNumber         *string
	PkpConfirmedOn    *civil.Date
	InputVatTreatment string
	SignerName        *string
	SignerTitle       *string
	ApprovedBy        *int64
	CreatedAt         time.Time
}

// ---------------------------------------------------------------------------------------------------------------
// PKP settings (append-only history of the tax status of the property)
func (q *Queries) ListTaxSettings(ctx context.Context, arg ListTaxSettingsParams) ([]ListTaxSettingsRow, error) {
	rows, err := q.db.Query(ctx, listTaxSettings, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaxSettingsRow{}
	for rows.Next() {
		var i ListTaxSettingsRow
		if err := rows.Scan(
			&i.ID,
			&i.EffectiveFrom,
			&i.IsPkp,
			&i.Npwp,
			&i.PkpNumber,
			&i.PkpConfirmedOn,
			&i.InputVatTreatment,
			&i.SignerName,
			&i.SignerTitle,
			&i.ApprovedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveReturnOfPeriod = `-- name: LiveReturnOfPeriod :one
SELECT id FROM tax_returns WHERE tenant_id = $1 AND property_id = $2 AND tax_id = $3 AND period_start = $4 AND status = 'FILED'
`

type LiveReturnOfPeriodParams struct {
	TenantID    int64
	PropertyID  int64
	TaxID       int64
	PeriodStart civil.Date
}

func (q *Queries) LiveReturnOfPeriod(ctx context.Context, arg LiveReturnOfPeriodParams) (int64, error) {
	row := q.db.QueryRow(ctx, liveReturnOfPeriod,
		arg.TenantID,
		arg.PropertyID,
		arg.TaxID,
		arg.PeriodStart,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const mapAccountCode = `-- name: MapAccountCode :one
SELECT a.code FROM gl_account_map m JOIN gl_accounts a ON a.property_id = m.property_id AND a.id = m.account_id
WHERE m.tenant_id = $1 AND m.property_id = $2 AND m.map_key = $3
`

type MapAccountCodeParams struct {
	TenantID   int64
	PropertyID int64
	MapKey     string
}

func (q *Queries) MapAccountCode(ctx context.Context, arg MapAccountCodeParams) (string, error) {
	row := q.db.QueryRow(ctx, mapAccountCode, arg.TenantID, arg.PropertyID, arg.MapKey)
	var code string
	err := row.Scan(&code)
	return code, err
}

const paidByReturnToDate = `-- name: PaidByReturnToDate :many
SELECT x.return_id, COALESCE(sum(x.amount), 0)::numeric AS paid
FROM tax_payments x LEFT JOIN gl_journals xv ON xv.property_id = x.property_id AND xv.id = x.void_journal_id
WHERE x.tenant_id = $1 AND x.property_id = $2 AND x.payment_date <= $3::date AND (x.status = 'POSTED' OR xv.journal_date > $3::date)
GROUP BY x.return_id
`

type PaidByReturnToDateParams struct {
	TenantID   int64
	PropertyID int64
	AsOf       civil.Date
}

type PaidByReturnToDateRow struct {
	ReturnID int64
	Paid     decimal.Decimal
}

// What was paid on each return up to a date (a payment voided after the date still counts).
func (q *Queries) PaidByReturnToDate(ctx context.Context, arg PaidByReturnToDateParams) ([]PaidByReturnToDateRow, error) {
	rows, err := q.db.Query(ctx, paidByReturnToDate, arg.TenantID, arg.PropertyID, arg.AsOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaidByReturnToDateRow{}
	for rows.Next() {
		var i PaidByReturnToDateRow
		if err := rows.Scan(&i.ReturnID, &i.Paid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profileOfReturn = `-- name: ProfileOfReturn :one
SELECT p.id FROM tax_filing_profiles p JOIN tax_returns r ON r.property_id = p.property_id AND r.tax_id = p.tax_id
WHERE r.tenant_id = $1 AND r.property_id = $2 AND r.id = $3
`

type ProfileOfReturnParams struct {
	TenantID   int64
	PropertyID int64
	ReturnID   int64
}

func (q *Queries) ProfileOfReturn(ctx context.Context, arg ProfileOfReturnParams) (int64, error) {
	row := q.db.QueryRow(ctx, profileOfReturn, arg.TenantID, arg.PropertyID, arg.ReturnID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const returnOfPayment = `-- name: ReturnOfPayment :one
SELECT return_id FROM tax_payments WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type ReturnOfPaymentParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) ReturnOfPayment(ctx context.Context, arg ReturnOfPaymentParams) (int64, error) {
	row := q.db.QueryRow(ctx, returnOfPayment, arg.TenantID, arg.PropertyID, arg.ID)
	var return_id int64
	err := row.Scan(&return_id)
	return return_id, err
}

const taxOfProperty = `-- name: TaxOfProperty :one
SELECT id, code, is_active FROM taxes WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type TaxOfPropertyParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

type TaxOfPropertyRow struct {
	ID       int64
	Code     string
	IsActive bool
}

func (q *Queries) TaxOfProperty(ctx context.Context, arg TaxOfPropertyParams) (TaxOfPropertyRow, error) {
	row := q.db.QueryRow(ctx, taxOfProperty, arg.TenantID, arg.PropertyID, arg.ID)
	var i TaxOfPropertyRow
	err := row.Scan(&i.ID, &i.Code, &i.IsActive)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE tax_filing_profiles SET authority = $1, registration_number = $2, due_day = $3, is_active = $4, updated_by = $5
WHERE tenant_id = $6 AND property_id = $7 AND id = $8
`

type UpdateProfileParams struct {
	Authority          string
	RegistrationNumber *string
	DueDay             int16
	IsActive           bool
	ActorID            *int64
	TenantID           int64
	PropertyID         int64
	ID                 int64
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile,
		arg.Authority,
		arg.RegistrationNumber,
		arg.DueDay,
		arg.IsActive,
		arg.ActorID,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
	)
	return err
}

const voidReturn = `-- name: VoidReturn :exec
UPDATE tax_returns SET status = 'VOIDED', voided_at = $1, voided_by = $2, void_reason = $3, approved_by = $4
WHERE tenant_id = $5 AND property_id = $6 AND id = $7
`

type VoidReturnParams struct {
	Now        *time.Time
	ActorID    *int64
	Reason     *string
	ApprovedBy *int64
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) VoidReturn(ctx context.Context, arg VoidReturnParams) error {
	_, err := q.db.Exec(ctx, voidReturn,
		arg.Now,
		arg.ActorID,
		arg.Reason,
		arg.ApprovedBy,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
	)
	return err
}

const voidTaxPayment = `-- name: VoidTaxPayment :exec
UPDATE tax_payments SET status = 'VOIDED', voided_at = $1, voided_by = $2, void_reason = $3, void_journal_id = $4, approved_by = $5
WHERE tenant_id = $6 AND property_id = $7 AND id = $8
`

type VoidTaxPaymentParams struct {
	Now           *time.Time
	ActorID       *int64
	Reason        *string
	VoidJournalID *int64
	ApprovedBy    *int64
	TenantID      int64
	PropertyID    int64
	ID            int64
}

func (q *Queries) VoidTaxPayment(ctx context.Context, arg VoidTaxPaymentParams) error {
	_, err := q.db.Exec(ctx, voidTaxPayment,
		arg.Now,
		arg.ActorID,
		arg.Reason,
		arg.VoidJournalID,
		arg.ApprovedBy,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
	)
	return err
}

const worksheetLines = `-- name: WorksheetLines :many

SELECT COALESCE(cc.code, occ.code, '')::text AS charge_code, COALESCE(cc.name, occ.name, '')::text AS charge_name, k.rate,
       count(DISTINCT i.id)::int AS items, sum(k.base_amount)::numeric AS base, sum(k.amount)::numeric AS tax
FROM folio_item_components k
JOIN folio_items i ON i.property_id = k.property_id AND i.id = k.folio_item_id
LEFT JOIN charge_codes cc ON cc.property_id = i.property_id AND cc.id = i.charge_code_id
LEFT JOIN folio_items o ON o.property_id = i.property_id AND o.id = i.reverses_item_id
LEFT JOIN charge_codes occ ON occ.property_id = o.property_id AND occ.id = o.charge_code_id
WHERE k.tenant_id = $1 AND k.property_id = $2 AND k.component_type = 'TAX' AND k.tax_id = $3
  AND i.business_date BETWEEN $4::date AND $5::date
GROUP BY COALESCE(cc.code, occ.code, ''), COALESCE(cc.name, occ.name, ''), k.rate
ORDER BY 1, k.rate
`

type WorksheetLinesParams struct {
	TenantID   int64
	PropertyID int64
	TaxID      *int64
	FromDate   civil.Date
	ToDate     civil.Date
}

type WorksheetLinesRow struct {
	ChargeCode string
	ChargeName string
	Rate       decimal.Decimal
	Items      int32
	Base       decimal.Decimal
	Tax        decimal.Decimal
}

// ---------------------------------------------------------------------------------------------------------------
// The worksheet of a month
// Tax collected in a range by charge code and rate, from the snapshots of the folio items (a reversal carries the code of
// the item it reverses and negative amounts).
func (q *Queries) WorksheetLines(ctx context.Context, arg WorksheetLinesParams) ([]WorksheetLinesRow, error) {
	rows, err := q.db.Query(ctx, worksheetLines,
		arg.TenantID,
		arg.PropertyID,
		arg.TaxID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorksheetLinesRow{}
	for rows.Next() {
		var i WorksheetLinesRow
		if err := rows.Scan(
			&i.ChargeCode,
			&i.ChargeName,
			&i.Rate,
			&i.Items,
			&i.Base,
			&i.Tax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
