/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe (never checks dependencies) */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (checks the database) */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in (sets the httpOnly refresh cookie) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange the refresh cookie for a new access token (rotates the cookie) */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the session identified by the refresh cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller, their tenant, and their permissions per property */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the caller's password (ends their other sessions) */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The permission catalogue */
        get: operations["listPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users of the tenant (tenant administrators) */
        get: operations["listUsers"];
        put?: never;
        /** Create a user (tenant administrators) */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        /** A user with their property grants */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename, activate/deactivate, or change the administrator flag */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/v1/users/{userId}/properties": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        get?: never;
        /** Replace the user's property grants (one role per property) */
        put: operations["replaceUserGrants"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a user's password (ends all their sessions) */
        post: operations["resetUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roles of the tenant */
        get: operations["listRoles"];
        put?: never;
        /** Create a role */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: number;
            };
            cookie?: never;
        };
        /** A role */
        get: operations["getRole"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename a role or replace its permissions (effective on the next request) */
        patch: operations["updateRole"];
        trace?: never;
    };
    "/api/v1/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Properties the caller can access */
        get: operations["listProperties"];
        put?: never;
        /** Create a property (opens its first business day and document sequences) */
        post: operations["createProperty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{propertyId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: components["parameters"]["PropertyId"];
            };
            cookie?: never;
        };
        /** Property details, settings and current business date */
        get: operations["getProperty"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update property settings (currency is locked once financial transactions exist) */
        patch: operations["updateProperty"];
        trace?: never;
    };
    "/api/v1/properties/{propertyId}/business-date": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: components["parameters"]["PropertyId"];
            };
            cookie?: never;
        };
        /** The property business date versus server and local time */
        get: operations["getBusinessDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{propertyId}/business-days": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: components["parameters"]["PropertyId"];
            };
            cookie?: never;
        };
        /** Business-day history, newest first */
        get: operations["listBusinessDays"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            tenant_code: string;
            email: string;
            password: string;
        };
        Session: {
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** @description Seconds */
            expires_in: number;
            /** Format: date-time */
            expires_at: string;
            user: components["schemas"]["User"];
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        Grant: {
            /** Format: int64 */
            property_id: number;
            property_code: string;
            property_name: string;
            /** Format: int64 */
            role_id: number;
            role_name: string;
        };
        GrantInput: {
            /** Format: int64 */
            property_id: number;
            /** Format: int64 */
            role_id: number;
        };
        User: {
            /** Format: int64 */
            id: number;
            email: string;
            full_name: string;
            is_tenant_admin: boolean;
            is_active: boolean;
            /** Format: date-time */
            last_login_at?: string;
            /** Format: date-time */
            created_at: string;
            grants: components["schemas"]["Grant"][];
        };
        UserPage: {
            data: components["schemas"]["User"][];
            next_cursor?: string;
        };
        CreateUserRequest: {
            email: string;
            full_name: string;
            password: string;
            /** @default false */
            is_tenant_admin: boolean;
            grants?: components["schemas"]["GrantInput"][];
        };
        UpdateUserRequest: {
            full_name?: string;
            is_active?: boolean;
            is_tenant_admin?: boolean;
        };
        PermissionInfo: {
            code: string;
            group: string;
            description: string;
            milestone: string;
        };
        Role: {
            /** Format: int64 */
            id: number;
            name: string;
            description?: string;
            is_system: boolean;
            permissions: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RoleRequest: {
            name?: string;
            description?: string;
            permissions?: string[];
        };
        Me: {
            user: components["schemas"]["User"];
            tenant: {
                /** Format: int64 */
                id: number;
                code: string;
                name: string;
            };
            properties: {
                /** Format: int64 */
                id: number;
                code: string;
                name: string;
                role: string;
                permissions: string[];
            }[];
        };
        /**
         * Format: date
         * @description Calendar/business date (YYYY-MM-DD), never shifted by time zones.
         * @example 2026-09-30
         */
        Date: string;
        /** @example 14:00 */
        TimeOfDay: string;
        PropertySettings: {
            name: string;
            address?: string;
            city?: string;
            /** @description ISO 3166-1 alpha-2 */
            country_code?: string;
            /**
             * @description IANA time zone
             * @example Asia/Jakarta
             */
            timezone: string;
            /**
             * @description ISO 4217
             * @example IDR
             */
            currency_code: string;
            currency_decimals: number;
            check_in_time: components["schemas"]["TimeOfDay"];
            check_out_time: components["schemas"]["TimeOfDay"];
            require_room_inspection_for_checkin: boolean;
            night_audit_marks_occupied_dirty: boolean;
            night_audit_earliest_time: components["schemas"]["TimeOfDay"];
        };
        Property: components["schemas"]["PropertySettings"] & {
            /** Format: int64 */
            id: number;
            code: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PropertyWithDay: components["schemas"]["Property"] & {
            business_date: components["schemas"]["Date"];
        };
        PropertyPage: {
            data: components["schemas"]["Property"][];
            next_cursor?: string;
        };
        CreatePropertyRequest: {
            code: string;
            name: string;
            address?: string;
            city?: string;
            country_code?: string;
            timezone: string;
            currency_code: string;
            currency_decimals: number;
            check_in_time: components["schemas"]["TimeOfDay"];
            check_out_time: components["schemas"]["TimeOfDay"];
            /** @default false */
            require_room_inspection_for_checkin: boolean;
            /** @default true */
            night_audit_marks_occupied_dirty: boolean;
            night_audit_earliest_time?: components["schemas"]["TimeOfDay"];
            /** @description The property's current local date or the day before. */
            opening_business_date: components["schemas"]["Date"];
        };
        PatchPropertyRequest: {
            name?: string;
            address?: string;
            city?: string;
            country_code?: string;
            timezone?: string;
            currency_code?: string;
            currency_decimals?: number;
            check_in_time?: components["schemas"]["TimeOfDay"];
            check_out_time?: components["schemas"]["TimeOfDay"];
            require_room_inspection_for_checkin?: boolean;
            night_audit_marks_occupied_dirty?: boolean;
            night_audit_earliest_time?: components["schemas"]["TimeOfDay"];
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
        };
        DayClock: {
            business_date: components["schemas"]["Date"];
            /**
             * Format: date-time
             * @description Server time (UTC)
             */
            server_time: string;
            /** @description Server time in the property time zone (RFC 3339 with offset) */
            property_local_time: string;
            timezone: string;
            night_audit_allowed: boolean;
            /** Format: date-time */
            night_audit_allowed_from: string;
            /** @description The local date is more than one day past the business date. */
            night_audit_overdue: boolean;
        };
        BusinessDay: {
            business_date: components["schemas"]["Date"];
            /** @enum {string} */
            status: "OPEN" | "CLOSED";
            /** Format: date-time */
            opened_at: string;
            /** Format: int64 */
            opened_by?: number;
            /** Format: date-time */
            closed_at?: string;
            /** Format: int64 */
            closed_by?: number;
            summary?: {
                [key: string]: unknown;
            };
        };
        BusinessDayPage: {
            data: components["schemas"]["BusinessDay"][];
            next_cursor?: string;
        };
        HealthStatus: {
            /**
             * @example ok
             * @example ready
             */
            status: string;
        };
        FieldError: {
            field: string;
            code: string;
            message?: string;
        };
        Problem: {
            /** @example urn:kamarapms:problem:ROOM_NOT_AVAILABLE */
            type: string;
            title: string;
            status: number;
            /**
             * @description Stable machine-readable error code.
             * @example ROOM_NOT_AVAILABLE
             * @example VERSION_CONFLICT
             * @example RESOURCE_BUSY
             */
            code: string;
            detail?: string;
            errors?: components["schemas"]["FieldError"][];
            context?: {
                [key: string]: unknown;
            };
            /** @description The same request may succeed if retried (temporary contention). */
            retryable?: boolean;
            request_id?: string;
        };
    };
    responses: {
        /** @description An error, described as RFC 9457 problem details. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        PropertyId: number;
        Limit: number;
        /** @description Opaque cursor from a previous page's next_cursor. */
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API can serve traffic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            503: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. The refresh token is set as the httpOnly cookie pms_refresh (Path=/api/v1/auth). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A new session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out; the cookie is cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Changed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Problem"];
        };
    };
    listPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All permissions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PermissionInfo"][];
                    };
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor from a previous page's next_cursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description The user. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description The user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    replaceUserGrants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    grants: components["schemas"]["GrantInput"][];
                };
            };
        };
        responses: {
            /** @description The user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    resetUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description Password set. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Problem"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All roles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Role"][];
                    };
                };
            };
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        responses: {
            /** @description The role. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        responses: {
            /** @description The role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listProperties: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor from a previous page's next_cursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of properties. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyPage"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    createProperty: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePropertyRequest"];
            };
        };
        responses: {
            /** @description The created property with its business date. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyWithDay"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: components["parameters"]["PropertyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The property. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyWithDay"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    updateProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: components["parameters"]["PropertyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchPropertyRequest"];
            };
        };
        responses: {
            /** @description The updated property. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyWithDay"];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getBusinessDate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: components["parameters"]["PropertyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The business-date clock. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayClock"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listBusinessDays: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor from a previous page's next_cursor. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                propertyId: components["parameters"]["PropertyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of business days. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessDayPage"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
}
