import type { components } from './schema'

type Schemas = components['schemas']

export type Property = Schemas['Property']
export type PropertyWithDay = Schemas['PropertyWithDay']
export type PropertySettings = Schemas['PropertySettings']
export type CreatePropertyRequest = Schemas['CreatePropertyRequest']
export type PatchPropertyRequest = Schemas['PatchPropertyRequest']
export type DayClock = Schemas['DayClock']
export type BusinessDay = Schemas['BusinessDay']

export type RoomType = Schemas['RoomType']
export type CreateRoomTypeRequest = Schemas['CreateRoomTypeRequest']
export type PatchRoomTypeRequest = Schemas['PatchRoomTypeRequest']
export type BedType = Schemas['BedType']
export type Room = Schemas['Room']
export type CreateRoomRequest = Schemas['CreateRoomRequest']
export type PatchRoomRequest = Schemas['PatchRoomRequest']
export type RoomBlock = Schemas['RoomBlock']
export type BlockType = Schemas['BlockType']
export type HousekeepingStatus = Schemas['HousekeepingStatus']
export type HousekeepingBoardRoom = Schemas['HousekeepingBoardRoom']
export type Occupancy = Schemas['Occupancy']

export type Guest = Schemas['Guest']
export type GuestView = Schemas['GuestView']
export type CreateGuestRequest = Schemas['CreateGuestRequest']
export type PatchGuestRequest = Schemas['PatchGuestRequest']
export type CreatedGuest = Schemas['CreatedGuest']
export type PossibleDuplicate = Schemas['PossibleDuplicate']
export type GuestHistoryItem = Schemas['GuestHistoryItem']

export type Tax = Schemas['Tax']
export type CreateTaxRequest = Schemas['CreateTaxRequest']
export type PatchTaxRequest = Schemas['PatchTaxRequest']
export type ServiceCharge = Schemas['ServiceCharge']
export type CreateServiceChargeRequest = Schemas['CreateServiceChargeRequest']
export type PatchServiceChargeRequest = Schemas['PatchServiceChargeRequest']
export type ChargeCode = Schemas['ChargeCode']
export type ChargeType = Schemas['ChargeType']
export type PriceMode = Schemas['PriceMode']
export type TaxRule = Schemas['TaxRule']
export type ServiceRule = Schemas['ServiceRule']
export type ReplaceRulesRequest = Schemas['ReplaceRulesRequest']

export type ChargeCalculation = Schemas['ChargeCalculation']
export type CalculationComponent = Schemas['CalculationComponent']
export type CalculateChargeRequest = Schemas['CalculateChargeRequest']

export type RatePlan = Schemas['RatePlan']
export type MealPlan = Schemas['MealPlan']
export type CreateRatePlanRequest = Schemas['CreateRatePlanRequest']
export type PatchRatePlanRequest = Schemas['PatchRatePlanRequest']
export type RateGrid = Schemas['RateGrid']
export type RateCell = Schemas['RateCell']
export type Weekday = Schemas['Weekday']
export type FillRatesRequest = Schemas['FillRatesRequest']
export type FillRatesResult = Schemas['FillRatesResult']

export type AvailabilitySearch = Schemas['AvailabilitySearch']
export type TypeOffer = Schemas['TypeOffer']
export type PlanOffer = Schemas['PlanOffer']
export type FreeRoom = Schemas['FreeRoom']
export type Reservation = Schemas['Reservation']
export type ReservationRoom = Schemas['ReservationRoom']
export type ReservationSummary = Schemas['ReservationSummary']
export type ReservationSource = Schemas['ReservationSource']
export type CreateReservationRequest = Schemas['CreateReservationRequest']
export type CancelResult = Schemas['CancelResult']
export type NightRate = Schemas['NightRate']
export type TapeChart = Schemas['TapeChart']
export type OccupancyKind = Schemas['OccupancyKind']
export type FreeRoomsReport = Schemas['FreeRoomsReport']
export type AvailabilityCalendar = Schemas['AvailabilityCalendar']
export type TapeBooking = Schemas['TapeBooking']

export type Folio = Schemas['Folio']
export type FolioItem = Schemas['FolioItem']
export type FolioSummary = Schemas['FolioSummary']
export type FolioComponent = Schemas['FolioComponent']
export type Payment = Schemas['Payment']
export type PaymentMethod = Schemas['PaymentMethod']
export type PaymentResult = Schemas['PaymentResult']
export type ItemResult = Schemas['ItemResult']
export type MethodTotal = Schemas['MethodTotal']
export type Approval = Schemas['Approval']

export type Stay = Schemas['Stay']
export type StaySummary = Schemas['StaySummary']
export type StayDetail = Schemas['StayDetail']
export type Arrival = Schemas['Arrival']
export type CheckInResult = Schemas['CheckInResult']
export type CheckInRequest = Schemas['CheckInRequest']
export type WalkInRequest = Schemas['WalkInRequest']
export type MoveResult = Schemas['MoveResult']
export type CheckOutResult = Schemas['CheckOutResult']

export type RoomChargePreview = Schemas['RoomChargePreview']
export type RoomChargeItem = Schemas['RoomChargeItem']
export type RoomChargePostResponse = Schemas['RoomChargePostResponse']

export type NightAuditPreview = Schemas['NightAuditPreview']
export type NightAuditBlockers = Schemas['NightAuditBlockers']
export type NightAuditResult = Schemas['NightAuditResult']
export type NightAuditSummary = Schemas['NightAuditSummary']
export type UnresolvedArrival = Schemas['UnresolvedArrival']
export type NoShowsResult = Schemas['NoShowsResult']

export type DailySummaryReport = Schemas['DailySummaryReport']
export type RevenueReport = Schemas['RevenueReport']
export type TaxReport = Schemas['TaxReport']
export type CashierReport = Schemas['CashierReport']
export type StatisticsReport = Schemas['StatisticsReport']
export type HousekeepingProductivityReport = Schemas['HousekeepingProductivityReport']
export type HousekeepingDirtyRoomsReport = Schemas['HousekeepingDirtyRoomsReport']
export type MaintenanceReport = Schemas['MaintenanceReport']
export type StayListReport = Schemas['StayListReport']
export type ArrivalsReport = Schemas['ArrivalsReport']

export type AuditLog = Schemas['AuditLog']

export type ReservationEmails = Schemas['ReservationEmails']
export type EmailEntry = Schemas['EmailEntry']

export type Company = Schemas['Company']
export type CreateCompanyRequest = Schemas['CreateCompanyRequest']
export type PatchCompanyRequest = Schemas['PatchCompanyRequest']
export type Group = Schemas['Group']
export type CreateGroupRequest = Schemas['CreateGroupRequest']
export type PatchGroupRequest = Schemas['PatchGroupRequest']
export type GroupMember = Schemas['GroupMember']
export type CityLedgerAccount = Schemas['CityLedgerAccount']
export type CityLedgerReceipt = Schemas['CityLedgerReceipt']
export type CityLedgerStatement = Schemas['CityLedgerStatement']
export type CityLedgerAdjustment = Schemas['CityLedgerAdjustment']
export type CityLedgerStatementLine = Schemas['CityLedgerStatementLine']
export type CityLedgerAging = Schemas['CityLedgerAging']

export type CityLedgerInvoice = Schemas['CityLedgerInvoice']
export type CashierShift = Schemas['CashierShift']
export type CardFeeRule = Schemas['CardFeeRule']
export type Budget = Schemas['Budget']
export type Department = Schemas['Department']
export type DepartmentSetupReport = Schemas['DepartmentSetupReport']
export type DepartmentReport = Schemas['DepartmentReport']
export type DepartmentNode = Schemas['DepartmentNode']
export type BudgetDepartmentVsActual = Schemas['BudgetDepartmentVsActual']
export type BudgetDepartmentVariance = Schemas['BudgetDepartmentVariance']
export type CashFlow = Schemas['CashFlow']
export type BudgetStatisticsVsActual = Schemas['BudgetStatisticsVsActual']
export type BudgetStatisticsRow = Schemas['BudgetStatisticsRow']
export type BudgetRow = Schemas['BudgetRow']
export type BudgetMonth = Schemas['BudgetMonth']
export type BudgetAccountRef = Schemas['BudgetAccountRef']
export type BudgetVsActual = Schemas['BudgetVsActual']
export type BudgetVarianceLine = Schemas['BudgetVarianceLine']
export type BudgetVarianceAccount = Schemas['BudgetVarianceAccount']
export type BudgetCell = Schemas['BudgetCell']
export type ExpectedCardSettlements = Schemas['ExpectedCardSettlements']
export type CardSettlement = Schemas['CardSettlement']
export type SettlementProposal = Schemas['SettlementProposal']
export type CashierSettings = Schemas['CashierSettings']
export type CityLedgerOverdue = Schemas['CityLedgerOverdue']
export type CityLedgerOverdueCompany = Schemas['CityLedgerOverdueCompany']
export type CityLedgerLateFee = Schemas['CityLedgerLateFee']
export type CityLedgerReminder = Schemas['CityLedgerReminder']
export type CityLedgerInvoiceLine = Schemas['CityLedgerInvoiceLine']
export type CityLedgerCandidate = Schemas['CityLedgerCandidate']

export type HousekeepingFlags = Schemas['HousekeepingFlags']
export type HousekeepingStaffMember = Schemas['HousekeepingStaffMember']
export type HousekeepingTask = Schemas['HousekeepingTask']
export type HousekeepingTaskList = Schemas['HousekeepingTaskList']
export type HousekeepingWorkload = Schemas['HousekeepingWorkload']

export type MaintenanceRequest = Schemas['MaintenanceRequest']
export type MaintenanceBlock = Schemas['MaintenanceBlock']

export type LostFoundItem = Schemas['LostFoundItem']
export type LostFoundOwner = Schemas['LostFoundOwner']

export type GlAccount = Schemas['GlAccount']
export type GlAccountMapEntry = Schemas['GlAccountMapEntry']
export type GlCodeReport = Schemas['GlCodeReport']
export type GlCodeIssue = Schemas['GlCodeIssue']
export type Journal = Schemas['Journal']
export type JournalLine = Schemas['JournalLine']
export type GlPeriod = Schemas['GlPeriod']
export type FiscalYear = Schemas['FiscalYear']
export type Supplier = Schemas['Supplier']
export type BankAccount = Schemas['BankAccount']
export type Dashboard = Schemas['Dashboard']
export type YieldRule = Schemas['YieldRule']
export type RateQuote = Schemas['RateQuote']
export type TaxFilingProfile = Schemas['TaxFilingProfile']
export type TaxSettings = Schemas['TaxSettings']
export type TaxInvoice = Schemas['TaxInvoice']
export type TaxInvoicePreview = Schemas['TaxInvoicePreview']
export type TaxInvoiceCoverage = Schemas['TaxInvoiceCoverage']
export type TaxInvoiceExport = Schemas['TaxInvoiceExport']
export type TaxSettingsView = Schemas['TaxSettingsView']
export type TaxFilingPeriod = Schemas['TaxFilingPeriod']
export type TaxFilingWorksheet = Schemas['TaxFilingWorksheet']
export type TaxFilingReturn = Schemas['TaxFilingReturn']
export type TaxFilingLiability = Schemas['TaxFilingLiability']
export type BankStatement = Schemas['BankStatement']
export type BankStatementDetail = Schemas['BankStatementDetail']
export type UnclearedLine = Schemas['UnclearedLine']
export type Bill = Schemas['Bill']
export type OpenBill = Schemas['OpenBill']
export type SupplierPayment = Schemas['SupplierPayment']
export type PayablesAging = Schemas['PayablesAging']
export type TrialBalance = Schemas['TrialBalance']
export type GeneralLedger = Schemas['GeneralLedger']
export type IncomeStatement = Schemas['IncomeStatement']
export type BalanceSheet = Schemas['BalanceSheet']
export type StatementLine = Schemas['StatementLine']
export type Reconciliation = Schemas['Reconciliation']
