import type { components } from './schema'

type Schemas = components['schemas']

export type Property = Schemas['Property']
export type PropertyWithDay = Schemas['PropertyWithDay']
export type PropertySettings = Schemas['PropertySettings']
export type CreatePropertyRequest = Schemas['CreatePropertyRequest']
export type PatchPropertyRequest = Schemas['PatchPropertyRequest']
export type DayClock = Schemas['DayClock']
export type BusinessDay = Schemas['BusinessDay']

export type RoomType = Schemas['RoomType']
export type CreateRoomTypeRequest = Schemas['CreateRoomTypeRequest']
export type PatchRoomTypeRequest = Schemas['PatchRoomTypeRequest']
export type Room = Schemas['Room']
export type CreateRoomRequest = Schemas['CreateRoomRequest']
export type PatchRoomRequest = Schemas['PatchRoomRequest']
export type RoomBlock = Schemas['RoomBlock']
export type BlockType = Schemas['BlockType']
export type HousekeepingStatus = Schemas['HousekeepingStatus']
export type HousekeepingBoardRoom = Schemas['HousekeepingBoardRoom']
export type Occupancy = Schemas['Occupancy']

export type Guest = Schemas['Guest']
export type GuestView = Schemas['GuestView']
export type CreateGuestRequest = Schemas['CreateGuestRequest']
export type PatchGuestRequest = Schemas['PatchGuestRequest']
export type CreatedGuest = Schemas['CreatedGuest']
export type PossibleDuplicate = Schemas['PossibleDuplicate']
export type GuestHistoryItem = Schemas['GuestHistoryItem']

export type Tax = Schemas['Tax']
export type CreateTaxRequest = Schemas['CreateTaxRequest']
export type PatchTaxRequest = Schemas['PatchTaxRequest']
export type ServiceCharge = Schemas['ServiceCharge']
export type CreateServiceChargeRequest = Schemas['CreateServiceChargeRequest']
export type PatchServiceChargeRequest = Schemas['PatchServiceChargeRequest']
export type ChargeCode = Schemas['ChargeCode']
export type ChargeType = Schemas['ChargeType']
export type PriceMode = Schemas['PriceMode']
export type TaxRule = Schemas['TaxRule']
export type ServiceRule = Schemas['ServiceRule']
export type ReplaceRulesRequest = Schemas['ReplaceRulesRequest']
