// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ratesdb

import (
	"time"
)

type RatePlan struct {
	ID                 int64
	TenantID           int64
	PropertyID         int64
	Code               string
	Name               string
	Description        *string
	MealPlan           string
	CancellationPolicy *string
	IsRefundable       bool
	RoomChargeCodeID   int64
	IsActive           bool
	CreatedAt          time.Time
	CreatedBy          *int64
	UpdatedAt          time.Time
	UpdatedBy          *int64
}
