// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package ratesdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"kamarapms/internal/platform/civil"
)

const clearReferencePlans = `-- name: ClearReferencePlans :exec
UPDATE rate_plans SET is_reference = false, updated_by = $1
WHERE tenant_id = $2 AND property_id = $3 AND is_reference AND id <> $4
`

type ClearReferencePlansParams struct {
	ActorID    *int64
	TenantID   int64
	PropertyID int64
	ID         int64
}

// Only one plan per property is the reference plan: taking the flag over clears it from the others first.
func (q *Queries) ClearReferencePlans(ctx context.Context, arg ClearReferencePlansParams) error {
	_, err := q.db.Exec(ctx, clearReferencePlans,
		arg.ActorID,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
	)
	return err
}

const countRatesOfPlan = `-- name: CountRatesOfPlan :one
SELECT count(*) FROM rates WHERE tenant_id = $1 AND property_id = $2 AND rate_plan_id = $3
`

type CountRatesOfPlanParams struct {
	TenantID   int64
	PropertyID int64
	RatePlanID int64
}

func (q *Queries) CountRatesOfPlan(ctx context.Context, arg CountRatesOfPlanParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRatesOfPlan, arg.TenantID, arg.PropertyID, arg.RatePlanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRatePlan = `-- name: CreateRatePlan :one

INSERT INTO rate_plans (
    tenant_id, property_id, code, name, description, meal_plan, cancellation_policy, is_refundable,
    room_charge_code_id, occupancy_kind, is_active, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $12
)
RETURNING id, tenant_id, property_id, code, name, description, meal_plan, cancellation_policy, is_refundable, room_charge_code_id, is_active, created_at, created_by, updated_at, updated_by, occupancy_kind, is_reference
`

type CreateRatePlanParams struct {
	TenantID            int64
	PropertyID          int64
	Code                string
	Name                string
	RatePlanDescription *string
	MealPlan            string
	CancellationPolicy  *string
	IsRefundable        bool
	RoomChargeCodeID    int64
	OccupancyKind       string
	IsActive            bool
	ActorID             *int64
}

// Rates module queries (sqlc): rate plans and the rate grid. Scoped by tenant_id and property_id.
func (q *Queries) CreateRatePlan(ctx context.Context, arg CreateRatePlanParams) (RatePlan, error) {
	row := q.db.QueryRow(ctx, createRatePlan,
		arg.TenantID,
		arg.PropertyID,
		arg.Code,
		arg.Name,
		arg.RatePlanDescription,
		arg.MealPlan,
		arg.CancellationPolicy,
		arg.IsRefundable,
		arg.RoomChargeCodeID,
		arg.OccupancyKind,
		arg.IsActive,
		arg.ActorID,
	)
	var i RatePlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.MealPlan,
		&i.CancellationPolicy,
		&i.IsRefundable,
		&i.RoomChargeCodeID,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.OccupancyKind,
		&i.IsReference,
	)
	return i, err
}

const createYieldRule = `-- name: CreateYieldRule :one

INSERT INTO yield_rules (
    tenant_id, property_id, code, name, rate_plan_id, room_type_id, stay_from, stay_to, weekdays, occupancy_from, occupancy_to,
    lead_min, lead_max, stay_min, stay_max, adjustment_type, adjustment_value, floor_amount, cap_amount, priority, is_active,
    created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $19,
    $20, $21, $22, $22
)
RETURNING id, tenant_id, property_id, code, name, rate_plan_id, room_type_id, stay_from, stay_to, weekdays, occupancy_from, occupancy_to, lead_min, lead_max, stay_min, stay_max, adjustment_type, adjustment_value, floor_amount, cap_amount, priority, is_active, created_at, created_by, updated_at, updated_by
`

type CreateYieldRuleParams struct {
	TenantID        int64
	PropertyID      int64
	Code            string
	Name            string
	RatePlanID      *int64
	RoomTypeID      *int64
	StayFrom        *civil.Date
	StayTo          *civil.Date
	Weekdays        []string
	OccupancyFrom   *decimal.Decimal
	OccupancyTo     *decimal.Decimal
	LeadMin         pgtype.Int4
	LeadMax         pgtype.Int4
	StayMin         pgtype.Int4
	StayMax         pgtype.Int4
	AdjustmentType  string
	AdjustmentValue decimal.Decimal
	FloorAmount     *decimal.Decimal
	CapAmount       *decimal.Decimal
	Priority        int32
	IsActive        bool
	ActorID         *int64
}

// ---------------------------------------------------------------- yield rules
func (q *Queries) CreateYieldRule(ctx context.Context, arg CreateYieldRuleParams) (YieldRule, error) {
	row := q.db.QueryRow(ctx, createYieldRule,
		arg.TenantID,
		arg.PropertyID,
		arg.Code,
		arg.Name,
		arg.RatePlanID,
		arg.RoomTypeID,
		arg.StayFrom,
		arg.StayTo,
		arg.Weekdays,
		arg.OccupancyFrom,
		arg.OccupancyTo,
		arg.LeadMin,
		arg.LeadMax,
		arg.StayMin,
		arg.StayMax,
		arg.AdjustmentType,
		arg.AdjustmentValue,
		arg.FloorAmount,
		arg.CapAmount,
		arg.Priority,
		arg.IsActive,
		arg.ActorID,
	)
	var i YieldRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.RatePlanID,
		&i.RoomTypeID,
		&i.StayFrom,
		&i.StayTo,
		&i.Weekdays,
		&i.OccupancyFrom,
		&i.OccupancyTo,
		&i.LeadMin,
		&i.LeadMax,
		&i.StayMin,
		&i.StayMax,
		&i.AdjustmentType,
		&i.AdjustmentValue,
		&i.FloorAmount,
		&i.CapAmount,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteEmptiedRestrictions = `-- name: DeleteEmptiedRestrictions :one
WITH gone AS (
    DELETE FROM rate_restrictions
    WHERE tenant_id = $1 AND property_id = $2
      AND room_type_id IS NOT DISTINCT FROM $3::bigint AND rate_plan_id IS NOT DISTINCT FROM $4::bigint
      AND stay_date = ANY($5::date[])
      AND NOT $6::boolean -- when the request sets an attribute, a row that loses another one still says something
      AND (stop_sell IS NULL OR ($7::boolean AND NOT $8::boolean))
      AND (closed_to_arrival IS NULL OR ($9::boolean AND NOT $10::boolean))
      AND (closed_to_departure IS NULL OR ($11::boolean AND NOT $12::boolean))
      AND (min_stay IS NULL OR ($13::boolean AND NOT $14::boolean))
      AND (max_stay IS NULL OR ($15::boolean AND NOT $16::boolean))
    RETURNING 1
)
SELECT count(*)::bigint FROM gone
`

type DeleteEmptiedRestrictionsParams struct {
	TenantID      int64
	PropertyID    int64
	RoomTypeID    *int64
	RatePlanID    *int64
	Dates         []civil.Date
	HasSet        bool
	ClearStopSell bool
	SetStopSell   bool
	ClearCta      bool
	SetCta        bool
	ClearCtd      bool
	SetCtd        bool
	ClearMin      bool
	SetMin        bool
	ClearMax      bool
	SetMax        bool
}

// Removes the rows of one exact scope on the given dates that would say nothing after the change (every attribute is NULL already, or is being cleared and not set): a row must say
// something, so they are removed before the update rather than emptied by it.
func (q *Queries) DeleteEmptiedRestrictions(ctx context.Context, arg DeleteEmptiedRestrictionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteEmptiedRestrictions,
		arg.TenantID,
		arg.PropertyID,
		arg.RoomTypeID,
		arg.RatePlanID,
		arg.Dates,
		arg.HasSet,
		arg.ClearStopSell,
		arg.SetStopSell,
		arg.ClearCta,
		arg.SetCta,
		arg.ClearCtd,
		arg.SetCtd,
		arg.ClearMin,
		arg.SetMin,
		arg.ClearMax,
		arg.SetMax,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteYieldRule = `-- name: DeleteYieldRule :execrows
DELETE FROM yield_rules WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type DeleteYieldRuleParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) DeleteYieldRule(ctx context.Context, arg DeleteYieldRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteYieldRule, arg.TenantID, arg.PropertyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChargeCodeForPlan = `-- name: GetChargeCodeForPlan :one
SELECT id, code, charge_type, price_mode, is_active FROM charge_codes
WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type GetChargeCodeForPlanParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

type GetChargeCodeForPlanRow struct {
	ID         int64
	Code       string
	ChargeType string
	PriceMode  string
	IsActive   bool
}

// The room charge code of a plan: what the plan sells through, and how its grid amounts are read.
func (q *Queries) GetChargeCodeForPlan(ctx context.Context, arg GetChargeCodeForPlanParams) (GetChargeCodeForPlanRow, error) {
	row := q.db.QueryRow(ctx, getChargeCodeForPlan, arg.TenantID, arg.PropertyID, arg.ID)
	var i GetChargeCodeForPlanRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ChargeType,
		&i.PriceMode,
		&i.IsActive,
	)
	return i, err
}

const getChargeCodeForPlanShare = `-- name: GetChargeCodeForPlanShare :one
SELECT id, code, charge_type, price_mode, is_active FROM charge_codes
WHERE tenant_id = $1 AND property_id = $2 AND id = $3
FOR SHARE
`

type GetChargeCodeForPlanShareParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

type GetChargeCodeForPlanShareRow struct {
	ID         int64
	Code       string
	ChargeType string
	PriceMode  string
	IsActive   bool
}

// Share-locked, so the code cannot be deactivated (or re-typed) while a plan is being pointed at it.
func (q *Queries) GetChargeCodeForPlanShare(ctx context.Context, arg GetChargeCodeForPlanShareParams) (GetChargeCodeForPlanShareRow, error) {
	row := q.db.QueryRow(ctx, getChargeCodeForPlanShare, arg.TenantID, arg.PropertyID, arg.ID)
	var i GetChargeCodeForPlanShareRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ChargeType,
		&i.PriceMode,
		&i.IsActive,
	)
	return i, err
}

const getRatePlan = `-- name: GetRatePlan :one
SELECT id, tenant_id, property_id, code, name, description, meal_plan, cancellation_policy, is_refundable, room_charge_code_id, is_active, created_at, created_by, updated_at, updated_by, occupancy_kind, is_reference FROM rate_plans WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type GetRatePlanParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) GetRatePlan(ctx context.Context, arg GetRatePlanParams) (RatePlan, error) {
	row := q.db.QueryRow(ctx, getRatePlan, arg.TenantID, arg.PropertyID, arg.ID)
	var i RatePlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.MealPlan,
		&i.CancellationPolicy,
		&i.IsRefundable,
		&i.RoomChargeCodeID,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.OccupancyKind,
		&i.IsReference,
	)
	return i, err
}

const getRatePlanForShare = `-- name: GetRatePlanForShare :one
SELECT id, tenant_id, property_id, code, name, description, meal_plan, cancellation_policy, is_refundable, room_charge_code_id, is_active, created_at, created_by, updated_at, updated_by, occupancy_kind, is_reference FROM rate_plans WHERE tenant_id = $1 AND property_id = $2 AND id = $3 FOR SHARE
`

type GetRatePlanForShareParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) GetRatePlanForShare(ctx context.Context, arg GetRatePlanForShareParams) (RatePlan, error) {
	row := q.db.QueryRow(ctx, getRatePlanForShare, arg.TenantID, arg.PropertyID, arg.ID)
	var i RatePlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.MealPlan,
		&i.CancellationPolicy,
		&i.IsRefundable,
		&i.RoomChargeCodeID,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.OccupancyKind,
		&i.IsReference,
	)
	return i, err
}

const getRatePlanForUpdate = `-- name: GetRatePlanForUpdate :one
SELECT id, tenant_id, property_id, code, name, description, meal_plan, cancellation_policy, is_refundable, room_charge_code_id, is_active, created_at, created_by, updated_at, updated_by, occupancy_kind, is_reference FROM rate_plans WHERE tenant_id = $1 AND property_id = $2 AND id = $3 FOR UPDATE
`

type GetRatePlanForUpdateParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) GetRatePlanForUpdate(ctx context.Context, arg GetRatePlanForUpdateParams) (RatePlan, error) {
	row := q.db.QueryRow(ctx, getRatePlanForUpdate, arg.TenantID, arg.PropertyID, arg.ID)
	var i RatePlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.MealPlan,
		&i.CancellationPolicy,
		&i.IsRefundable,
		&i.RoomChargeCodeID,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.OccupancyKind,
		&i.IsReference,
	)
	return i, err
}

const getYieldRule = `-- name: GetYieldRule :one
SELECT id, tenant_id, property_id, code, name, rate_plan_id, room_type_id, stay_from, stay_to, weekdays, occupancy_from, occupancy_to, lead_min, lead_max, stay_min, stay_max, adjustment_type, adjustment_value, floor_amount, cap_amount, priority, is_active, created_at, created_by, updated_at, updated_by FROM yield_rules WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type GetYieldRuleParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) GetYieldRule(ctx context.Context, arg GetYieldRuleParams) (YieldRule, error) {
	row := q.db.QueryRow(ctx, getYieldRule, arg.TenantID, arg.PropertyID, arg.ID)
	var i YieldRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.RatePlanID,
		&i.RoomTypeID,
		&i.StayFrom,
		&i.StayTo,
		&i.Weekdays,
		&i.OccupancyFrom,
		&i.OccupancyTo,
		&i.LeadMin,
		&i.LeadMax,
		&i.StayMin,
		&i.StayMax,
		&i.AdjustmentType,
		&i.AdjustmentValue,
		&i.FloorAmount,
		&i.CapAmount,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getYieldRuleForUpdate = `-- name: GetYieldRuleForUpdate :one
SELECT id, tenant_id, property_id, code, name, rate_plan_id, room_type_id, stay_from, stay_to, weekdays, occupancy_from, occupancy_to, lead_min, lead_max, stay_min, stay_max, adjustment_type, adjustment_value, floor_amount, cap_amount, priority, is_active, created_at, created_by, updated_at, updated_by FROM yield_rules WHERE tenant_id = $1 AND property_id = $2 AND id = $3 FOR UPDATE
`

type GetYieldRuleForUpdateParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) GetYieldRuleForUpdate(ctx context.Context, arg GetYieldRuleForUpdateParams) (YieldRule, error) {
	row := q.db.QueryRow(ctx, getYieldRuleForUpdate, arg.TenantID, arg.PropertyID, arg.ID)
	var i YieldRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.RatePlanID,
		&i.RoomTypeID,
		&i.StayFrom,
		&i.StayTo,
		&i.Weekdays,
		&i.OccupancyFrom,
		&i.OccupancyTo,
		&i.LeadMin,
		&i.LeadMax,
		&i.StayMin,
		&i.StayMax,
		&i.AdjustmentType,
		&i.AdjustmentValue,
		&i.FloorAmount,
		&i.CapAmount,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const insertBedAdjustment = `-- name: InsertBedAdjustment :one
INSERT INTO rate_plan_bed_adjustments (tenant_id, property_id, rate_plan_id, room_type_id, bed_type_id, adjust_kind, amount, effective_from, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, property_id, rate_plan_id, room_type_id, bed_type_id, adjust_kind, amount, effective_from, created_at, created_by
`

type InsertBedAdjustmentParams struct {
	TenantID      int64
	PropertyID    int64
	RatePlanID    int64
	RoomTypeID    int64
	BedTypeID     int64
	AdjustKind    string
	Amount        decimal.Decimal
	EffectiveFrom civil.Date
	ActorID       *int64
}

func (q *Queries) InsertBedAdjustment(ctx context.Context, arg InsertBedAdjustmentParams) (RatePlanBedAdjustment, error) {
	row := q.db.QueryRow(ctx, insertBedAdjustment,
		arg.TenantID,
		arg.PropertyID,
		arg.RatePlanID,
		arg.RoomTypeID,
		arg.BedTypeID,
		arg.AdjustKind,
		arg.Amount,
		arg.EffectiveFrom,
		arg.ActorID,
	)
	var i RatePlanBedAdjustment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.RatePlanID,
		&i.RoomTypeID,
		&i.BedTypeID,
		&i.AdjustKind,
		&i.Amount,
		&i.EffectiveFrom,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listApplicableYieldRules = `-- name: ListApplicableYieldRules :many
SELECT id, tenant_id, property_id, code, name, rate_plan_id, room_type_id, stay_from, stay_to, weekdays, occupancy_from, occupancy_to, lead_min, lead_max, stay_min, stay_max, adjustment_type, adjustment_value, floor_amount, cap_amount, priority, is_active, created_at, created_by, updated_at, updated_by FROM yield_rules
WHERE tenant_id = $1 AND property_id = $2 AND is_active
  AND (rate_plan_id IS NULL OR rate_plan_id = $3)
  AND (room_type_id IS NULL OR room_type_id = $4)
ORDER BY priority, id
`

type ListApplicableYieldRulesParams struct {
	TenantID   int64
	PropertyID int64
	RatePlanID *int64
	RoomTypeID *int64
}

// The rules that can apply to a plan and room type (the ones that name another plan or type are left out).
func (q *Queries) ListApplicableYieldRules(ctx context.Context, arg ListApplicableYieldRulesParams) ([]YieldRule, error) {
	rows, err := q.db.Query(ctx, listApplicableYieldRules,
		arg.TenantID,
		arg.PropertyID,
		arg.RatePlanID,
		arg.RoomTypeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []YieldRule{}
	for rows.Next() {
		var i YieldRule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PropertyID,
			&i.Code,
			&i.Name,
			&i.RatePlanID,
			&i.RoomTypeID,
			&i.StayFrom,
			&i.StayTo,
			&i.Weekdays,
			&i.OccupancyFrom,
			&i.OccupancyTo,
			&i.LeadMin,
			&i.LeadMax,
			&i.StayMin,
			&i.StayMax,
			&i.AdjustmentType,
			&i.AdjustmentValue,
			&i.FloorAmount,
			&i.CapAmount,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBedAdjustments = `-- name: ListBedAdjustments :many
SELECT a.id, a.rate_plan_id, a.room_type_id, rt.code AS room_type_code, a.bed_type_id, bt.code AS bed_type_code, bt.name AS bed_type_name,
       a.adjust_kind, a.amount, a.effective_from, a.created_at
FROM rate_plan_bed_adjustments a
JOIN room_types rt ON rt.property_id = a.property_id AND rt.id = a.room_type_id
JOIN bed_types bt ON bt.property_id = a.property_id AND bt.id = a.bed_type_id
WHERE a.tenant_id = $1 AND a.property_id = $2 AND a.rate_plan_id = $3
ORDER BY rt.code, bt.sort_order, bt.id, a.effective_from DESC
`

type ListBedAdjustmentsParams struct {
	TenantID   int64
	PropertyID int64
	RatePlanID int64
}

type ListBedAdjustmentsRow struct {
	ID            int64
	RatePlanID    int64
	RoomTypeID    int64
	RoomTypeCode  string
	BedTypeID     int64
	BedTypeCode   string
	BedTypeName   string
	AdjustKind    string
	Amount        decimal.Decimal
	EffectiveFrom civil.Date
	CreatedAt     time.Time
}

func (q *Queries) ListBedAdjustments(ctx context.Context, arg ListBedAdjustmentsParams) ([]ListBedAdjustmentsRow, error) {
	rows, err := q.db.Query(ctx, listBedAdjustments, arg.TenantID, arg.PropertyID, arg.RatePlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBedAdjustmentsRow{}
	for rows.Next() {
		var i ListBedAdjustmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.RatePlanID,
			&i.RoomTypeID,
			&i.RoomTypeCode,
			&i.BedTypeID,
			&i.BedTypeCode,
			&i.BedTypeName,
			&i.AdjustKind,
			&i.Amount,
			&i.EffectiveFrom,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBedSupplements = `-- name: ListBedSupplements :many
SELECT adjust_kind, amount, effective_from FROM rate_plan_bed_adjustments
WHERE tenant_id = $1 AND property_id = $2 AND rate_plan_id = $3 AND room_type_id = $4 AND bed_type_id = $5
ORDER BY effective_from
`

type ListBedSupplementsParams struct {
	TenantID   int64
	PropertyID int64
	RatePlanID int64
	RoomTypeID int64
	BedTypeID  int64
}

type ListBedSupplementsRow struct {
	AdjustKind    string
	Amount        decimal.Decimal
	EffectiveFrom civil.Date
}

// The supplements of one bed type of one room type on a rate plan, oldest first (the one in force on a night is the latest that has started).
func (q *Queries) ListBedSupplements(ctx context.Context, arg ListBedSupplementsParams) ([]ListBedSupplementsRow, error) {
	rows, err := q.db.Query(ctx, listBedSupplements,
		arg.TenantID,
		arg.PropertyID,
		arg.RatePlanID,
		arg.RoomTypeID,
		arg.BedTypeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBedSupplementsRow{}
	for rows.Next() {
		var i ListBedSupplementsRow
		if err := rows.Scan(&i.AdjustKind, &i.Amount, &i.EffectiveFrom); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChargeCodeModes = `-- name: ListChargeCodeModes :many
SELECT id, code, price_mode FROM charge_codes WHERE tenant_id = $1 AND property_id = $2
`

type ListChargeCodeModesParams struct {
	TenantID   int64
	PropertyID int64
}

type ListChargeCodeModesRow struct {
	ID        int64
	Code      string
	PriceMode string
}

// id, code and price mode of every charge code of the property (to describe plans).
func (q *Queries) ListChargeCodeModes(ctx context.Context, arg ListChargeCodeModesParams) ([]ListChargeCodeModesRow, error) {
	rows, err := q.db.Query(ctx, listChargeCodeModes, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChargeCodeModesRow{}
	for rows.Next() {
		var i ListChargeCodeModesRow
		if err := rows.Scan(&i.ID, &i.Code, &i.PriceMode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNightRates = `-- name: ListNightRates :many
SELECT stay_date, amount FROM rates
WHERE tenant_id = $1 AND property_id = $2 AND rate_plan_id = $3 AND room_type_id = $4
  AND stay_date >= $5 AND stay_date < $6
ORDER BY stay_date
`

type ListNightRatesParams struct {
	TenantID   int64
	PropertyID int64
	RatePlanID int64
	RoomTypeID int64
	Arrival    civil.Date
	Departure  civil.Date
}

type ListNightRatesRow struct {
	StayDate civil.Date
	Amount   decimal.Decimal
}

// The nights of a stay priced from the grid: [arrival, departure) for one plan and room type.
func (q *Queries) ListNightRates(ctx context.Context, arg ListNightRatesParams) ([]ListNightRatesRow, error) {
	rows, err := q.db.Query(ctx, listNightRates,
		arg.TenantID,
		arg.PropertyID,
		arg.RatePlanID,
		arg.RoomTypeID,
		arg.Arrival,
		arg.Departure,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNightRatesRow{}
	for rows.Next() {
		var i ListNightRatesRow
		if err := rows.Scan(&i.StayDate, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatePlans = `-- name: ListRatePlans :many
SELECT id, tenant_id, property_id, code, name, description, meal_plan, cancellation_policy, is_refundable, room_charge_code_id, is_active, created_at, created_by, updated_at, updated_by, occupancy_kind, is_reference FROM rate_plans
WHERE tenant_id = $1 AND property_id = $2 AND id > $3
  AND ($4::boolean IS NULL OR is_active = $4::boolean)
ORDER BY id
LIMIT $5
`

type ListRatePlansParams struct {
	TenantID   int64
	PropertyID int64
	AfterID    int64
	Active     *bool
	RowLimit   int32
}

func (q *Queries) ListRatePlans(ctx context.Context, arg ListRatePlansParams) ([]RatePlan, error) {
	rows, err := q.db.Query(ctx, listRatePlans,
		arg.TenantID,
		arg.PropertyID,
		arg.AfterID,
		arg.Active,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RatePlan{}
	for rows.Next() {
		var i RatePlan
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PropertyID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.MealPlan,
			&i.CancellationPolicy,
			&i.IsRefundable,
			&i.RoomChargeCodeID,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.OccupancyKind,
			&i.IsReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRates = `-- name: ListRates :many
SELECT room_type_id, stay_date, amount FROM rates
WHERE tenant_id = $1 AND property_id = $2 AND rate_plan_id = $3
  AND stay_date >= $4 AND stay_date < $5
  AND ($6::bigint IS NULL OR room_type_id = $6::bigint)
ORDER BY stay_date, room_type_id
`

type ListRatesParams struct {
	TenantID   int64
	PropertyID int64
	RatePlanID int64
	FromDate   civil.Date
	ToDate     civil.Date
	RoomTypeID *int64
}

type ListRatesRow struct {
	RoomTypeID int64
	StayDate   civil.Date
	Amount     decimal.Decimal
}

func (q *Queries) ListRates(ctx context.Context, arg ListRatesParams) ([]ListRatesRow, error) {
	rows, err := q.db.Query(ctx, listRates,
		arg.TenantID,
		arg.PropertyID,
		arg.RatePlanID,
		arg.FromDate,
		arg.ToDate,
		arg.RoomTypeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRatesRow{}
	for rows.Next() {
		var i ListRatesRow
		if err := rows.Scan(&i.RoomTypeID, &i.StayDate, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestrictionRows = `-- name: ListRestrictionRows :many

SELECT id, room_type_id, rate_plan_id, stay_date, stop_sell, closed_to_arrival, closed_to_departure, min_stay, max_stay, note
FROM rate_restrictions
WHERE tenant_id = $1 AND property_id = $2 AND stay_date >= $3::date AND stay_date < $4::date
  AND ($5::bigint IS NULL OR room_type_id IS NULL OR room_type_id = $5::bigint)
  AND ($6::bigint IS NULL OR rate_plan_id IS NULL OR rate_plan_id = $6::bigint)
ORDER BY stay_date, room_type_id NULLS FIRST, rate_plan_id NULLS FIRST
`

type ListRestrictionRowsParams struct {
	TenantID   int64
	PropertyID int64
	FromDate   civil.Date
	ToDate     civil.Date
	RoomTypeID *int64
	RatePlanID *int64
}

type ListRestrictionRowsRow struct {
	ID                int64
	RoomTypeID        *int64
	RatePlanID        *int64
	StayDate          civil.Date
	StopSell          *bool
	ClosedToArrival   *bool
	ClosedToDeparture *bool
	MinStay           pgtype.Int2
	MaxStay           pgtype.Int2
	Note              *string
}

// ---------------------------------------------------------------- sales restrictions (the grid; the evaluator is availability.EvaluateStay)
// The rows of the grid in [from, to) that can speak for a room type and a rate plan (a row of a scope of NULL is for all); without a filter, every row.
func (q *Queries) ListRestrictionRows(ctx context.Context, arg ListRestrictionRowsParams) ([]ListRestrictionRowsRow, error) {
	rows, err := q.db.Query(ctx, listRestrictionRows,
		arg.TenantID,
		arg.PropertyID,
		arg.FromDate,
		arg.ToDate,
		arg.RoomTypeID,
		arg.RatePlanID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRestrictionRowsRow{}
	for rows.Next() {
		var i ListRestrictionRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomTypeID,
			&i.RatePlanID,
			&i.StayDate,
			&i.StopSell,
			&i.ClosedToArrival,
			&i.ClosedToDeparture,
			&i.MinStay,
			&i.MaxStay,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listYieldRules = `-- name: ListYieldRules :many
SELECT id, tenant_id, property_id, code, name, rate_plan_id, room_type_id, stay_from, stay_to, weekdays, occupancy_from, occupancy_to, lead_min, lead_max, stay_min, stay_max, adjustment_type, adjustment_value, floor_amount, cap_amount, priority, is_active, created_at, created_by, updated_at, updated_by FROM yield_rules
WHERE tenant_id = $1 AND property_id = $2
  AND ($3::boolean IS NULL OR is_active = $3::boolean)
ORDER BY priority, id
`

type ListYieldRulesParams struct {
	TenantID   int64
	PropertyID int64
	Active     *bool
}

func (q *Queries) ListYieldRules(ctx context.Context, arg ListYieldRulesParams) ([]YieldRule, error) {
	rows, err := q.db.Query(ctx, listYieldRules, arg.TenantID, arg.PropertyID, arg.Active)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []YieldRule{}
	for rows.Next() {
		var i YieldRule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PropertyID,
			&i.Code,
			&i.Name,
			&i.RatePlanID,
			&i.RoomTypeID,
			&i.StayFrom,
			&i.StayTo,
			&i.Weekdays,
			&i.OccupancyFrom,
			&i.OccupancyTo,
			&i.LeadMin,
			&i.LeadMax,
			&i.StayMin,
			&i.StayMax,
			&i.AdjustmentType,
			&i.AdjustmentValue,
			&i.FloorAmount,
			&i.CapAmount,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roomTypeExists = `-- name: RoomTypeExists :one
SELECT EXISTS (SELECT 1 FROM room_types WHERE tenant_id = $1 AND property_id = $2 AND id = $3)
`

type RoomTypeExistsParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) RoomTypeExists(ctx context.Context, arg RoomTypeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, roomTypeExists, arg.TenantID, arg.PropertyID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateRatePlan = `-- name: UpdateRatePlan :one
UPDATE rate_plans SET
    name = $1, description = $2, meal_plan = $3,
    cancellation_policy = $4, is_refundable = $5,
    room_charge_code_id = $6, is_reference = $7, is_active = $8, updated_by = $9
WHERE tenant_id = $10 AND property_id = $11 AND id = $12
RETURNING id, tenant_id, property_id, code, name, description, meal_plan, cancellation_policy, is_refundable, room_charge_code_id, is_active, created_at, created_by, updated_at, updated_by, occupancy_kind, is_reference
`

type UpdateRatePlanParams struct {
	Name                string
	RatePlanDescription *string
	MealPlan            string
	CancellationPolicy  *string
	IsRefundable        bool
	RoomChargeCodeID    int64
	IsReference         bool
	IsActive            bool
	ActorID             *int64
	TenantID            int64
	PropertyID          int64
	ID                  int64
}

func (q *Queries) UpdateRatePlan(ctx context.Context, arg UpdateRatePlanParams) (RatePlan, error) {
	row := q.db.QueryRow(ctx, updateRatePlan,
		arg.Name,
		arg.RatePlanDescription,
		arg.MealPlan,
		arg.CancellationPolicy,
		arg.IsRefundable,
		arg.RoomChargeCodeID,
		arg.IsReference,
		arg.IsActive,
		arg.ActorID,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
	)
	var i RatePlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.MealPlan,
		&i.CancellationPolicy,
		&i.IsRefundable,
		&i.RoomChargeCodeID,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.OccupancyKind,
		&i.IsReference,
	)
	return i, err
}

const updateRestrictions = `-- name: UpdateRestrictions :one
WITH changed AS (
    UPDATE rate_restrictions SET
        stop_sell           = CASE WHEN $1::boolean THEN $2::boolean WHEN $3::boolean THEN NULL ELSE stop_sell END,
        closed_to_arrival   = CASE WHEN $4::boolean THEN $5::boolean WHEN $6::boolean THEN NULL ELSE closed_to_arrival END,
        closed_to_departure = CASE WHEN $7::boolean THEN $8::boolean WHEN $9::boolean THEN NULL ELSE closed_to_departure END,
        min_stay            = CASE WHEN $10::boolean THEN $11::smallint WHEN $12::boolean THEN NULL ELSE min_stay END,
        max_stay            = CASE WHEN $13::boolean THEN $14::smallint WHEN $15::boolean THEN NULL ELSE max_stay END,
        note                = CASE WHEN $16::boolean THEN $17::varchar WHEN $18::boolean THEN NULL ELSE note END,
        updated_by          = $19::bigint
    WHERE tenant_id = $20 AND property_id = $21
      AND room_type_id IS NOT DISTINCT FROM $22::bigint AND rate_plan_id IS NOT DISTINCT FROM $23::bigint
      AND stay_date = ANY($24::date[])
    RETURNING 1
)
SELECT count(*)::bigint FROM changed
`

type UpdateRestrictionsParams struct {
	SetStopSell       bool
	StopSell          *bool
	ClearStopSell     bool
	SetCta            bool
	ClosedToArrival   *bool
	ClearCta          bool
	SetCtd            bool
	ClosedToDeparture *bool
	ClearCtd          bool
	SetMin            bool
	MinStay           pgtype.Int2
	ClearMin          bool
	SetMax            bool
	MaxStay           pgtype.Int2
	ClearMax          bool
	SetNote           bool
	Note              *string
	ClearNote         bool
	ActorID           *int64
	TenantID          int64
	PropertyID        int64
	RoomTypeID        *int64
	RatePlanID        *int64
	Dates             []civil.Date
}

// Applies a change to the rows that exist for one exact scope (NULL is the scope "all") on the given dates: an attribute with its set flag takes the value, one with its
// clear flag goes back to NULL, the others stay.
func (q *Queries) UpdateRestrictions(ctx context.Context, arg UpdateRestrictionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateRestrictions,
		arg.SetStopSell,
		arg.StopSell,
		arg.ClearStopSell,
		arg.SetCta,
		arg.ClosedToArrival,
		arg.ClearCta,
		arg.SetCtd,
		arg.ClosedToDeparture,
		arg.ClearCtd,
		arg.SetMin,
		arg.MinStay,
		arg.ClearMin,
		arg.SetMax,
		arg.MaxStay,
		arg.ClearMax,
		arg.SetNote,
		arg.Note,
		arg.ClearNote,
		arg.ActorID,
		arg.TenantID,
		arg.PropertyID,
		arg.RoomTypeID,
		arg.RatePlanID,
		arg.Dates,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateYieldRule = `-- name: UpdateYieldRule :one
UPDATE yield_rules SET
    name = $1, rate_plan_id = $2, room_type_id = $3,
    stay_from = $4, stay_to = $5, weekdays = $6,
    occupancy_from = $7, occupancy_to = $8,
    lead_min = $9, lead_max = $10, stay_min = $11, stay_max = $12,
    adjustment_type = $13, adjustment_value = $14,
    floor_amount = $15, cap_amount = $16, priority = $17, is_active = $18,
    updated_by = $19
WHERE tenant_id = $20 AND property_id = $21 AND id = $22
RETURNING id, tenant_id, property_id, code, name, rate_plan_id, room_type_id, stay_from, stay_to, weekdays, occupancy_from, occupancy_to, lead_min, lead_max, stay_min, stay_max, adjustment_type, adjustment_value, floor_amount, cap_amount, priority, is_active, created_at, created_by, updated_at, updated_by
`

type UpdateYieldRuleParams struct {
	Name            string
	RatePlanID      *int64
	RoomTypeID      *int64
	StayFrom        *civil.Date
	StayTo          *civil.Date
	Weekdays        []string
	OccupancyFrom   *decimal.Decimal
	OccupancyTo     *decimal.Decimal
	LeadMin         pgtype.Int4
	LeadMax         pgtype.Int4
	StayMin         pgtype.Int4
	StayMax         pgtype.Int4
	AdjustmentType  string
	AdjustmentValue decimal.Decimal
	FloorAmount     *decimal.Decimal
	CapAmount       *decimal.Decimal
	Priority        int32
	IsActive        bool
	ActorID         *int64
	TenantID        int64
	PropertyID      int64
	ID              int64
}

func (q *Queries) UpdateYieldRule(ctx context.Context, arg UpdateYieldRuleParams) (YieldRule, error) {
	row := q.db.QueryRow(ctx, updateYieldRule,
		arg.Name,
		arg.RatePlanID,
		arg.RoomTypeID,
		arg.StayFrom,
		arg.StayTo,
		arg.Weekdays,
		arg.OccupancyFrom,
		arg.OccupancyTo,
		arg.LeadMin,
		arg.LeadMax,
		arg.StayMin,
		arg.StayMax,
		arg.AdjustmentType,
		arg.AdjustmentValue,
		arg.FloorAmount,
		arg.CapAmount,
		arg.Priority,
		arg.IsActive,
		arg.ActorID,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
	)
	var i YieldRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.RatePlanID,
		&i.RoomTypeID,
		&i.StayFrom,
		&i.StayTo,
		&i.Weekdays,
		&i.OccupancyFrom,
		&i.OccupancyTo,
		&i.LeadMin,
		&i.LeadMax,
		&i.StayMin,
		&i.StayMax,
		&i.AdjustmentType,
		&i.AdjustmentValue,
		&i.FloorAmount,
		&i.CapAmount,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertRates = `-- name: UpsertRates :one
WITH written AS (
    INSERT INTO rates (tenant_id, property_id, rate_plan_id, room_type_id, stay_date, amount, updated_by)
    SELECT $1::bigint, $2::bigint, $3::bigint, t.room_type_id, d.stay_date::date, $4::numeric, $5::bigint
    FROM unnest($6::bigint[]) AS t (room_type_id)
    CROSS JOIN unnest($7::text[]) AS d (stay_date)
    ON CONFLICT (rate_plan_id, room_type_id, stay_date) DO UPDATE SET amount = EXCLUDED.amount, updated_by = EXCLUDED.updated_by
    RETURNING (xmax = 0) AS inserted
)
SELECT count(*)::bigint AS written, (count(*) FILTER (WHERE inserted))::bigint AS created FROM written
`

type UpsertRatesParams struct {
	TenantID    int64
	PropertyID  int64
	RatePlanID  int64
	Amount      decimal.Decimal
	ActorID     *int64
	RoomTypeIds []int64
	Dates       []string
}

type UpsertRatesRow struct {
	Written int64
	Created int64
}

// Bulk upsert of every (room type, date) pair. Dates arrive as ISO strings (already filtered by weekday).
// Returns how many nights were written and how many of them are new.
func (q *Queries) UpsertRates(ctx context.Context, arg UpsertRatesParams) (UpsertRatesRow, error) {
	row := q.db.QueryRow(ctx, upsertRates,
		arg.TenantID,
		arg.PropertyID,
		arg.RatePlanID,
		arg.Amount,
		arg.ActorID,
		arg.RoomTypeIds,
		arg.Dates,
	)
	var i UpsertRatesRow
	err := row.Scan(&i.Written, &i.Created)
	return i, err
}

const upsertRestrictions = `-- name: UpsertRestrictions :one
WITH written AS (
    INSERT INTO rate_restrictions (tenant_id, property_id, room_type_id, rate_plan_id, stay_date, stop_sell, closed_to_arrival, closed_to_departure, min_stay, max_stay, note, created_by, updated_by)
    SELECT $1::bigint, $2::bigint, $3::bigint, $4::bigint, d.stay_date,
           CASE WHEN $5::boolean THEN $6::boolean END, CASE WHEN $7::boolean THEN $8::boolean END,
           CASE WHEN $9::boolean THEN $10::boolean END, CASE WHEN $11::boolean THEN $12::smallint END,
           CASE WHEN $13::boolean THEN $14::smallint END, CASE WHEN $15::boolean THEN $16::varchar END,
           $17::bigint, $17::bigint
    FROM unnest($18::date[]) AS d (stay_date)
    ON CONFLICT (property_id, COALESCE(room_type_id, 0), COALESCE(rate_plan_id, 0), stay_date) DO UPDATE SET
        stop_sell           = CASE WHEN $5::boolean THEN EXCLUDED.stop_sell WHEN $19::boolean THEN NULL ELSE rate_restrictions.stop_sell END,
        closed_to_arrival   = CASE WHEN $7::boolean THEN EXCLUDED.closed_to_arrival WHEN $20::boolean THEN NULL ELSE rate_restrictions.closed_to_arrival END,
        closed_to_departure = CASE WHEN $9::boolean THEN EXCLUDED.closed_to_departure WHEN $21::boolean THEN NULL ELSE rate_restrictions.closed_to_departure END,
        min_stay            = CASE WHEN $11::boolean THEN EXCLUDED.min_stay WHEN $22::boolean THEN NULL ELSE rate_restrictions.min_stay END,
        max_stay            = CASE WHEN $13::boolean THEN EXCLUDED.max_stay WHEN $23::boolean THEN NULL ELSE rate_restrictions.max_stay END,
        note                = CASE WHEN $15::boolean THEN EXCLUDED.note WHEN $24::boolean THEN NULL ELSE rate_restrictions.note END,
        updated_by          = EXCLUDED.updated_by
    RETURNING (xmax = 0) AS inserted
)
SELECT (count(*) FILTER (WHERE inserted))::bigint AS created, (count(*) FILTER (WHERE NOT inserted))::bigint AS updated FROM written
`

type UpsertRestrictionsParams struct {
	TenantID          int64
	PropertyID        int64
	RoomTypeID        *int64
	RatePlanID        *int64
	SetStopSell       bool
	StopSell          *bool
	SetCta            bool
	ClosedToArrival   *bool
	SetCtd            bool
	ClosedToDeparture *bool
	SetMin            bool
	MinStay           pgtype.Int2
	SetMax            bool
	MaxStay           pgtype.Int2
	SetNote           bool
	Note              *string
	ActorID           *int64
	Dates             []civil.Date
	ClearStopSell     bool
	ClearCta          bool
	ClearCtd          bool
	ClearMin          bool
	ClearMax          bool
	ClearNote         bool
}

type UpsertRestrictionsRow struct {
	Created int64
	Updated int64
}

// Sets attributes for one exact scope on the given dates, creating the rows that are missing and applying the set and clear flags to those that exist, in one atomic statement
// (two fills of the same rows merge instead of losing one of them). Used when at least one of the five attributes is set: a row must say something.
func (q *Queries) UpsertRestrictions(ctx context.Context, arg UpsertRestrictionsParams) (UpsertRestrictionsRow, error) {
	row := q.db.QueryRow(ctx, upsertRestrictions,
		arg.TenantID,
		arg.PropertyID,
		arg.RoomTypeID,
		arg.RatePlanID,
		arg.SetStopSell,
		arg.StopSell,
		arg.SetCta,
		arg.ClosedToArrival,
		arg.SetCtd,
		arg.ClosedToDeparture,
		arg.SetMin,
		arg.MinStay,
		arg.SetMax,
		arg.MaxStay,
		arg.SetNote,
		arg.Note,
		arg.ActorID,
		arg.Dates,
		arg.ClearStopSell,
		arg.ClearCta,
		arg.ClearCtd,
		arg.ClearMin,
		arg.ClearMax,
		arg.ClearNote,
	)
	var i UpsertRestrictionsRow
	err := row.Scan(&i.Created, &i.Updated)
	return i, err
}
