// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package departmentsdb

import (
	"context"
)

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type DeleteDepartmentParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) DeleteDepartment(ctx context.Context, arg DeleteDepartmentParams) error {
	_, err := q.db.Exec(ctx, deleteDepartment, arg.TenantID, arg.PropertyID, arg.ID)
	return err
}

const insertDepartment = `-- name: InsertDepartment :one
INSERT INTO departments (tenant_id, property_id, parent_id, code, name, sort_order, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id
`

type InsertDepartmentParams struct {
	TenantID   int64
	PropertyID int64
	ParentID   *int64
	Code       string
	Name       string
	SortOrder  int32
	ActorID    *int64
}

func (q *Queries) InsertDepartment(ctx context.Context, arg InsertDepartmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertDepartment,
		arg.TenantID,
		arg.PropertyID,
		arg.ParentID,
		arg.Code,
		arg.Name,
		arg.SortOrder,
		arg.ActorID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listDepartments = `-- name: ListDepartments :many

SELECT d.id, d.parent_id, p.code AS parent_code, d.code, d.name, d.sort_order, d.is_active,
       (SELECT count(*) FROM departments c WHERE c.property_id = d.property_id AND c.parent_id = d.id)::int AS child_count,
       (EXISTS (SELECT 1 FROM gl_journal_lines l WHERE l.property_id = d.property_id AND l.department_id = d.id)
        OR EXISTS (SELECT 1 FROM folio_items i WHERE i.property_id = d.property_id AND i.department_id = d.id)
        OR EXISTS (SELECT 1 FROM charge_codes c WHERE c.property_id = d.property_id AND c.department_id = d.id)
        OR EXISTS (SELECT 1 FROM supplier_bill_lines b WHERE b.property_id = d.property_id AND b.department_id = d.id)
        OR EXISTS (SELECT 1 FROM budget_lines bl WHERE bl.property_id = d.property_id AND bl.department_id = d.id))::boolean AS in_use
FROM departments d
LEFT JOIN departments p ON p.property_id = d.property_id AND p.id = d.parent_id
WHERE d.tenant_id = $1 AND d.property_id = $2
  AND ($3::bigint IS NULL OR d.id = $3::bigint)
  AND ($4::boolean IS NULL OR d.is_active = $4::boolean)
ORDER BY COALESCE(p.sort_order, d.sort_order), COALESCE(p.code, d.code), (d.parent_id IS NOT NULL), d.sort_order, d.code
`

type ListDepartmentsParams struct {
	TenantID   int64
	PropertyID int64
	ID         *int64
	Active     *bool
}

type ListDepartmentsRow struct {
	ID         int64
	ParentID   *int64
	ParentCode *string
	Code       string
	Name       string
	SortOrder  int32
	IsActive   bool
	ChildCount int32
	InUse      bool
}

// Departments of a property. Every query is scoped by tenant_id and property_id.
func (q *Queries) ListDepartments(ctx context.Context, arg ListDepartmentsParams) ([]ListDepartmentsRow, error) {
	rows, err := q.db.Query(ctx, listDepartments,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
		arg.Active,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDepartmentsRow{}
	for rows.Next() {
		var i ListDepartmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.ParentCode,
			&i.Code,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
			&i.ChildCount,
			&i.InUse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedDepartments = `-- name: SeedDepartments :one
SELECT seed_departments($1, $2, $3)::int AS created
`

type SeedDepartmentsParams struct {
	TenantID   int64
	PropertyID int64
	ActorID    *int64
}

func (q *Queries) SeedDepartments(ctx context.Context, arg SeedDepartmentsParams) (int32, error) {
	row := q.db.QueryRow(ctx, seedDepartments, arg.TenantID, arg.PropertyID, arg.ActorID)
	var created int32
	err := row.Scan(&created)
	return created, err
}

const updateDepartment = `-- name: UpdateDepartment :exec
UPDATE departments SET name = $1, sort_order = $2, is_active = $3, updated_by = $4
WHERE tenant_id = $5 AND property_id = $6 AND id = $7
`

type UpdateDepartmentParams struct {
	Name       string
	SortOrder  int32
	IsActive   bool
	ActorID    *int64
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) error {
	_, err := q.db.Exec(ctx, updateDepartment,
		arg.Name,
		arg.SortOrder,
		arg.IsActive,
		arg.ActorID,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
	)
	return err
}
