// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package reportsdb

import (
	"context"

	"github.com/shopspring/decimal"
	"kamarapms/internal/platform/civil"
)

const cashierByMethod = `-- name: CashierByMethod :many
SELECT business_date, payment_method,
       COALESCE(sum(amount) FILTER (WHERE payment_type = 'PAYMENT' AND status = 'POSTED'), 0)::numeric AS payments,
       COALESCE(sum(amount) FILTER (WHERE payment_type = 'REFUND' AND status = 'POSTED'), 0)::numeric AS refunds,
       count(*) FILTER (WHERE status = 'POSTED')::int AS count,
       COALESCE(sum(amount) FILTER (WHERE status = 'VOIDED'), 0)::numeric AS voided,
       count(*) FILTER (WHERE status = 'VOIDED')::int AS voided_count
FROM (
    SELECT p.business_date, p.payment_method, p.payment_type, p.status, p.amount FROM payments p
    WHERE p.tenant_id = $1 AND p.property_id = $2 AND p.business_date BETWEEN $3::date AND $4::date
    UNION ALL
    SELECT r.business_date, r.payment_method, 'PAYMENT'::varchar, r.status, r.amount FROM city_ledger_receipts r
    WHERE r.tenant_id = $1 AND r.property_id = $2 AND r.business_date BETWEEN $3::date AND $4::date
) x
GROUP BY business_date, payment_method
ORDER BY business_date, payment_method
`

type CashierByMethodParams struct {
	TenantID   int64
	PropertyID int64
	FromDate   civil.Date
	ToDate     civil.Date
}

type CashierByMethodRow struct {
	BusinessDate  civil.Date
	PaymentMethod string
	Payments      decimal.Decimal
	Refunds       decimal.Decimal
	Count         int32
	Voided        decimal.Decimal
	VoidedCount   int32
}

// Folio payments plus the money companies paid against their city ledger account (receipts count as payments).
func (q *Queries) CashierByMethod(ctx context.Context, arg CashierByMethodParams) ([]CashierByMethodRow, error) {
	rows, err := q.db.Query(ctx, cashierByMethod,
		arg.TenantID,
		arg.PropertyID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CashierByMethodRow{}
	for rows.Next() {
		var i CashierByMethodRow
		if err := rows.Scan(
			&i.BusinessDate,
			&i.PaymentMethod,
			&i.Payments,
			&i.Refunds,
			&i.Count,
			&i.Voided,
			&i.VoidedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBusinessDay = `-- name: GetBusinessDay :one

SELECT business_date, status, summary FROM business_days
WHERE property_id = $1 AND business_date = $2::date
`

type GetBusinessDayParams struct {
	PropertyID int64
	Bd         civil.Date
}

type GetBusinessDayRow struct {
	BusinessDate civil.Date
	Status       string
	Summary      []byte
}

// Report queries (sqlc). Read-only. Every query is scoped by tenant_id and property_id. Money reports read the
// ledger rows and their component snapshots by business date, never the masters.
func (q *Queries) GetBusinessDay(ctx context.Context, arg GetBusinessDayParams) (GetBusinessDayRow, error) {
	row := q.db.QueryRow(ctx, getBusinessDay, arg.PropertyID, arg.Bd)
	var i GetBusinessDayRow
	err := row.Scan(&i.BusinessDate, &i.Status, &i.Summary)
	return i, err
}

const listClosedDaySummaries = `-- name: ListClosedDaySummaries :many
SELECT business_date, summary FROM business_days
WHERE property_id = $1 AND status = 'CLOSED' AND business_date BETWEEN $2::date AND $3::date
ORDER BY business_date
`

type ListClosedDaySummariesParams struct {
	PropertyID int64
	FromDate   civil.Date
	ToDate     civil.Date
}

type ListClosedDaySummariesRow struct {
	BusinessDate civil.Date
	Summary      []byte
}

// Closed days with a stored summary, for the statistics.
func (q *Queries) ListClosedDaySummaries(ctx context.Context, arg ListClosedDaySummariesParams) ([]ListClosedDaySummariesRow, error) {
	rows, err := q.db.Query(ctx, listClosedDaySummaries, arg.PropertyID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClosedDaySummariesRow{}
	for rows.Next() {
		var i ListClosedDaySummariesRow
		if err := rows.Scan(&i.BusinessDate, &i.Summary); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportArrivals = `-- name: ReportArrivals :many
SELECT l.id AS reservation_room_id, res.confirmation_number, l.status, l.arrival_date, l.departure_date, l.adult_count, l.child_count,
       t.code AS room_type_code, r.room_number, g.first_name AS guest_first_name, g.last_name AS guest_last_name
FROM reservation_rooms l
JOIN reservations res ON res.property_id = l.property_id AND res.id = l.reservation_id
JOIN room_types t ON t.property_id = l.property_id AND t.id = l.room_type_id
LEFT JOIN rooms r ON r.property_id = l.property_id AND r.id = l.room_id
LEFT JOIN guests g ON g.tenant_id = res.tenant_id AND g.id = COALESCE(l.guest_id, res.guest_id)
WHERE l.tenant_id = $1 AND l.property_id = $2 AND l.arrival_date = $3::date AND l.status <> 'DRAFT'
ORDER BY l.status, t.code, l.id
`

type ReportArrivalsParams struct {
	TenantID   int64
	PropertyID int64
	OnDate     civil.Date
}

type ReportArrivalsRow struct {
	ReservationRoomID  int64
	ConfirmationNumber string
	Status             string
	ArrivalDate        civil.Date
	DepartureDate      civil.Date
	AdultCount         int16
	ChildCount         int16
	RoomTypeCode       string
	RoomNumber         *string
	GuestFirstName     *string
	GuestLastName      *string
}

func (q *Queries) ReportArrivals(ctx context.Context, arg ReportArrivalsParams) ([]ReportArrivalsRow, error) {
	rows, err := q.db.Query(ctx, reportArrivals, arg.TenantID, arg.PropertyID, arg.OnDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportArrivalsRow{}
	for rows.Next() {
		var i ReportArrivalsRow
		if err := rows.Scan(
			&i.ReservationRoomID,
			&i.ConfirmationNumber,
			&i.Status,
			&i.ArrivalDate,
			&i.DepartureDate,
			&i.AdultCount,
			&i.ChildCount,
			&i.RoomTypeCode,
			&i.RoomNumber,
			&i.GuestFirstName,
			&i.GuestLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportDepartures = `-- name: ReportDepartures :many
SELECT s.id AS stay_id, s.stay_number, s.status, s.arrival_date, s.departure_date, res.confirmation_number,
       (SELECT r.room_number FROM stay_rooms sr JOIN rooms r ON r.property_id = sr.property_id AND r.id = sr.room_id
         WHERE sr.property_id = s.property_id AND sr.stay_id = s.id ORDER BY sr.start_business_date DESC, sr.id DESC LIMIT 1) AS room_number,
       g.first_name AS guest_first_name, g.last_name AS guest_last_name,
       COALESCE((SELECT sum(i.debit - i.credit) FROM folio_items i JOIN folios f ON f.property_id = i.property_id AND f.id = i.folio_id
                 WHERE f.property_id = s.property_id AND f.stay_id = s.id), 0)::numeric AS balance
FROM stays s
JOIN reservation_rooms l ON l.property_id = s.property_id AND l.id = s.reservation_room_id
JOIN reservations res ON res.property_id = l.property_id AND res.id = l.reservation_id
JOIN guests g ON g.tenant_id = s.tenant_id AND g.id = s.guest_id
WHERE s.tenant_id = $1 AND s.property_id = $2 AND s.departure_date = $3::date AND s.status <> 'CANCELLED'
ORDER BY s.status, s.id
`

type ReportDeparturesParams struct {
	TenantID   int64
	PropertyID int64
	OnDate     civil.Date
}

type ReportDeparturesRow struct {
	StayID             int64
	StayNumber         string
	Status             string
	ArrivalDate        civil.Date
	DepartureDate      civil.Date
	ConfirmationNumber string
	RoomNumber         string
	GuestFirstName     *string
	GuestLastName      string
	Balance            decimal.Decimal
}

// Stays that leave (or left) on the date, with the room of their last segment.
func (q *Queries) ReportDepartures(ctx context.Context, arg ReportDeparturesParams) ([]ReportDeparturesRow, error) {
	rows, err := q.db.Query(ctx, reportDepartures, arg.TenantID, arg.PropertyID, arg.OnDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportDeparturesRow{}
	for rows.Next() {
		var i ReportDeparturesRow
		if err := rows.Scan(
			&i.StayID,
			&i.StayNumber,
			&i.Status,
			&i.ArrivalDate,
			&i.DepartureDate,
			&i.ConfirmationNumber,
			&i.RoomNumber,
			&i.GuestFirstName,
			&i.GuestLastName,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportInHouse = `-- name: ReportInHouse :many
SELECT s.id AS stay_id, s.stay_number, res.confirmation_number, s.arrival_date, s.departure_date, s.adult_count, s.child_count,
       r.room_number, g.first_name AS guest_first_name, g.last_name AS guest_last_name,
       COALESCE((SELECT sum(i.debit - i.credit) FROM folio_items i JOIN folios f ON f.property_id = i.property_id AND f.id = i.folio_id
                 WHERE f.property_id = s.property_id AND f.stay_id = s.id), 0)::numeric AS balance
FROM stays s
JOIN reservation_rooms l ON l.property_id = s.property_id AND l.id = s.reservation_room_id
JOIN reservations res ON res.property_id = l.property_id AND res.id = l.reservation_id
JOIN guests g ON g.tenant_id = s.tenant_id AND g.id = s.guest_id
LEFT JOIN stay_rooms sr ON sr.property_id = s.property_id AND sr.stay_id = s.id AND sr.check_out_at IS NULL
LEFT JOIN rooms r ON r.property_id = sr.property_id AND r.id = sr.room_id
WHERE s.tenant_id = $1 AND s.property_id = $2 AND s.status = 'OPEN'
ORDER BY r.room_number, s.id
`

type ReportInHouseParams struct {
	TenantID   int64
	PropertyID int64
}

type ReportInHouseRow struct {
	StayID             int64
	StayNumber         string
	ConfirmationNumber string
	ArrivalDate        civil.Date
	DepartureDate      civil.Date
	AdultCount         int16
	ChildCount         int16
	RoomNumber         *string
	GuestFirstName     *string
	GuestLastName      string
	Balance            decimal.Decimal
}

func (q *Queries) ReportInHouse(ctx context.Context, arg ReportInHouseParams) ([]ReportInHouseRow, error) {
	rows, err := q.db.Query(ctx, reportInHouse, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportInHouseRow{}
	for rows.Next() {
		var i ReportInHouseRow
		if err := rows.Scan(
			&i.StayID,
			&i.StayNumber,
			&i.ConfirmationNumber,
			&i.ArrivalDate,
			&i.DepartureDate,
			&i.AdultCount,
			&i.ChildCount,
			&i.RoomNumber,
			&i.GuestFirstName,
			&i.GuestLastName,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueByChargeCode = `-- name: RevenueByChargeCode :many
SELECT c.id AS charge_code_id, c.code, c.name, c.charge_type, i.revenue_account_code,
       count(*)::int AS items,
       sum(i.base_amount)::numeric AS base, sum(i.discount_amount)::numeric AS discount, sum(i.net_amount)::numeric AS net,
       sum(i.service_charge_total)::numeric AS service, sum(i.tax_total)::numeric AS tax, sum(i.debit - i.credit)::numeric AS total
FROM folio_items i JOIN charge_codes c ON c.property_id = i.property_id AND c.id = i.charge_code_id
WHERE i.tenant_id = $1 AND i.property_id = $2 AND i.business_date BETWEEN $3::date AND $4::date
  AND i.transaction_type IN ('CHARGE', 'ADJUSTMENT', 'REVERSAL')
GROUP BY c.id, c.code, c.name, c.charge_type, i.revenue_account_code
ORDER BY c.charge_type, c.code, i.revenue_account_code NULLS FIRST
`

type RevenueByChargeCodeParams struct {
	TenantID   int64
	PropertyID int64
	FromDate   civil.Date
	ToDate     civil.Date
}

type RevenueByChargeCodeRow struct {
	ChargeCodeID       int64
	Code               string
	Name               string
	ChargeType         string
	RevenueAccountCode *string
	Items              int32
	Base               decimal.Decimal
	Discount           decimal.Decimal
	Net                decimal.Decimal
	Service            decimal.Decimal
	Tax                decimal.Decimal
	Total              decimal.Decimal
}

func (q *Queries) RevenueByChargeCode(ctx context.Context, arg RevenueByChargeCodeParams) ([]RevenueByChargeCodeRow, error) {
	rows, err := q.db.Query(ctx, revenueByChargeCode,
		arg.TenantID,
		arg.PropertyID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueByChargeCodeRow{}
	for rows.Next() {
		var i RevenueByChargeCodeRow
		if err := rows.Scan(
			&i.ChargeCodeID,
			&i.Code,
			&i.Name,
			&i.ChargeType,
			&i.RevenueAccountCode,
			&i.Items,
			&i.Base,
			&i.Discount,
			&i.Net,
			&i.Service,
			&i.Tax,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taxReport = `-- name: TaxReport :many
SELECT k.component_type, k.code, k.name, k.rate, k.gl_account_code,
       count(*)::int AS items, sum(k.base_amount)::numeric AS base, sum(k.amount)::numeric AS amount
FROM folio_item_components k JOIN folio_items i ON i.property_id = k.property_id AND i.id = k.folio_item_id
WHERE i.tenant_id = $1 AND i.property_id = $2 AND i.business_date BETWEEN $3::date AND $4::date
GROUP BY k.component_type, k.code, k.name, k.rate, k.gl_account_code
ORDER BY k.component_type DESC, k.code, k.rate, k.gl_account_code NULLS FIRST
`

type TaxReportParams struct {
	TenantID   int64
	PropertyID int64
	FromDate   civil.Date
	ToDate     civil.Date
}

type TaxReportRow struct {
	ComponentType string
	Code          string
	Name          string
	Rate          decimal.Decimal
	GlAccountCode *string
	Items         int32
	Base          decimal.Decimal
	Amount        decimal.Decimal
}

// Tax and service report from the component snapshots: a rate edited later shows up as its own line.
func (q *Queries) TaxReport(ctx context.Context, arg TaxReportParams) ([]TaxReportRow, error) {
	rows, err := q.db.Query(ctx, taxReport,
		arg.TenantID,
		arg.PropertyID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxReportRow{}
	for rows.Next() {
		var i TaxReportRow
		if err := rows.Scan(
			&i.ComponentType,
			&i.Code,
			&i.Name,
			&i.Rate,
			&i.GlAccountCode,
			&i.Items,
			&i.Base,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
