// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package foliosdb

import (
	"time"

	"github.com/shopspring/decimal"
	"kamarapms/internal/platform/civil"
)

type Folio struct {
	ID            int64
	TenantID      int64
	PropertyID    int64
	FolioNumber   string
	ReservationID int64
	StayID        *int64
	FolioType     string
	Status        string
	OpenedAt      time.Time
	ClosedAt      *time.Time
	ClosedBy      *int64
	Version       int32
	CreatedAt     time.Time
	CreatedBy     *int64
	UpdatedAt     time.Time
	UpdatedBy     *int64
	ClosedOn      *civil.Date
}

type FolioItem struct {
	ID                 int64
	TenantID           int64
	PropertyID         int64
	FolioID            int64
	BusinessDate       civil.Date
	TransactionAt      time.Time
	ServiceDate        civil.Date
	TransactionType    string
	ChargeCodeID       *int64
	PaymentID          *int64
	ReversesItemID     *int64
	StayID             *int64
	StayRoomID         *int64
	ReferenceType      *string
	ReferenceID        *string
	Description        string
	Quantity           decimal.Decimal
	UnitPrice          decimal.Decimal
	PriceMode          string
	BaseAmount         decimal.Decimal
	DiscountAmount     decimal.Decimal
	NetAmount          decimal.Decimal
	RoundingAdjustment decimal.Decimal
	ServiceChargeTotal decimal.Decimal
	TaxTotal           decimal.Decimal
	Debit              decimal.Decimal
	Credit             decimal.Decimal
	Source             string
	Reason             *string
	IdempotencyKey     *string
	CreatedAt          time.Time
	CreatedBy          *int64
	ApprovedBy         *int64
	RevenueAccountCode *string
	DepartmentID       *int64
}

type FolioItemComponent struct {
	ID              int64
	TenantID        int64
	PropertyID      int64
	FolioItemID     int64
	ComponentType   string
	TaxID           *int64
	ServiceChargeID *int64
	Code            string
	Name            string
	Rate            decimal.Decimal
	TaxOnService    *bool
	BaseAmount      decimal.Decimal
	Amount          decimal.Decimal
	Sequence        int16
	CreatedAt       time.Time
	GlAccountCode   *string
}

type Payment struct {
	ID                     int64
	TenantID               int64
	PropertyID             int64
	PaymentNumber          string
	FolioID                int64
	PaymentType            string
	PaymentMethod          string
	Amount                 decimal.Decimal
	PaidAt                 time.Time
	BusinessDate           civil.Date
	ReferenceNumber        *string
	RefundOfPaymentID      *int64
	Status                 string
	VoidedAt               *time.Time
	VoidedBy               *int64
	VoidReason             *string
	IdempotencyKey         *string
	Remarks                *string
	CreatedAt              time.Time
	CreatedBy              *int64
	ApprovedBy             *int64
	CompanyID              *int64
	ShiftID                *int64
	MdrRate                *decimal.Decimal
	MdrFee                 *decimal.Decimal
	ExpectedSettlementDate *civil.Date
}
