// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package cityledgerdb

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
	"kamarapms/internal/platform/civil"
)

const attachedNotes = `-- name: AttachedNotes :many
SELECT a.id, a.adjustment_number, a.amount, p.payment_number
FROM city_ledger_adjustment_invoices x
JOIN city_ledger_adjustments a ON a.property_id = x.property_id AND a.id = x.adjustment_id
JOIN payments p ON p.property_id = a.property_id AND p.id = a.payment_id
WHERE x.tenant_id = $1 AND x.property_id = $2 AND x.invoice_id = $3 AND x.released_at IS NULL
ORDER BY a.id
`

type AttachedNotesParams struct {
	TenantID   int64
	PropertyID int64
	InvoiceID  int64
}

type AttachedNotesRow struct {
	ID               int64
	AdjustmentNumber string
	Amount           decimal.Decimal
	PaymentNumber    string
}

func (q *Queries) AttachedNotes(ctx context.Context, arg AttachedNotesParams) ([]AttachedNotesRow, error) {
	rows, err := q.db.Query(ctx, attachedNotes, arg.TenantID, arg.PropertyID, arg.InvoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttachedNotesRow{}
	for rows.Next() {
		var i AttachedNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.AdjustmentNumber,
			&i.Amount,
			&i.PaymentNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLiveAdjustmentsOfInvoice = `-- name: CountLiveAdjustmentsOfInvoice :one
SELECT count(*)::int FROM city_ledger_adjustments WHERE tenant_id = $1 AND property_id = $2 AND invoice_id = $3 AND status = 'POSTED'
`

type CountLiveAdjustmentsOfInvoiceParams struct {
	TenantID   int64
	PropertyID int64
	InvoiceID  *int64
}

func (q *Queries) CountLiveAdjustmentsOfInvoice(ctx context.Context, arg CountLiveAdjustmentsOfInvoiceParams) (int32, error) {
	row := q.db.QueryRow(ctx, countLiveAdjustmentsOfInvoice, arg.TenantID, arg.PropertyID, arg.InvoiceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countLiveTaxInvoices = `-- name: CountLiveTaxInvoices :one
SELECT count(*)::int FROM tax_invoices WHERE tenant_id = $1 AND property_id = $2 AND city_ledger_invoice_id = $3 AND status = 'ISSUED'
`

type CountLiveTaxInvoicesParams struct {
	TenantID   int64
	PropertyID int64
	InvoiceID  *int64
}

// The tax invoices (faktur pajak) of an invoice that are not void.
func (q *Queries) CountLiveTaxInvoices(ctx context.Context, arg CountLiveTaxInvoicesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countLiveTaxInvoices, arg.TenantID, arg.PropertyID, arg.InvoiceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getAccount = `-- name: GetAccount :one
SELECT c.id, c.code, c.name, c.credit_limit, c.payment_terms_days, c.is_active, c.email, c.phone, c.address, c.contact_name,
       COALESCE((SELECT sum(p.amount) FROM payments p WHERE p.property_id = c.property_id AND p.company_id = c.id AND p.status = 'POSTED'), 0)::numeric AS transferred,
       COALESCE((SELECT sum(r.amount) FROM city_ledger_receipts r WHERE r.property_id = c.property_id AND r.company_id = c.id AND r.status = 'POSTED'), 0)::numeric AS received,
       COALESCE((SELECT sum(a.amount) FROM city_ledger_adjustments a WHERE a.property_id = c.property_id AND a.company_id = c.id AND a.status = 'POSTED'), 0)::numeric AS adjusted
FROM companies c
WHERE c.tenant_id = $1 AND c.property_id = $2 AND c.id = $3
`

type GetAccountParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

type GetAccountRow struct {
	ID               int64
	Code             string
	Name             string
	CreditLimit      *decimal.Decimal
	PaymentTermsDays int16
	IsActive         bool
	Email            *string
	Phone            *string
	Address          *string
	ContactName      *string
	Transferred      decimal.Decimal
	Received         decimal.Decimal
	Adjusted         decimal.Decimal
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.TenantID, arg.PropertyID, arg.ID)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreditLimit,
		&i.PaymentTermsDays,
		&i.IsActive,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.ContactName,
		&i.Transferred,
		&i.Received,
		&i.Adjusted,
	)
	return i, err
}

const getAdjustment = `-- name: GetAdjustment :one
SELECT id, tenant_id, property_id, adjustment_number, kind, company_id, invoice_id, payment_id, amount, business_date, reason, debit_account_id, status, journal_id, void_journal_id, voided_at, voided_by, void_reason, approved_by, idempotency_key, created_at, created_by FROM city_ledger_adjustments WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type GetAdjustmentParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) GetAdjustment(ctx context.Context, arg GetAdjustmentParams) (CityLedgerAdjustment, error) {
	row := q.db.QueryRow(ctx, getAdjustment, arg.TenantID, arg.PropertyID, arg.ID)
	var i CityLedgerAdjustment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.AdjustmentNumber,
		&i.Kind,
		&i.CompanyID,
		&i.InvoiceID,
		&i.PaymentID,
		&i.Amount,
		&i.BusinessDate,
		&i.Reason,
		&i.DebitAccountID,
		&i.Status,
		&i.JournalID,
		&i.VoidJournalID,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.ApprovedBy,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getAdjustmentByKey = `-- name: GetAdjustmentByKey :one
SELECT id, tenant_id, property_id, adjustment_number, kind, company_id, invoice_id, payment_id, amount, business_date, reason, debit_account_id, status, journal_id, void_journal_id, voided_at, voided_by, void_reason, approved_by, idempotency_key, created_at, created_by FROM city_ledger_adjustments WHERE tenant_id = $1 AND property_id = $2 AND idempotency_key = $3
`

type GetAdjustmentByKeyParams struct {
	TenantID       int64
	PropertyID     int64
	IdempotencyKey *string
}

func (q *Queries) GetAdjustmentByKey(ctx context.Context, arg GetAdjustmentByKeyParams) (CityLedgerAdjustment, error) {
	row := q.db.QueryRow(ctx, getAdjustmentByKey, arg.TenantID, arg.PropertyID, arg.IdempotencyKey)
	var i CityLedgerAdjustment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.AdjustmentNumber,
		&i.Kind,
		&i.CompanyID,
		&i.InvoiceID,
		&i.PaymentID,
		&i.Amount,
		&i.BusinessDate,
		&i.Reason,
		&i.DebitAccountID,
		&i.Status,
		&i.JournalID,
		&i.VoidJournalID,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.ApprovedBy,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, tenant_id, property_id, invoice_number, company_id, invoice_date, due_date, total, notes, status, voided_at, voided_by, void_reason, approved_by, idempotency_key, created_at, created_by FROM city_ledger_invoices WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type GetInvoiceParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) GetInvoice(ctx context.Context, arg GetInvoiceParams) (CityLedgerInvoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, arg.TenantID, arg.PropertyID, arg.ID)
	var i CityLedgerInvoice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.InvoiceNumber,
		&i.CompanyID,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Total,
		&i.Notes,
		&i.Status,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.ApprovedBy,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getInvoiceByKey = `-- name: GetInvoiceByKey :one
SELECT id, tenant_id, property_id, invoice_number, company_id, invoice_date, due_date, total, notes, status, voided_at, voided_by, void_reason, approved_by, idempotency_key, created_at, created_by FROM city_ledger_invoices WHERE tenant_id = $1 AND property_id = $2 AND idempotency_key = $3
`

type GetInvoiceByKeyParams struct {
	TenantID       int64
	PropertyID     int64
	IdempotencyKey *string
}

func (q *Queries) GetInvoiceByKey(ctx context.Context, arg GetInvoiceByKeyParams) (CityLedgerInvoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByKey, arg.TenantID, arg.PropertyID, arg.IdempotencyKey)
	var i CityLedgerInvoice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.InvoiceNumber,
		&i.CompanyID,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Total,
		&i.Notes,
		&i.Status,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.ApprovedBy,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getLateFee = `-- name: GetLateFee :one
SELECT monthly_rate, grace_days FROM city_ledger_late_fee_settings WHERE tenant_id = $1 AND property_id = $2
`

type GetLateFeeParams struct {
	TenantID   int64
	PropertyID int64
}

type GetLateFeeRow struct {
	MonthlyRate decimal.Decimal
	GraceDays   int16
}

func (q *Queries) GetLateFee(ctx context.Context, arg GetLateFeeParams) (GetLateFeeRow, error) {
	row := q.db.QueryRow(ctx, getLateFee, arg.TenantID, arg.PropertyID)
	var i GetLateFeeRow
	err := row.Scan(&i.MonthlyRate, &i.GraceDays)
	return i, err
}

const getReceipt = `-- name: GetReceipt :one
SELECT id, tenant_id, property_id, receipt_number, company_id, amount, payment_method, reference_number, remarks, business_date, paid_at, status, voided_at, voided_by, void_reason, idempotency_key, created_at, created_by, approved_by FROM city_ledger_receipts WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type GetReceiptParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) GetReceipt(ctx context.Context, arg GetReceiptParams) (CityLedgerReceipt, error) {
	row := q.db.QueryRow(ctx, getReceipt, arg.TenantID, arg.PropertyID, arg.ID)
	var i CityLedgerReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.ReceiptNumber,
		&i.CompanyID,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.Remarks,
		&i.BusinessDate,
		&i.PaidAt,
		&i.Status,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ApprovedBy,
	)
	return i, err
}

const getReceiptByKey = `-- name: GetReceiptByKey :one
SELECT id, tenant_id, property_id, receipt_number, company_id, amount, payment_method, reference_number, remarks, business_date, paid_at, status, voided_at, voided_by, void_reason, idempotency_key, created_at, created_by, approved_by FROM city_ledger_receipts WHERE tenant_id = $1 AND property_id = $2 AND idempotency_key = $3
`

type GetReceiptByKeyParams struct {
	TenantID       int64
	PropertyID     int64
	IdempotencyKey *string
}

func (q *Queries) GetReceiptByKey(ctx context.Context, arg GetReceiptByKeyParams) (CityLedgerReceipt, error) {
	row := q.db.QueryRow(ctx, getReceiptByKey, arg.TenantID, arg.PropertyID, arg.IdempotencyKey)
	var i CityLedgerReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.ReceiptNumber,
		&i.CompanyID,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.Remarks,
		&i.BusinessDate,
		&i.PaidAt,
		&i.Status,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ApprovedBy,
	)
	return i, err
}

const getReminderByKey = `-- name: GetReminderByKey :one
SELECT id, tenant_id, property_id, reminder_number, company_id, level, reminder_date, note, total_outstanding, total_interest, idempotency_key, created_at, created_by FROM city_ledger_reminders WHERE tenant_id = $1 AND property_id = $2 AND idempotency_key = $3
`

type GetReminderByKeyParams struct {
	TenantID       int64
	PropertyID     int64
	IdempotencyKey *string
}

func (q *Queries) GetReminderByKey(ctx context.Context, arg GetReminderByKeyParams) (CityLedgerReminder, error) {
	row := q.db.QueryRow(ctx, getReminderByKey, arg.TenantID, arg.PropertyID, arg.IdempotencyKey)
	var i CityLedgerReminder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.ReminderNumber,
		&i.CompanyID,
		&i.Level,
		&i.ReminderDate,
		&i.Note,
		&i.TotalOutstanding,
		&i.TotalInterest,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, payment_number, company_id, amount, status, payment_type, payment_method FROM payments WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type GetTransferParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

type GetTransferRow struct {
	ID            int64
	PaymentNumber string
	CompanyID     *int64
	Amount        decimal.Decimal
	Status        string
	PaymentType   string
	PaymentMethod string
}

// A transfer to a company, as a credit note needs to know it.
func (q *Queries) GetTransfer(ctx context.Context, arg GetTransferParams) (GetTransferRow, error) {
	row := q.db.QueryRow(ctx, getTransfer, arg.TenantID, arg.PropertyID, arg.ID)
	var i GetTransferRow
	err := row.Scan(
		&i.ID,
		&i.PaymentNumber,
		&i.CompanyID,
		&i.Amount,
		&i.Status,
		&i.PaymentType,
		&i.PaymentMethod,
	)
	return i, err
}

const insertAdjustment = `-- name: InsertAdjustment :one

INSERT INTO city_ledger_adjustments (tenant_id, property_id, adjustment_number, kind, company_id, invoice_id, payment_id, amount, business_date, reason, debit_account_id,
                                     journal_id, approved_by, idempotency_key, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
        $12, $13, $14, $15)
RETURNING id, tenant_id, property_id, adjustment_number, kind, company_id, invoice_id, payment_id, amount, business_date, reason, debit_account_id, status, journal_id, void_journal_id, voided_at, voided_by, void_reason, approved_by, idempotency_key, created_at, created_by
`

type InsertAdjustmentParams struct {
	TenantID         int64
	PropertyID       int64
	AdjustmentNumber string
	Kind             string
	CompanyID        int64
	InvoiceID        *int64
	PaymentID        *int64
	Amount           decimal.Decimal
	BusinessDate     civil.Date
	Reason           string
	DebitAccountID   *int64
	JournalID        int64
	ApprovedBy       *int64
	IdempotencyKey   *string
	ActorID          *int64
}

// ---------------------------------------------------------------------------------------------------------------
// Credit notes and write-offs
func (q *Queries) InsertAdjustment(ctx context.Context, arg InsertAdjustmentParams) (CityLedgerAdjustment, error) {
	row := q.db.QueryRow(ctx, insertAdjustment,
		arg.TenantID,
		arg.PropertyID,
		arg.AdjustmentNumber,
		arg.Kind,
		arg.CompanyID,
		arg.InvoiceID,
		arg.PaymentID,
		arg.Amount,
		arg.BusinessDate,
		arg.Reason,
		arg.DebitAccountID,
		arg.JournalID,
		arg.ApprovedBy,
		arg.IdempotencyKey,
		arg.ActorID,
	)
	var i CityLedgerAdjustment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.AdjustmentNumber,
		&i.Kind,
		&i.CompanyID,
		&i.InvoiceID,
		&i.PaymentID,
		&i.Amount,
		&i.BusinessDate,
		&i.Reason,
		&i.DebitAccountID,
		&i.Status,
		&i.JournalID,
		&i.VoidJournalID,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.ApprovedBy,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertAllocation = `-- name: InsertAllocation :exec
INSERT INTO city_ledger_receipt_allocations (tenant_id, property_id, receipt_id, invoice_id, company_id, amount)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAllocationParams struct {
	TenantID   int64
	PropertyID int64
	ReceiptID  int64
	InvoiceID  int64
	CompanyID  int64
	Amount     decimal.Decimal
}

func (q *Queries) InsertAllocation(ctx context.Context, arg InsertAllocationParams) error {
	_, err := q.db.Exec(ctx, insertAllocation,
		arg.TenantID,
		arg.PropertyID,
		arg.ReceiptID,
		arg.InvoiceID,
		arg.CompanyID,
		arg.Amount,
	)
	return err
}

const insertAttachment = `-- name: InsertAttachment :exec
INSERT INTO city_ledger_adjustment_invoices (tenant_id, property_id, adjustment_id, invoice_id) VALUES ($1, $2, $3, $4)
`

type InsertAttachmentParams struct {
	TenantID     int64
	PropertyID   int64
	AdjustmentID int64
	InvoiceID    int64
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) error {
	_, err := q.db.Exec(ctx, insertAttachment,
		arg.TenantID,
		arg.PropertyID,
		arg.AdjustmentID,
		arg.InvoiceID,
	)
	return err
}

const insertCreditNoteLine = `-- name: InsertCreditNoteLine :exec
INSERT INTO city_ledger_credit_note_lines (tenant_id, property_id, adjustment_id, line_no, description, account_id, net_amount, tax_id, tax_rate, tax_amount)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertCreditNoteLineParams struct {
	TenantID     int64
	PropertyID   int64
	AdjustmentID int64
	LineNo       int32
	Description  string
	AccountID    int64
	NetAmount    decimal.Decimal
	TaxID        *int64
	TaxRate      *decimal.Decimal
	TaxAmount    decimal.Decimal
}

func (q *Queries) InsertCreditNoteLine(ctx context.Context, arg InsertCreditNoteLineParams) error {
	_, err := q.db.Exec(ctx, insertCreditNoteLine,
		arg.TenantID,
		arg.PropertyID,
		arg.AdjustmentID,
		arg.LineNo,
		arg.Description,
		arg.AccountID,
		arg.NetAmount,
		arg.TaxID,
		arg.TaxRate,
		arg.TaxAmount,
	)
	return err
}

const insertInvoice = `-- name: InsertInvoice :one
INSERT INTO city_ledger_invoices (
    tenant_id, property_id, invoice_number, company_id, invoice_date, due_date, total, notes, idempotency_key, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, tenant_id, property_id, invoice_number, company_id, invoice_date, due_date, total, notes, status, voided_at, voided_by, void_reason, approved_by, idempotency_key, created_at, created_by
`

type InsertInvoiceParams struct {
	TenantID       int64
	PropertyID     int64
	InvoiceNumber  string
	CompanyID      int64
	InvoiceDate    civil.Date
	DueDate        civil.Date
	Total          decimal.Decimal
	Notes          *string
	IdempotencyKey *string
	ActorID        *int64
}

func (q *Queries) InsertInvoice(ctx context.Context, arg InsertInvoiceParams) (CityLedgerInvoice, error) {
	row := q.db.QueryRow(ctx, insertInvoice,
		arg.TenantID,
		arg.PropertyID,
		arg.InvoiceNumber,
		arg.CompanyID,
		arg.InvoiceDate,
		arg.DueDate,
		arg.Total,
		arg.Notes,
		arg.IdempotencyKey,
		arg.ActorID,
	)
	var i CityLedgerInvoice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.InvoiceNumber,
		&i.CompanyID,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Total,
		&i.Notes,
		&i.Status,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.ApprovedBy,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertInvoiceLine = `-- name: InsertInvoiceLine :exec
INSERT INTO city_ledger_invoice_lines (tenant_id, property_id, invoice_id, payment_id, amount)
VALUES ($1, $2, $3, $4, $5)
`

type InsertInvoiceLineParams struct {
	TenantID   int64
	PropertyID int64
	InvoiceID  int64
	PaymentID  int64
	Amount     decimal.Decimal
}

func (q *Queries) InsertInvoiceLine(ctx context.Context, arg InsertInvoiceLineParams) error {
	_, err := q.db.Exec(ctx, insertInvoiceLine,
		arg.TenantID,
		arg.PropertyID,
		arg.InvoiceID,
		arg.PaymentID,
		arg.Amount,
	)
	return err
}

const insertReceipt = `-- name: InsertReceipt :one
INSERT INTO city_ledger_receipts (
    tenant_id, property_id, receipt_number, company_id, amount, payment_method, reference_number, remarks,
    business_date, paid_at, idempotency_key, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12
)
RETURNING id, tenant_id, property_id, receipt_number, company_id, amount, payment_method, reference_number, remarks, business_date, paid_at, status, voided_at, voided_by, void_reason, idempotency_key, created_at, created_by, approved_by
`

type InsertReceiptParams struct {
	TenantID        int64
	PropertyID      int64
	ReceiptNumber   string
	CompanyID       int64
	Amount          decimal.Decimal
	PaymentMethod   string
	ReferenceNumber *string
	Remarks         *string
	BusinessDate    civil.Date
	PaidAt          time.Time
	IdempotencyKey  *string
	ActorID         *int64
}

func (q *Queries) InsertReceipt(ctx context.Context, arg InsertReceiptParams) (CityLedgerReceipt, error) {
	row := q.db.QueryRow(ctx, insertReceipt,
		arg.TenantID,
		arg.PropertyID,
		arg.ReceiptNumber,
		arg.CompanyID,
		arg.Amount,
		arg.PaymentMethod,
		arg.ReferenceNumber,
		arg.Remarks,
		arg.BusinessDate,
		arg.PaidAt,
		arg.IdempotencyKey,
		arg.ActorID,
	)
	var i CityLedgerReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.ReceiptNumber,
		&i.CompanyID,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.Remarks,
		&i.BusinessDate,
		&i.PaidAt,
		&i.Status,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ApprovedBy,
	)
	return i, err
}

const insertReminder = `-- name: InsertReminder :one
INSERT INTO city_ledger_reminders (tenant_id, property_id, reminder_number, company_id, level, reminder_date, note, total_outstanding, total_interest, idempotency_key, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, tenant_id, property_id, reminder_number, company_id, level, reminder_date, note, total_outstanding, total_interest, idempotency_key, created_at, created_by
`

type InsertReminderParams struct {
	TenantID         int64
	PropertyID       int64
	ReminderNumber   string
	CompanyID        int64
	Level            int16
	ReminderDate     civil.Date
	Note             *string
	TotalOutstanding decimal.Decimal
	TotalInterest    decimal.Decimal
	IdempotencyKey   *string
	ActorID          *int64
}

func (q *Queries) InsertReminder(ctx context.Context, arg InsertReminderParams) (CityLedgerReminder, error) {
	row := q.db.QueryRow(ctx, insertReminder,
		arg.TenantID,
		arg.PropertyID,
		arg.ReminderNumber,
		arg.CompanyID,
		arg.Level,
		arg.ReminderDate,
		arg.Note,
		arg.TotalOutstanding,
		arg.TotalInterest,
		arg.IdempotencyKey,
		arg.ActorID,
	)
	var i CityLedgerReminder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.ReminderNumber,
		&i.CompanyID,
		&i.Level,
		&i.ReminderDate,
		&i.Note,
		&i.TotalOutstanding,
		&i.TotalInterest,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertReminderItem = `-- name: InsertReminderItem :exec
INSERT INTO city_ledger_reminder_items (tenant_id, property_id, reminder_id, company_id, invoice_id, outstanding, days_overdue, interest)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertReminderItemParams struct {
	TenantID    int64
	PropertyID  int64
	ReminderID  int64
	CompanyID   int64
	InvoiceID   int64
	Outstanding decimal.Decimal
	DaysOverdue int32
	Interest    decimal.Decimal
}

func (q *Queries) InsertReminderItem(ctx context.Context, arg InsertReminderItemParams) error {
	_, err := q.db.Exec(ctx, insertReminderItem,
		arg.TenantID,
		arg.PropertyID,
		arg.ReminderID,
		arg.CompanyID,
		arg.InvoiceID,
		arg.Outstanding,
		arg.DaysOverdue,
		arg.Interest,
	)
	return err
}

const invoiceAdjusted = `-- name: InvoiceAdjusted :many
SELECT a.invoice_id, COALESCE(sum(a.amount) FILTER (WHERE a.kind = 'CREDIT_NOTE'), 0)::numeric AS credited, COALESCE(sum(a.amount) FILTER (WHERE a.kind = 'WRITE_OFF'), 0)::numeric AS written_off
FROM city_ledger_adjustments a
WHERE a.property_id = $1 AND a.status = 'POSTED' AND a.invoice_id = ANY ($2::bigint[])
GROUP BY a.invoice_id
`

type InvoiceAdjustedParams struct {
	PropertyID int64
	InvoiceIds []int64
}

type InvoiceAdjustedRow struct {
	InvoiceID  *int64
	Credited   decimal.Decimal
	WrittenOff decimal.Decimal
}

// What posted credit notes and write-offs have taken off invoices (those made against the invoice itself).
func (q *Queries) InvoiceAdjusted(ctx context.Context, arg InvoiceAdjustedParams) ([]InvoiceAdjustedRow, error) {
	rows, err := q.db.Query(ctx, invoiceAdjusted, arg.PropertyID, arg.InvoiceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceAdjustedRow{}
	for rows.Next() {
		var i InvoiceAdjustedRow
		if err := rows.Scan(&i.InvoiceID, &i.Credited, &i.WrittenOff); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const invoicePaid = `-- name: InvoicePaid :many
SELECT a.invoice_id, sum(a.amount)::numeric AS paid
FROM city_ledger_receipt_allocations a
JOIN city_ledger_receipts r ON r.property_id = a.property_id AND r.id = a.receipt_id AND r.status = 'POSTED'
WHERE a.property_id = $1 AND a.invoice_id = ANY($2::bigint[])
GROUP BY a.invoice_id
`

type InvoicePaidParams struct {
	PropertyID int64
	InvoiceIds []int64
}

type InvoicePaidRow struct {
	InvoiceID int64
	Paid      decimal.Decimal
}

// What invoices have been paid: the allocations of receipts that are still posted.
func (q *Queries) InvoicePaid(ctx context.Context, arg InvoicePaidParams) ([]InvoicePaidRow, error) {
	rows, err := q.db.Query(ctx, invoicePaid, arg.PropertyID, arg.InvoiceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoicePaidRow{}
	for rows.Next() {
		var i InvoicePaidRow
		if err := rows.Scan(&i.InvoiceID, &i.Paid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastRemindersOfInvoices = `-- name: LastRemindersOfInvoices :many
SELECT DISTINCT ON (it.invoice_id) it.invoice_id, m.reminder_number, m.reminder_date, m.level
FROM city_ledger_reminder_items it
JOIN city_ledger_reminders m ON m.property_id = it.property_id AND m.id = it.reminder_id
WHERE it.tenant_id = $1 AND it.property_id = $2 AND it.invoice_id = ANY ($3::bigint[])
ORDER BY it.invoice_id, m.id DESC
`

type LastRemindersOfInvoicesParams struct {
	TenantID   int64
	PropertyID int64
	InvoiceIds []int64
}

type LastRemindersOfInvoicesRow struct {
	InvoiceID      int64
	ReminderNumber string
	ReminderDate   civil.Date
	Level          int16
}

// The latest reminder that listed each of the invoices.
func (q *Queries) LastRemindersOfInvoices(ctx context.Context, arg LastRemindersOfInvoicesParams) ([]LastRemindersOfInvoicesRow, error) {
	rows, err := q.db.Query(ctx, lastRemindersOfInvoices, arg.TenantID, arg.PropertyID, arg.InvoiceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LastRemindersOfInvoicesRow{}
	for rows.Next() {
		var i LastRemindersOfInvoicesRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.ReminderNumber,
			&i.ReminderDate,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT a.id, a.code, a.name, a.credit_limit, a.payment_terms_days, a.is_active, a.transferred, a.received, a.adjusted
FROM (
    SELECT c.id, c.code, c.name, c.credit_limit, c.payment_terms_days, c.is_active,
           COALESCE((SELECT sum(p.amount) FROM payments p WHERE p.property_id = c.property_id AND p.company_id = c.id AND p.status = 'POSTED'), 0)::numeric AS transferred,
           COALESCE((SELECT sum(r.amount) FROM city_ledger_receipts r WHERE r.property_id = c.property_id AND r.company_id = c.id AND r.status = 'POSTED'), 0)::numeric AS received,
           COALESCE((SELECT sum(a.amount) FROM city_ledger_adjustments a WHERE a.property_id = c.property_id AND a.company_id = c.id AND a.status = 'POSTED'), 0)::numeric AS adjusted
    FROM companies c
    WHERE c.tenant_id = $1 AND c.property_id = $2 AND c.id > $3
      AND ($4::text IS NULL OR c.code ILIKE '%' || $4::text || '%' OR c.name ILIKE '%' || $4::text || '%')
) a
WHERE (NOT $5::boolean OR a.transferred - a.received - a.adjusted > 0)
ORDER BY a.id
LIMIT $6
`

type ListAccountsParams struct {
	TenantID   int64
	PropertyID int64
	AfterID    int64
	Q          *string
	Owing      bool
	RowLimit   int32
}

type ListAccountsRow struct {
	ID               int64
	Code             string
	Name             string
	CreditLimit      *decimal.Decimal
	PaymentTermsDays int16
	IsActive         bool
	Transferred      decimal.Decimal
	Received         decimal.Decimal
	Adjusted         decimal.Decimal
}

// Accounts: every company with what was transferred to it and what it paid back (posted rows only).
func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts,
		arg.TenantID,
		arg.PropertyID,
		arg.AfterID,
		arg.Q,
		arg.Owing,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.CreditLimit,
			&i.PaymentTermsDays,
			&i.IsActive,
			&i.Transferred,
			&i.Received,
			&i.Adjusted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdjustments = `-- name: ListAdjustments :many
SELECT a.id, a.adjustment_number, a.kind, a.company_id, a.invoice_id, i.invoice_number, a.payment_id, p.payment_number, a.amount, a.business_date, a.reason,
       a.debit_account_id, da.code AS debit_account_code, a.status, a.journal_id, jn.journal_number, a.voided_at, a.void_reason, a.approved_by, a.created_by, a.created_at,
       COALESCE((SELECT x.invoice_id FROM city_ledger_adjustment_invoices x WHERE x.property_id = a.property_id AND x.adjustment_id = a.id AND x.released_at IS NULL), 0)::bigint AS attached_invoice_id
FROM city_ledger_adjustments a
JOIN gl_journals jn ON jn.property_id = a.property_id AND jn.id = a.journal_id
LEFT JOIN city_ledger_invoices i ON i.property_id = a.property_id AND i.id = a.invoice_id
LEFT JOIN payments p ON p.property_id = a.property_id AND p.id = a.payment_id
LEFT JOIN gl_accounts da ON da.property_id = a.property_id AND da.id = a.debit_account_id
WHERE a.tenant_id = $1 AND a.property_id = $2
  AND ($3::bigint IS NULL OR a.id = $3::bigint)
  AND ($4::bigint IS NULL OR a.company_id = $4::bigint)
ORDER BY a.business_date DESC, a.id DESC
`

type ListAdjustmentsParams struct {
	TenantID   int64
	PropertyID int64
	ID         *int64
	CompanyID  *int64
}

type ListAdjustmentsRow struct {
	ID                int64
	AdjustmentNumber  string
	Kind              string
	CompanyID         int64
	InvoiceID         *int64
	InvoiceNumber     *string
	PaymentID         *int64
	PaymentNumber     *string
	Amount            decimal.Decimal
	BusinessDate      civil.Date
	Reason            string
	DebitAccountID    *int64
	DebitAccountCode  *string
	Status            string
	JournalID         int64
	JournalNumber     string
	VoidedAt          *time.Time
	VoidReason        *string
	ApprovedBy        *int64
	CreatedBy         *int64
	CreatedAt         time.Time
	AttachedInvoiceID int64
}

func (q *Queries) ListAdjustments(ctx context.Context, arg ListAdjustmentsParams) ([]ListAdjustmentsRow, error) {
	rows, err := q.db.Query(ctx, listAdjustments,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
		arg.CompanyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdjustmentsRow{}
	for rows.Next() {
		var i ListAdjustmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AdjustmentNumber,
			&i.Kind,
			&i.CompanyID,
			&i.InvoiceID,
			&i.InvoiceNumber,
			&i.PaymentID,
			&i.PaymentNumber,
			&i.Amount,
			&i.BusinessDate,
			&i.Reason,
			&i.DebitAccountID,
			&i.DebitAccountCode,
			&i.Status,
			&i.JournalID,
			&i.JournalNumber,
			&i.VoidedAt,
			&i.VoidReason,
			&i.ApprovedBy,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.AttachedInvoiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyAllocations = `-- name: ListCompanyAllocations :many
SELECT a.receipt_id, a.invoice_id, i.invoice_number, a.amount
FROM city_ledger_receipt_allocations a
JOIN city_ledger_invoices i ON i.property_id = a.property_id AND i.id = a.invoice_id
WHERE a.tenant_id = $1 AND a.property_id = $2 AND a.company_id = $3
ORDER BY a.receipt_id, a.invoice_id
`

type ListCompanyAllocationsParams struct {
	TenantID   int64
	PropertyID int64
	CompanyID  int64
}

type ListCompanyAllocationsRow struct {
	ReceiptID     int64
	InvoiceID     int64
	InvoiceNumber string
	Amount        decimal.Decimal
}

func (q *Queries) ListCompanyAllocations(ctx context.Context, arg ListCompanyAllocationsParams) ([]ListCompanyAllocationsRow, error) {
	rows, err := q.db.Query(ctx, listCompanyAllocations, arg.TenantID, arg.PropertyID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompanyAllocationsRow{}
	for rows.Next() {
		var i ListCompanyAllocationsRow
		if err := rows.Scan(
			&i.ReceiptID,
			&i.InvoiceID,
			&i.InvoiceNumber,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreditNoteLines = `-- name: ListCreditNoteLines :many
SELECT l.adjustment_id, l.line_no, l.description, l.account_id, ga.code AS account_code, ga.name AS account_name, l.net_amount, l.tax_id, t.code AS tax_code, l.tax_rate, l.tax_amount
FROM city_ledger_credit_note_lines l
JOIN gl_accounts ga ON ga.property_id = l.property_id AND ga.id = l.account_id
LEFT JOIN taxes t ON t.property_id = l.property_id AND t.id = l.tax_id
WHERE l.tenant_id = $1 AND l.property_id = $2 AND l.adjustment_id = ANY ($3::bigint[])
ORDER BY l.adjustment_id, l.line_no
`

type ListCreditNoteLinesParams struct {
	TenantID      int64
	PropertyID    int64
	AdjustmentIds []int64
}

type ListCreditNoteLinesRow struct {
	AdjustmentID int64
	LineNo       int32
	Description  string
	AccountID    int64
	AccountCode  string
	AccountName  string
	NetAmount    decimal.Decimal
	TaxID        *int64
	TaxCode      *string
	TaxRate      *decimal.Decimal
	TaxAmount    decimal.Decimal
}

func (q *Queries) ListCreditNoteLines(ctx context.Context, arg ListCreditNoteLinesParams) ([]ListCreditNoteLinesRow, error) {
	rows, err := q.db.Query(ctx, listCreditNoteLines, arg.TenantID, arg.PropertyID, arg.AdjustmentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCreditNoteLinesRow{}
	for rows.Next() {
		var i ListCreditNoteLinesRow
		if err := rows.Scan(
			&i.AdjustmentID,
			&i.LineNo,
			&i.Description,
			&i.AccountID,
			&i.AccountCode,
			&i.AccountName,
			&i.NetAmount,
			&i.TaxID,
			&i.TaxCode,
			&i.TaxRate,
			&i.TaxAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceCandidates = `-- name: ListInvoiceCandidates :many
SELECT p.id, p.payment_number, p.business_date, p.amount, p.reference_number,
       COALESCE((SELECT sum(a.amount) FROM city_ledger_adjustments a WHERE a.property_id = p.property_id AND a.payment_id = p.id AND a.status = 'POSTED'
                  AND NOT EXISTS (SELECT 1 FROM city_ledger_adjustment_invoices x WHERE x.property_id = a.property_id AND x.adjustment_id = a.id AND x.released_at IS NULL)), 0)::numeric AS credited,
       f.folio_number, r.confirmation_number,
       COALESCE(s.stay_number, '')::text AS stay_number, COALESCE(s.status, '')::text AS stay_status,
       s.arrival_date AS arrival_date, s.departure_date AS departure_date, s.actual_check_out_at AS checked_out_at,
       COALESCE(NULLIF(trim(COALESCE(g.first_name, '') || ' ' || COALESCE(g.last_name, '')), ''), '')::text AS guest_name,
       COALESCE((SELECT string_agg(ro.room_number, ', ' ORDER BY sr.start_business_date, sr.id)
                 FROM stay_rooms sr JOIN rooms ro ON ro.property_id = sr.property_id AND ro.id = sr.room_id
                 WHERE sr.property_id = s.property_id AND sr.stay_id = s.id), '')::text AS room_numbers
FROM payments p
JOIN folios f ON f.property_id = p.property_id AND f.id = p.folio_id
JOIN reservations r ON r.property_id = f.property_id AND r.id = f.reservation_id
LEFT JOIN stays s ON s.property_id = f.property_id AND s.id = f.stay_id
LEFT JOIN guests g ON g.tenant_id = s.tenant_id AND g.id = s.guest_id
WHERE p.tenant_id = $1 AND p.property_id = $2 AND p.company_id = $3
  AND p.payment_type = 'PAYMENT' AND p.status = 'POSTED'
  AND ($4::bigint[] IS NULL OR p.id = ANY($4::bigint[]))
  AND NOT EXISTS (SELECT 1 FROM city_ledger_invoice_lines l WHERE l.property_id = p.property_id AND l.payment_id = p.id AND l.released_at IS NULL)
ORDER BY p.business_date, p.id
`

type ListInvoiceCandidatesParams struct {
	TenantID   int64
	PropertyID int64
	CompanyID  *int64
	Ids        []int64
}

type ListInvoiceCandidatesRow struct {
	ID                 int64
	PaymentNumber      string
	BusinessDate       civil.Date
	Amount             decimal.Decimal
	ReferenceNumber    *string
	Credited           decimal.Decimal
	FolioNumber        string
	ConfirmationNumber string
	StayNumber         string
	StayStatus         string
	ArrivalDate        *civil.Date
	DepartureDate      *civil.Date
	CheckedOutAt       *time.Time
	GuestName          string
	RoomNumbers        string
}

// Transfers of a company that are not on a live invoice, with the state of the stay behind them. Only a transfer
// whose guest has checked out can be invoiced. ids narrows the list to the transfers an invoice asks for.
func (q *Queries) ListInvoiceCandidates(ctx context.Context, arg ListInvoiceCandidatesParams) ([]ListInvoiceCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceCandidates,
		arg.TenantID,
		arg.PropertyID,
		arg.CompanyID,
		arg.Ids,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceCandidatesRow{}
	for rows.Next() {
		var i ListInvoiceCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentNumber,
			&i.BusinessDate,
			&i.Amount,
			&i.ReferenceNumber,
			&i.Credited,
			&i.FolioNumber,
			&i.ConfirmationNumber,
			&i.StayNumber,
			&i.StayStatus,
			&i.ArrivalDate,
			&i.DepartureDate,
			&i.CheckedOutAt,
			&i.GuestName,
			&i.RoomNumbers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceLines = `-- name: ListInvoiceLines :many
SELECT p.id AS payment_id, p.payment_number, p.business_date, l.amount, p.reference_number,
       f.folio_number, r.confirmation_number,
       COALESCE(s.stay_number, '')::text AS stay_number,
       s.arrival_date AS arrival_date, s.departure_date AS departure_date, s.actual_check_out_at AS checked_out_at,
       COALESCE(NULLIF(trim(COALESCE(g.first_name, '') || ' ' || COALESCE(g.last_name, '')), ''), '')::text AS guest_name,
       COALESCE((SELECT string_agg(ro.room_number, ', ' ORDER BY sr.start_business_date, sr.id)
                 FROM stay_rooms sr JOIN rooms ro ON ro.property_id = sr.property_id AND ro.id = sr.room_id
                 WHERE sr.property_id = s.property_id AND sr.stay_id = s.id), '')::text AS room_numbers
FROM city_ledger_invoice_lines l
JOIN payments p ON p.property_id = l.property_id AND p.id = l.payment_id
JOIN folios f ON f.property_id = p.property_id AND f.id = p.folio_id
JOIN reservations r ON r.property_id = f.property_id AND r.id = f.reservation_id
LEFT JOIN stays s ON s.property_id = f.property_id AND s.id = f.stay_id
LEFT JOIN guests g ON g.tenant_id = s.tenant_id AND g.id = s.guest_id
WHERE l.tenant_id = $1 AND l.property_id = $2 AND l.invoice_id = $3
ORDER BY p.business_date, p.id
`

type ListInvoiceLinesParams struct {
	TenantID   int64
	PropertyID int64
	InvoiceID  int64
}

type ListInvoiceLinesRow struct {
	PaymentID          int64
	PaymentNumber      string
	BusinessDate       civil.Date
	Amount             decimal.Decimal
	ReferenceNumber    *string
	FolioNumber        string
	ConfirmationNumber string
	StayNumber         string
	ArrivalDate        *civil.Date
	DepartureDate      *civil.Date
	CheckedOutAt       *time.Time
	GuestName          string
	RoomNumbers        string
}

func (q *Queries) ListInvoiceLines(ctx context.Context, arg ListInvoiceLinesParams) ([]ListInvoiceLinesRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceLines, arg.TenantID, arg.PropertyID, arg.InvoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceLinesRow{}
	for rows.Next() {
		var i ListInvoiceLinesRow
		if err := rows.Scan(
			&i.PaymentID,
			&i.PaymentNumber,
			&i.BusinessDate,
			&i.Amount,
			&i.ReferenceNumber,
			&i.FolioNumber,
			&i.ConfirmationNumber,
			&i.StayNumber,
			&i.ArrivalDate,
			&i.DepartureDate,
			&i.CheckedOutAt,
			&i.GuestName,
			&i.RoomNumbers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, tenant_id, property_id, invoice_number, company_id, invoice_date, due_date, total, notes, status, voided_at, voided_by, void_reason, approved_by, idempotency_key, created_at, created_by FROM city_ledger_invoices
WHERE tenant_id = $1 AND property_id = $2 AND company_id = $3
ORDER BY invoice_date DESC, id DESC
`

type ListInvoicesParams struct {
	TenantID   int64
	PropertyID int64
	CompanyID  int64
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]CityLedgerInvoice, error) {
	rows, err := q.db.Query(ctx, listInvoices, arg.TenantID, arg.PropertyID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CityLedgerInvoice{}
	for rows.Next() {
		var i CityLedgerInvoice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PropertyID,
			&i.InvoiceNumber,
			&i.CompanyID,
			&i.InvoiceDate,
			&i.DueDate,
			&i.Total,
			&i.Notes,
			&i.Status,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.VoidReason,
			&i.ApprovedBy,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueInvoices = `-- name: ListOverdueInvoices :many

SELECT i.id, i.invoice_number, i.company_id, c.code AS company_code, c.name AS company_name, i.invoice_date, i.due_date, i.total,
       COALESCE((SELECT sum(a.amount) FROM city_ledger_receipt_allocations a JOIN city_ledger_receipts r ON r.property_id = a.property_id AND r.id = a.receipt_id AND r.status = 'POSTED'
                  WHERE a.property_id = i.property_id AND a.invoice_id = i.id), 0)::numeric AS paid,
       COALESCE((SELECT sum(x.amount) FROM city_ledger_adjustments x WHERE x.property_id = i.property_id AND x.invoice_id = i.id AND x.status = 'POSTED'), 0)::numeric AS adjusted
FROM city_ledger_invoices i
JOIN companies c ON c.property_id = i.property_id AND c.id = i.company_id
WHERE i.tenant_id = $1 AND i.property_id = $2 AND i.status = 'ISSUED' AND i.due_date < $3::date
  AND ($4::bigint IS NULL OR i.company_id = $4::bigint)
ORDER BY c.code, i.due_date, i.id
`

type ListOverdueInvoicesParams struct {
	TenantID   int64
	PropertyID int64
	AsOf       civil.Date
	CompanyID  *int64
}

type ListOverdueInvoicesRow struct {
	ID            int64
	InvoiceNumber string
	CompanyID     int64
	CompanyCode   string
	CompanyName   string
	InvoiceDate   civil.Date
	DueDate       civil.Date
	Total         decimal.Decimal
	Paid          decimal.Decimal
	Adjusted      decimal.Decimal
}

// ---------------------------------------------------------------------------------------------------------------
// Overdue invoices, reminders and the late fee
// Issued invoices whose due date is before a date, with what is taken off them (the amounts that are still owed are worked out by the caller).
func (q *Queries) ListOverdueInvoices(ctx context.Context, arg ListOverdueInvoicesParams) ([]ListOverdueInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listOverdueInvoices,
		arg.TenantID,
		arg.PropertyID,
		arg.AsOf,
		arg.CompanyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverdueInvoicesRow{}
	for rows.Next() {
		var i ListOverdueInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.CompanyID,
			&i.CompanyCode,
			&i.CompanyName,
			&i.InvoiceDate,
			&i.DueDate,
			&i.Total,
			&i.Paid,
			&i.Adjusted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceipts = `-- name: ListReceipts :many
SELECT id, tenant_id, property_id, receipt_number, company_id, amount, payment_method, reference_number, remarks, business_date, paid_at, status, voided_at, voided_by, void_reason, idempotency_key, created_at, created_by, approved_by FROM city_ledger_receipts
WHERE tenant_id = $1 AND property_id = $2 AND company_id = $3
ORDER BY business_date, id
`

type ListReceiptsParams struct {
	TenantID   int64
	PropertyID int64
	CompanyID  int64
}

func (q *Queries) ListReceipts(ctx context.Context, arg ListReceiptsParams) ([]CityLedgerReceipt, error) {
	rows, err := q.db.Query(ctx, listReceipts, arg.TenantID, arg.PropertyID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CityLedgerReceipt{}
	for rows.Next() {
		var i CityLedgerReceipt
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PropertyID,
			&i.ReceiptNumber,
			&i.CompanyID,
			&i.Amount,
			&i.PaymentMethod,
			&i.ReferenceNumber,
			&i.Remarks,
			&i.BusinessDate,
			&i.PaidAt,
			&i.Status,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.VoidReason,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ApprovedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReminderItems = `-- name: ListReminderItems :many
SELECT it.reminder_id, it.invoice_id, i.invoice_number, i.invoice_date, i.due_date, it.outstanding, it.days_overdue, it.interest
FROM city_ledger_reminder_items it
JOIN city_ledger_invoices i ON i.property_id = it.property_id AND i.id = it.invoice_id
WHERE it.tenant_id = $1 AND it.property_id = $2 AND it.reminder_id = ANY ($3::bigint[])
ORDER BY it.reminder_id, i.due_date, i.id
`

type ListReminderItemsParams struct {
	TenantID    int64
	PropertyID  int64
	ReminderIds []int64
}

type ListReminderItemsRow struct {
	ReminderID    int64
	InvoiceID     int64
	InvoiceNumber string
	InvoiceDate   civil.Date
	DueDate       civil.Date
	Outstanding   decimal.Decimal
	DaysOverdue   int32
	Interest      decimal.Decimal
}

func (q *Queries) ListReminderItems(ctx context.Context, arg ListReminderItemsParams) ([]ListReminderItemsRow, error) {
	rows, err := q.db.Query(ctx, listReminderItems, arg.TenantID, arg.PropertyID, arg.ReminderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReminderItemsRow{}
	for rows.Next() {
		var i ListReminderItemsRow
		if err := rows.Scan(
			&i.ReminderID,
			&i.InvoiceID,
			&i.InvoiceNumber,
			&i.InvoiceDate,
			&i.DueDate,
			&i.Outstanding,
			&i.DaysOverdue,
			&i.Interest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReminders = `-- name: ListReminders :many
SELECT id, tenant_id, property_id, reminder_number, company_id, level, reminder_date, note, total_outstanding, total_interest, idempotency_key, created_at, created_by FROM city_ledger_reminders
WHERE tenant_id = $1 AND property_id = $2
  AND ($3::bigint IS NULL OR id = $3::bigint)
  AND ($4::bigint IS NULL OR company_id = $4::bigint)
ORDER BY reminder_date DESC, id DESC
`

type ListRemindersParams struct {
	TenantID   int64
	PropertyID int64
	ID         *int64
	CompanyID  *int64
}

func (q *Queries) ListReminders(ctx context.Context, arg ListRemindersParams) ([]CityLedgerReminder, error) {
	rows, err := q.db.Query(ctx, listReminders,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
		arg.CompanyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CityLedgerReminder{}
	for rows.Next() {
		var i CityLedgerReminder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PropertyID,
			&i.ReminderNumber,
			&i.CompanyID,
			&i.Level,
			&i.ReminderDate,
			&i.Note,
			&i.TotalOutstanding,
			&i.TotalInterest,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfers = `-- name: ListTransfers :many
SELECT p.id, p.payment_number, p.business_date, p.amount, p.status, p.reference_number,
       f.folio_number, r.confirmation_number,
       COALESCE(NULLIF(trim(COALESCE(g.first_name, '') || ' ' || g.last_name), ''), '')::text AS guest_name
FROM payments p
JOIN folios f ON f.property_id = p.property_id AND f.id = p.folio_id
JOIN reservations r ON r.property_id = f.property_id AND r.id = f.reservation_id
LEFT JOIN guests g ON g.tenant_id = r.tenant_id AND g.id = r.guest_id
WHERE p.tenant_id = $1 AND p.property_id = $2 AND p.company_id = $3 AND p.payment_type = 'PAYMENT'
ORDER BY p.business_date, p.id
`

type ListTransfersParams struct {
	TenantID   int64
	PropertyID int64
	CompanyID  *int64
}

type ListTransfersRow struct {
	ID                 int64
	PaymentNumber      string
	BusinessDate       civil.Date
	Amount             decimal.Decimal
	Status             string
	ReferenceNumber    *string
	FolioNumber        string
	ConfirmationNumber string
	GuestName          string
}

// Transfers of one company, oldest first, with the folio, reservation and booker they came from.
func (q *Queries) ListTransfers(ctx context.Context, arg ListTransfersParams) ([]ListTransfersRow, error) {
	rows, err := q.db.Query(ctx, listTransfers, arg.TenantID, arg.PropertyID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransfersRow{}
	for rows.Next() {
		var i ListTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentNumber,
			&i.BusinessDate,
			&i.Amount,
			&i.Status,
			&i.ReferenceNumber,
			&i.FolioNumber,
			&i.ConfirmationNumber,
			&i.GuestName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseAttachments = `-- name: ReleaseAttachments :exec
UPDATE city_ledger_adjustment_invoices SET released_at = $1::timestamptz WHERE property_id = $2 AND invoice_id = $3 AND released_at IS NULL
`

type ReleaseAttachmentsParams struct {
	Now        time.Time
	PropertyID int64
	InvoiceID  int64
}

func (q *Queries) ReleaseAttachments(ctx context.Context, arg ReleaseAttachmentsParams) error {
	_, err := q.db.Exec(ctx, releaseAttachments, arg.Now, arg.PropertyID, arg.InvoiceID)
	return err
}

const releaseInvoiceLines = `-- name: ReleaseInvoiceLines :exec
UPDATE city_ledger_invoice_lines SET released_at = $1::timestamptz
WHERE property_id = $2 AND invoice_id = $3 AND released_at IS NULL
`

type ReleaseInvoiceLinesParams struct {
	Now        time.Time
	PropertyID int64
	InvoiceID  int64
}

func (q *Queries) ReleaseInvoiceLines(ctx context.Context, arg ReleaseInvoiceLinesParams) error {
	_, err := q.db.Exec(ctx, releaseInvoiceLines, arg.Now, arg.PropertyID, arg.InvoiceID)
	return err
}

const taxForCreditNote = `-- name: TaxForCreditNote :one
SELECT id, code, rate, is_active, gl_account_code, tax_kind FROM taxes WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type TaxForCreditNoteParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

type TaxForCreditNoteRow struct {
	ID            int64
	Code          string
	Rate          decimal.Decimal
	IsActive      bool
	GlAccountCode *string
	TaxKind       string
}

func (q *Queries) TaxForCreditNote(ctx context.Context, arg TaxForCreditNoteParams) (TaxForCreditNoteRow, error) {
	row := q.db.QueryRow(ctx, taxForCreditNote, arg.TenantID, arg.PropertyID, arg.ID)
	var i TaxForCreditNoteRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Rate,
		&i.IsActive,
		&i.GlAccountCode,
		&i.TaxKind,
	)
	return i, err
}

const transferCredited = `-- name: TransferCredited :one
SELECT COALESCE(sum(amount), 0)::numeric AS credited FROM city_ledger_adjustments
WHERE tenant_id = $1 AND property_id = $2 AND payment_id = $3 AND status = 'POSTED'
`

type TransferCreditedParams struct {
	TenantID   int64
	PropertyID int64
	PaymentID  *int64
}

// All the credit notes posted against a transfer, attached to an invoice or not.
func (q *Queries) TransferCredited(ctx context.Context, arg TransferCreditedParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, transferCredited, arg.TenantID, arg.PropertyID, arg.PaymentID)
	var credited decimal.Decimal
	err := row.Scan(&credited)
	return credited, err
}

const transferOnLiveInvoice = `-- name: TransferOnLiveInvoice :one
SELECT count(*)::int FROM city_ledger_invoice_lines WHERE property_id = $1 AND payment_id = $2 AND released_at IS NULL
`

type TransferOnLiveInvoiceParams struct {
	PropertyID int64
	PaymentID  int64
}

func (q *Queries) TransferOnLiveInvoice(ctx context.Context, arg TransferOnLiveInvoiceParams) (int32, error) {
	row := q.db.QueryRow(ctx, transferOnLiveInvoice, arg.PropertyID, arg.PaymentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const unattachedTransferNotes = `-- name: UnattachedTransferNotes :many
SELECT a.id, a.payment_id, a.amount FROM city_ledger_adjustments a
WHERE a.tenant_id = $1 AND a.property_id = $2 AND a.payment_id = ANY ($3::bigint[]) AND a.status = 'POSTED'
  AND NOT EXISTS (SELECT 1 FROM city_ledger_adjustment_invoices x WHERE x.property_id = a.property_id AND x.adjustment_id = a.id AND x.released_at IS NULL)
ORDER BY a.id
`

type UnattachedTransferNotesParams struct {
	TenantID   int64
	PropertyID int64
	PaymentIds []int64
}

type UnattachedTransferNotesRow struct {
	ID        int64
	PaymentID *int64
	Amount    decimal.Decimal
}

// The credit notes of transfers that no invoice has taken yet.
func (q *Queries) UnattachedTransferNotes(ctx context.Context, arg UnattachedTransferNotesParams) ([]UnattachedTransferNotesRow, error) {
	rows, err := q.db.Query(ctx, unattachedTransferNotes, arg.TenantID, arg.PropertyID, arg.PaymentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnattachedTransferNotesRow{}
	for rows.Next() {
		var i UnattachedTransferNotesRow
		if err := rows.Scan(&i.ID, &i.PaymentID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLateFee = `-- name: UpsertLateFee :exec
INSERT INTO city_ledger_late_fee_settings (tenant_id, property_id, monthly_rate, grace_days, updated_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (property_id) DO UPDATE SET monthly_rate = EXCLUDED.monthly_rate, grace_days = EXCLUDED.grace_days, updated_by = EXCLUDED.updated_by
`

type UpsertLateFeeParams struct {
	TenantID    int64
	PropertyID  int64
	MonthlyRate decimal.Decimal
	GraceDays   int16
	ActorID     *int64
}

func (q *Queries) UpsertLateFee(ctx context.Context, arg UpsertLateFeeParams) error {
	_, err := q.db.Exec(ctx, upsertLateFee,
		arg.TenantID,
		arg.PropertyID,
		arg.MonthlyRate,
		arg.GraceDays,
		arg.ActorID,
	)
	return err
}

const voidAdjustment = `-- name: VoidAdjustment :exec
UPDATE city_ledger_adjustments SET status = 'VOIDED', voided_at = $1::timestamptz, voided_by = $2, void_reason = $3, void_journal_id = $4, approved_by = $5
WHERE tenant_id = $6 AND property_id = $7 AND id = $8
`

type VoidAdjustmentParams struct {
	Now           time.Time
	ActorID       *int64
	Reason        *string
	VoidJournalID *int64
	ApprovedBy    *int64
	TenantID      int64
	PropertyID    int64
	ID            int64
}

func (q *Queries) VoidAdjustment(ctx context.Context, arg VoidAdjustmentParams) error {
	_, err := q.db.Exec(ctx, voidAdjustment,
		arg.Now,
		arg.ActorID,
		arg.Reason,
		arg.VoidJournalID,
		arg.ApprovedBy,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
	)
	return err
}

const voidInvoice = `-- name: VoidInvoice :one
UPDATE city_ledger_invoices
SET status = 'VOIDED', voided_at = $1::timestamptz, voided_by = $2, void_reason = $3, approved_by = $4
WHERE tenant_id = $5 AND property_id = $6 AND id = $7
RETURNING id, tenant_id, property_id, invoice_number, company_id, invoice_date, due_date, total, notes, status, voided_at, voided_by, void_reason, approved_by, idempotency_key, created_at, created_by
`

type VoidInvoiceParams struct {
	Now        time.Time
	ActorID    *int64
	Reason     *string
	ApprovedBy *int64
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) VoidInvoice(ctx context.Context, arg VoidInvoiceParams) (CityLedgerInvoice, error) {
	row := q.db.QueryRow(ctx, voidInvoice,
		arg.Now,
		arg.ActorID,
		arg.Reason,
		arg.ApprovedBy,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
	)
	var i CityLedgerInvoice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.InvoiceNumber,
		&i.CompanyID,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Total,
		&i.Notes,
		&i.Status,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.ApprovedBy,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const voidReceipt = `-- name: VoidReceipt :one
UPDATE city_ledger_receipts
SET status = 'VOIDED', voided_at = $1::timestamptz, voided_by = $2, void_reason = $3, approved_by = $4
WHERE tenant_id = $5 AND property_id = $6 AND id = $7
RETURNING id, tenant_id, property_id, receipt_number, company_id, amount, payment_method, reference_number, remarks, business_date, paid_at, status, voided_at, voided_by, void_reason, idempotency_key, created_at, created_by, approved_by
`

type VoidReceiptParams struct {
	Now        time.Time
	ActorID    *int64
	Reason     *string
	ApprovedBy *int64
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) VoidReceipt(ctx context.Context, arg VoidReceiptParams) (CityLedgerReceipt, error) {
	row := q.db.QueryRow(ctx, voidReceipt,
		arg.Now,
		arg.ActorID,
		arg.Reason,
		arg.ApprovedBy,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
	)
	var i CityLedgerReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.ReceiptNumber,
		&i.CompanyID,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.Remarks,
		&i.BusinessDate,
		&i.PaidAt,
		&i.Status,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ApprovedBy,
	)
	return i, err
}
