// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package cityledgerdb

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
	"kamarapms/internal/platform/civil"
)

const getAccount = `-- name: GetAccount :one
SELECT c.id, c.code, c.name, c.credit_limit, c.payment_terms_days, c.is_active, c.email, c.phone, c.address, c.contact_name,
       COALESCE((SELECT sum(p.amount) FROM payments p WHERE p.property_id = c.property_id AND p.company_id = c.id AND p.status = 'POSTED'), 0)::numeric AS transferred,
       COALESCE((SELECT sum(r.amount) FROM city_ledger_receipts r WHERE r.property_id = c.property_id AND r.company_id = c.id AND r.status = 'POSTED'), 0)::numeric AS received
FROM companies c
WHERE c.tenant_id = $1 AND c.property_id = $2 AND c.id = $3
`

type GetAccountParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

type GetAccountRow struct {
	ID               int64
	Code             string
	Name             string
	CreditLimit      *decimal.Decimal
	PaymentTermsDays int16
	IsActive         bool
	Email            *string
	Phone            *string
	Address          *string
	ContactName      *string
	Transferred      decimal.Decimal
	Received         decimal.Decimal
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.TenantID, arg.PropertyID, arg.ID)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreditLimit,
		&i.PaymentTermsDays,
		&i.IsActive,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.ContactName,
		&i.Transferred,
		&i.Received,
	)
	return i, err
}

const getReceipt = `-- name: GetReceipt :one
SELECT id, tenant_id, property_id, receipt_number, company_id, amount, payment_method, reference_number, remarks, business_date, paid_at, status, voided_at, voided_by, void_reason, idempotency_key, created_at, created_by, approved_by FROM city_ledger_receipts WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type GetReceiptParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) GetReceipt(ctx context.Context, arg GetReceiptParams) (CityLedgerReceipt, error) {
	row := q.db.QueryRow(ctx, getReceipt, arg.TenantID, arg.PropertyID, arg.ID)
	var i CityLedgerReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.ReceiptNumber,
		&i.CompanyID,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.Remarks,
		&i.BusinessDate,
		&i.PaidAt,
		&i.Status,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ApprovedBy,
	)
	return i, err
}

const getReceiptByKey = `-- name: GetReceiptByKey :one
SELECT id, tenant_id, property_id, receipt_number, company_id, amount, payment_method, reference_number, remarks, business_date, paid_at, status, voided_at, voided_by, void_reason, idempotency_key, created_at, created_by, approved_by FROM city_ledger_receipts WHERE tenant_id = $1 AND property_id = $2 AND idempotency_key = $3
`

type GetReceiptByKeyParams struct {
	TenantID       int64
	PropertyID     int64
	IdempotencyKey *string
}

func (q *Queries) GetReceiptByKey(ctx context.Context, arg GetReceiptByKeyParams) (CityLedgerReceipt, error) {
	row := q.db.QueryRow(ctx, getReceiptByKey, arg.TenantID, arg.PropertyID, arg.IdempotencyKey)
	var i CityLedgerReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.ReceiptNumber,
		&i.CompanyID,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.Remarks,
		&i.BusinessDate,
		&i.PaidAt,
		&i.Status,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ApprovedBy,
	)
	return i, err
}

const insertReceipt = `-- name: InsertReceipt :one
INSERT INTO city_ledger_receipts (
    tenant_id, property_id, receipt_number, company_id, amount, payment_method, reference_number, remarks,
    business_date, paid_at, idempotency_key, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12
)
RETURNING id, tenant_id, property_id, receipt_number, company_id, amount, payment_method, reference_number, remarks, business_date, paid_at, status, voided_at, voided_by, void_reason, idempotency_key, created_at, created_by, approved_by
`

type InsertReceiptParams struct {
	TenantID        int64
	PropertyID      int64
	ReceiptNumber   string
	CompanyID       int64
	Amount          decimal.Decimal
	PaymentMethod   string
	ReferenceNumber *string
	Remarks         *string
	BusinessDate    civil.Date
	PaidAt          time.Time
	IdempotencyKey  *string
	ActorID         *int64
}

func (q *Queries) InsertReceipt(ctx context.Context, arg InsertReceiptParams) (CityLedgerReceipt, error) {
	row := q.db.QueryRow(ctx, insertReceipt,
		arg.TenantID,
		arg.PropertyID,
		arg.ReceiptNumber,
		arg.CompanyID,
		arg.Amount,
		arg.PaymentMethod,
		arg.ReferenceNumber,
		arg.Remarks,
		arg.BusinessDate,
		arg.PaidAt,
		arg.IdempotencyKey,
		arg.ActorID,
	)
	var i CityLedgerReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.ReceiptNumber,
		&i.CompanyID,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.Remarks,
		&i.BusinessDate,
		&i.PaidAt,
		&i.Status,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ApprovedBy,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT a.id, a.code, a.name, a.credit_limit, a.payment_terms_days, a.is_active, a.transferred, a.received
FROM (
    SELECT c.id, c.code, c.name, c.credit_limit, c.payment_terms_days, c.is_active,
           COALESCE((SELECT sum(p.amount) FROM payments p WHERE p.property_id = c.property_id AND p.company_id = c.id AND p.status = 'POSTED'), 0)::numeric AS transferred,
           COALESCE((SELECT sum(r.amount) FROM city_ledger_receipts r WHERE r.property_id = c.property_id AND r.company_id = c.id AND r.status = 'POSTED'), 0)::numeric AS received
    FROM companies c
    WHERE c.tenant_id = $1 AND c.property_id = $2 AND c.id > $3
      AND ($4::text IS NULL OR c.code ILIKE '%' || $4::text || '%' OR c.name ILIKE '%' || $4::text || '%')
) a
WHERE (NOT $5::boolean OR a.transferred - a.received > 0)
ORDER BY a.id
LIMIT $6
`

type ListAccountsParams struct {
	TenantID   int64
	PropertyID int64
	AfterID    int64
	Q          *string
	Owing      bool
	RowLimit   int32
}

type ListAccountsRow struct {
	ID               int64
	Code             string
	Name             string
	CreditLimit      *decimal.Decimal
	PaymentTermsDays int16
	IsActive         bool
	Transferred      decimal.Decimal
	Received         decimal.Decimal
}

// Accounts: every company with what was transferred to it and what it paid back (posted rows only).
func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts,
		arg.TenantID,
		arg.PropertyID,
		arg.AfterID,
		arg.Q,
		arg.Owing,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.CreditLimit,
			&i.PaymentTermsDays,
			&i.IsActive,
			&i.Transferred,
			&i.Received,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceipts = `-- name: ListReceipts :many
SELECT id, tenant_id, property_id, receipt_number, company_id, amount, payment_method, reference_number, remarks, business_date, paid_at, status, voided_at, voided_by, void_reason, idempotency_key, created_at, created_by, approved_by FROM city_ledger_receipts
WHERE tenant_id = $1 AND property_id = $2 AND company_id = $3
ORDER BY business_date, id
`

type ListReceiptsParams struct {
	TenantID   int64
	PropertyID int64
	CompanyID  int64
}

func (q *Queries) ListReceipts(ctx context.Context, arg ListReceiptsParams) ([]CityLedgerReceipt, error) {
	rows, err := q.db.Query(ctx, listReceipts, arg.TenantID, arg.PropertyID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CityLedgerReceipt{}
	for rows.Next() {
		var i CityLedgerReceipt
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PropertyID,
			&i.ReceiptNumber,
			&i.CompanyID,
			&i.Amount,
			&i.PaymentMethod,
			&i.ReferenceNumber,
			&i.Remarks,
			&i.BusinessDate,
			&i.PaidAt,
			&i.Status,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.VoidReason,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ApprovedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfers = `-- name: ListTransfers :many
SELECT p.id, p.payment_number, p.business_date, p.amount, p.status, p.reference_number,
       f.folio_number, r.confirmation_number,
       COALESCE(NULLIF(trim(COALESCE(g.first_name, '') || ' ' || g.last_name), ''), '')::text AS guest_name
FROM payments p
JOIN folios f ON f.property_id = p.property_id AND f.id = p.folio_id
JOIN reservations r ON r.property_id = f.property_id AND r.id = f.reservation_id
LEFT JOIN guests g ON g.tenant_id = r.tenant_id AND g.id = r.guest_id
WHERE p.tenant_id = $1 AND p.property_id = $2 AND p.company_id = $3 AND p.payment_type = 'PAYMENT'
ORDER BY p.business_date, p.id
`

type ListTransfersParams struct {
	TenantID   int64
	PropertyID int64
	CompanyID  *int64
}

type ListTransfersRow struct {
	ID                 int64
	PaymentNumber      string
	BusinessDate       civil.Date
	Amount             decimal.Decimal
	Status             string
	ReferenceNumber    *string
	FolioNumber        string
	ConfirmationNumber string
	GuestName          string
}

// Transfers of one company, oldest first, with the folio, reservation and booker they came from.
func (q *Queries) ListTransfers(ctx context.Context, arg ListTransfersParams) ([]ListTransfersRow, error) {
	rows, err := q.db.Query(ctx, listTransfers, arg.TenantID, arg.PropertyID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransfersRow{}
	for rows.Next() {
		var i ListTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentNumber,
			&i.BusinessDate,
			&i.Amount,
			&i.Status,
			&i.ReferenceNumber,
			&i.FolioNumber,
			&i.ConfirmationNumber,
			&i.GuestName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const voidReceipt = `-- name: VoidReceipt :one
UPDATE city_ledger_receipts
SET status = 'VOIDED', voided_at = $1::timestamptz, voided_by = $2, void_reason = $3, approved_by = $4
WHERE tenant_id = $5 AND property_id = $6 AND id = $7
RETURNING id, tenant_id, property_id, receipt_number, company_id, amount, payment_method, reference_number, remarks, business_date, paid_at, status, voided_at, voided_by, void_reason, idempotency_key, created_at, created_by, approved_by
`

type VoidReceiptParams struct {
	Now        time.Time
	ActorID    *int64
	Reason     *string
	ApprovedBy *int64
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) VoidReceipt(ctx context.Context, arg VoidReceiptParams) (CityLedgerReceipt, error) {
	row := q.db.QueryRow(ctx, voidReceipt,
		arg.Now,
		arg.ActorID,
		arg.Reason,
		arg.ApprovedBy,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
	)
	var i CityLedgerReceipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.ReceiptNumber,
		&i.CompanyID,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.Remarks,
		&i.BusinessDate,
		&i.PaidAt,
		&i.Status,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.VoidReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ApprovedBy,
	)
	return i, err
}
