// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package accountingdb

import (
	"context"
	"time"

	"kamarapms/internal/platform/civil"
)

const ancestorIDs = `-- name: AncestorIDs :many
WITH RECURSIVE up AS (
    SELECT g.id, g.parent_id, 1 AS depth FROM gl_accounts g WHERE g.property_id = $1 AND g.id = $2
    UNION ALL
    SELECT a.id, a.parent_id, up.depth + 1 FROM gl_accounts a JOIN up ON a.property_id = $1 AND a.id = up.parent_id WHERE up.depth < 20
)
SELECT id FROM up
`

type AncestorIDsParams struct {
	PropertyID int64
	ID         int64
}

// Accounts that stand above an account, to refuse a parent that would make a loop.
func (q *Queries) AncestorIDs(ctx context.Context, arg AncestorIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, ancestorIDs, arg.PropertyID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAccountReferences = `-- name: CountAccountReferences :one
SELECT ((SELECT count(*) FROM gl_account_map m WHERE m.property_id = $1 AND m.account_id = $2)
      + (SELECT count(*) FROM charge_codes c WHERE c.property_id = $1 AND c.gl_account_code = $3)
      + (SELECT count(*) FROM taxes t WHERE t.property_id = $1 AND t.gl_account_code = $3)
      + (SELECT count(*) FROM service_charges s WHERE s.property_id = $1 AND s.gl_account_code = $3))::int AS refs
`

type CountAccountReferencesParams struct {
	PropertyID int64
	ID         int64
	Code       *string
}

func (q *Queries) CountAccountReferences(ctx context.Context, arg CountAccountReferencesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAccountReferences, arg.PropertyID, arg.ID, arg.Code)
	var refs int32
	err := row.Scan(&refs)
	return refs, err
}

const countChildren = `-- name: CountChildren :one
SELECT count(*)::int FROM gl_accounts g WHERE g.property_id = $1 AND g.parent_id = $2
`

type CountChildrenParams struct {
	PropertyID int64
	ID         *int64
}

func (q *Queries) CountChildren(ctx context.Context, arg CountChildrenParams) (int32, error) {
	row := q.db.QueryRow(ctx, countChildren, arg.PropertyID, arg.ID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO gl_accounts (tenant_id, property_id, code, name, account_type, normal_side, parent_id, is_postable, is_active, statement_group, description, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
        $12, $12)
RETURNING id
`

type CreateAccountParams struct {
	TenantID       int64
	PropertyID     int64
	Code           string
	Name           string
	AccountType    string
	NormalSide     string
	ParentID       *int64
	IsPostable     bool
	IsActive       bool
	StatementGroup *string
	Description    *string
	ActorID        *int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.TenantID,
		arg.PropertyID,
		arg.Code,
		arg.Name,
		arg.AccountType,
		arg.NormalSide,
		arg.ParentID,
		arg.IsPostable,
		arg.IsActive,
		arg.StatementGroup,
		arg.Description,
		arg.ActorID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM gl_accounts WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type DeleteAccountParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.Exec(ctx, deleteAccount, arg.TenantID, arg.PropertyID, arg.ID)
	return err
}

const getAccountByCode = `-- name: GetAccountByCode :one
SELECT id, tenant_id, property_id, code, name, account_type, normal_side, parent_id, is_postable, is_active, statement_group, description, created_at, created_by, updated_at, updated_by FROM gl_accounts WHERE tenant_id = $1 AND property_id = $2 AND code = $3
`

type GetAccountByCodeParams struct {
	TenantID   int64
	PropertyID int64
	Code       string
}

func (q *Queries) GetAccountByCode(ctx context.Context, arg GetAccountByCodeParams) (GlAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByCode, arg.TenantID, arg.PropertyID, arg.Code)
	var i GlAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.AccountType,
		&i.NormalSide,
		&i.ParentID,
		&i.IsPostable,
		&i.IsActive,
		&i.StatementGroup,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getAccountRow = `-- name: GetAccountRow :one
SELECT id, tenant_id, property_id, code, name, account_type, normal_side, parent_id, is_postable, is_active, statement_group, description, created_at, created_by, updated_at, updated_by FROM gl_accounts WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type GetAccountRowParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) GetAccountRow(ctx context.Context, arg GetAccountRowParams) (GlAccount, error) {
	row := q.db.QueryRow(ctx, getAccountRow, arg.TenantID, arg.PropertyID, arg.ID)
	var i GlAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.AccountType,
		&i.NormalSide,
		&i.ParentID,
		&i.IsPostable,
		&i.IsActive,
		&i.StatementGroup,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT id, tenant_id, property_id, start_date, fiscal_year_start_month, created_at, updated_at, updated_by FROM accounting_settings WHERE tenant_id = $1 AND property_id = $2
`

type GetSettingsParams struct {
	TenantID   int64
	PropertyID int64
}

func (q *Queries) GetSettings(ctx context.Context, arg GetSettingsParams) (AccountingSetting, error) {
	row := q.db.QueryRow(ctx, getSettings, arg.TenantID, arg.PropertyID)
	var i AccountingSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.StartDate,
		&i.FiscalYearStartMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listAccountMap = `-- name: ListAccountMap :many
SELECT m.map_key, m.account_id, a.code AS account_code, a.name AS account_name, a.account_type, m.updated_at
FROM gl_account_map m
JOIN gl_accounts a ON a.property_id = m.property_id AND a.id = m.account_id
WHERE m.tenant_id = $1 AND m.property_id = $2
ORDER BY m.map_key
`

type ListAccountMapParams struct {
	TenantID   int64
	PropertyID int64
}

type ListAccountMapRow struct {
	MapKey      string
	AccountID   int64
	AccountCode string
	AccountName string
	AccountType string
	UpdatedAt   time.Time
}

func (q *Queries) ListAccountMap(ctx context.Context, arg ListAccountMapParams) ([]ListAccountMapRow, error) {
	rows, err := q.db.Query(ctx, listAccountMap, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountMapRow{}
	for rows.Next() {
		var i ListAccountMapRow
		if err := rows.Scan(
			&i.MapKey,
			&i.AccountID,
			&i.AccountCode,
			&i.AccountName,
			&i.AccountType,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT a.id, a.code, a.name, a.account_type, a.normal_side, a.parent_id, p.code AS parent_code, a.is_postable, a.is_active, a.statement_group,
       a.description, a.created_at,
       (EXISTS (SELECT 1 FROM gl_accounts c WHERE c.property_id = a.property_id AND c.parent_id = a.id)
        OR EXISTS (SELECT 1 FROM gl_account_map m WHERE m.property_id = a.property_id AND m.account_id = a.id)
        OR EXISTS (SELECT 1 FROM charge_codes cc WHERE cc.property_id = a.property_id AND cc.gl_account_code = a.code)
        OR EXISTS (SELECT 1 FROM taxes t WHERE t.property_id = a.property_id AND t.gl_account_code = a.code)
        OR EXISTS (SELECT 1 FROM service_charges s WHERE s.property_id = a.property_id AND s.gl_account_code = a.code))::boolean AS in_use
FROM gl_accounts a
LEFT JOIN gl_accounts p ON p.property_id = a.property_id AND p.id = a.parent_id
WHERE a.tenant_id = $1 AND a.property_id = $2
  AND ($3::bigint IS NULL OR a.id = $3::bigint)
  AND ($4::text IS NULL OR a.account_type = $4::text)
  AND ($5::text IS NULL OR a.statement_group = $5::text)
  AND ($6::boolean IS NULL OR a.is_active = $6::boolean)
  AND ($7::boolean IS NULL OR a.is_postable = $7::boolean)
  AND ($8::text IS NULL OR a.code ILIKE '%' || $8::text || '%' OR a.name ILIKE '%' || $8::text || '%')
ORDER BY a.code
LIMIT $9
`

type ListAccountsParams struct {
	TenantID       int64
	PropertyID     int64
	ID             *int64
	AccountType    *string
	StatementGroup *string
	Active         *bool
	Postable       *bool
	Q              *string
	RowLimit       int32
}

type ListAccountsRow struct {
	ID             int64
	Code           string
	Name           string
	AccountType    string
	NormalSide     string
	ParentID       *int64
	ParentCode     *string
	IsPostable     bool
	IsActive       bool
	StatementGroup *string
	Description    *string
	CreatedAt      time.Time
	InUse          bool
}

// An account with its parent's code and whether anything refers to it (children, the system map, a charge code, tax or
// service charge that carries its code), which is what stops it from being deleted or deactivated.
func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
		arg.AccountType,
		arg.StatementGroup,
		arg.Active,
		arg.Postable,
		arg.Q,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.AccountType,
			&i.NormalSide,
			&i.ParentID,
			&i.ParentCode,
			&i.IsPostable,
			&i.IsActive,
			&i.StatementGroup,
			&i.Description,
			&i.CreatedAt,
			&i.InUse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodeUsage = `-- name: ListCodeUsage :many
SELECT u.kind, u.id, u.code, u.name, u.is_active, u.gl_account_code,
       a.id AS account_id, a.is_active AS account_active, a.is_postable AS account_postable, a.account_type
FROM (
    SELECT 'CHARGE_CODE'::text AS kind, c.id, c.code, c.name, c.is_active, c.gl_account_code FROM charge_codes c
    WHERE c.tenant_id = $1 AND c.property_id = $2
    UNION ALL
    SELECT 'TAX', t.id, t.code, t.name, t.is_active, t.gl_account_code FROM taxes t
    WHERE t.tenant_id = $1 AND t.property_id = $2
    UNION ALL
    SELECT 'SERVICE_CHARGE', s.id, s.code, s.name, s.is_active, s.gl_account_code FROM service_charges s
    WHERE s.tenant_id = $1 AND s.property_id = $2
) u
LEFT JOIN gl_accounts a ON a.property_id = $2 AND a.code = u.gl_account_code
ORDER BY u.kind, u.code
`

type ListCodeUsageParams struct {
	TenantID   int64
	PropertyID int64
}

type ListCodeUsageRow struct {
	Kind            string
	ID              int64
	Code            string
	Name            string
	IsActive        bool
	GlAccountCode   *string
	AccountID       *int64
	AccountActive   *bool
	AccountPostable *bool
	AccountType     *string
}

// What carries an account code and whether the code is a usable account of the chart: charge codes, taxes and service
// charges. A code that is empty or names no active postable account of the right kind is posted to a fallback account.
func (q *Queries) ListCodeUsage(ctx context.Context, arg ListCodeUsageParams) ([]ListCodeUsageRow, error) {
	rows, err := q.db.Query(ctx, listCodeUsage, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCodeUsageRow{}
	for rows.Next() {
		var i ListCodeUsageRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.Code,
			&i.Name,
			&i.IsActive,
			&i.GlAccountCode,
			&i.AccountID,
			&i.AccountActive,
			&i.AccountPostable,
			&i.AccountType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedChart = `-- name: SeedChart :one

SELECT seed_chart_of_accounts($1, $2, $3, $4::date)::int AS created
`

type SeedChartParams struct {
	TenantID   int64
	PropertyID int64
	ActorID    *int64
	StartDate  civil.Date
}

// Accounting (sqlc): chart of accounts, the system account map and journals. Every query is scoped by tenant_id and property_id.
func (q *Queries) SeedChart(ctx context.Context, arg SeedChartParams) (int32, error) {
	row := q.db.QueryRow(ctx, seedChart,
		arg.TenantID,
		arg.PropertyID,
		arg.ActorID,
		arg.StartDate,
	)
	var created int32
	err := row.Scan(&created)
	return created, err
}

const setAccountMap = `-- name: SetAccountMap :exec
INSERT INTO gl_account_map (tenant_id, property_id, map_key, account_id, updated_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (property_id, map_key) DO UPDATE SET account_id = EXCLUDED.account_id, updated_by = EXCLUDED.updated_by, updated_at = now()
`

type SetAccountMapParams struct {
	TenantID   int64
	PropertyID int64
	MapKey     string
	AccountID  int64
	ActorID    *int64
}

func (q *Queries) SetAccountMap(ctx context.Context, arg SetAccountMapParams) error {
	_, err := q.db.Exec(ctx, setAccountMap,
		arg.TenantID,
		arg.PropertyID,
		arg.MapKey,
		arg.AccountID,
		arg.ActorID,
	)
	return err
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE gl_accounts
SET name = $1, parent_id = $2, is_postable = $3, is_active = $4, statement_group = $5,
    description = $6, updated_by = $7
WHERE tenant_id = $8 AND property_id = $9 AND id = $10
`

type UpdateAccountParams struct {
	Name           string
	ParentID       *int64
	IsPostable     bool
	IsActive       bool
	StatementGroup *string
	Description    *string
	ActorID        *int64
	TenantID       int64
	PropertyID     int64
	ID             int64
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.Exec(ctx, updateAccount,
		arg.Name,
		arg.ParentID,
		arg.IsPostable,
		arg.IsActive,
		arg.StatementGroup,
		arg.Description,
		arg.ActorID,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
	)
	return err
}
