// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package expecteddb

import (
	"context"

	"github.com/shopspring/decimal"
	"kamarapms/internal/platform/civil"
)

const listOpenStayIDs = `-- name: ListOpenStayIDs :many

SELECT id FROM stays WHERE tenant_id = $1 AND property_id = $2 AND status = 'OPEN' ORDER BY id
`

type ListOpenStayIDsParams struct {
	TenantID   int64
	PropertyID int64
}

// Expected Charge Engine loader (sqlc): read-only snapshot queries. Scoped by tenant and property.
func (q *Queries) ListOpenStayIDs(ctx context.Context, arg ListOpenStayIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listOpenStayIDs, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopeFolios = `-- name: ListScopeFolios :many
SELECT id, stay_id FROM folios
WHERE tenant_id = $1 AND property_id = $2 AND stay_id = ANY($3::bigint[]) AND status = 'OPEN' AND folio_type = 'GUEST'
`

type ListScopeFoliosParams struct {
	TenantID   int64
	PropertyID int64
	StayIds    []int64
}

type ListScopeFoliosRow struct {
	ID     int64
	StayID *int64
}

func (q *Queries) ListScopeFolios(ctx context.Context, arg ListScopeFoliosParams) ([]ListScopeFoliosRow, error) {
	rows, err := q.db.Query(ctx, listScopeFolios, arg.TenantID, arg.PropertyID, arg.StayIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScopeFoliosRow{}
	for rows.Next() {
		var i ListScopeFoliosRow
		if err := rows.Scan(&i.ID, &i.StayID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopeNights = `-- name: ListScopeNights :many
SELECT n.reservation_room_id, n.stay_date, n.rate_plan_id, n.charge_code_id, c.code AS charge_code, c.is_active, (c.charge_type = 'ROOM')::boolean AS is_room,
       n.price_mode, n.amount
FROM reservation_room_rates n
JOIN charge_codes c ON c.property_id = n.property_id AND c.id = n.charge_code_id
WHERE n.tenant_id = $1 AND n.property_id = $2 AND n.reservation_room_id = ANY($3::bigint[])
ORDER BY n.reservation_room_id, n.stay_date
`

type ListScopeNightsParams struct {
	TenantID   int64
	PropertyID int64
	LineIds    []int64
}

type ListScopeNightsRow struct {
	ReservationRoomID int64
	StayDate          civil.Date
	RatePlanID        int64
	ChargeCodeID      int64
	ChargeCode        string
	IsActive          bool
	IsRoom            bool
	PriceMode         string
	Amount            decimal.Decimal
}

func (q *Queries) ListScopeNights(ctx context.Context, arg ListScopeNightsParams) ([]ListScopeNightsRow, error) {
	rows, err := q.db.Query(ctx, listScopeNights, arg.TenantID, arg.PropertyID, arg.LineIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScopeNightsRow{}
	for rows.Next() {
		var i ListScopeNightsRow
		if err := rows.Scan(
			&i.ReservationRoomID,
			&i.StayDate,
			&i.RatePlanID,
			&i.ChargeCodeID,
			&i.ChargeCode,
			&i.IsActive,
			&i.IsRoom,
			&i.PriceMode,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopePostings = `-- name: ListScopePostings :many
SELECT stay_id, service_date, folio_item_id, stay_room_id FROM stay_charge_postings
WHERE tenant_id = $1 AND property_id = $2 AND stay_id = ANY($3::bigint[]) AND status = 'POSTED' AND charge_source = 'ROOM_NIGHT'
`

type ListScopePostingsParams struct {
	TenantID   int64
	PropertyID int64
	StayIds    []int64
}

type ListScopePostingsRow struct {
	StayID      int64
	ServiceDate civil.Date
	FolioItemID int64
	StayRoomID  int64
}

func (q *Queries) ListScopePostings(ctx context.Context, arg ListScopePostingsParams) ([]ListScopePostingsRow, error) {
	rows, err := q.db.Query(ctx, listScopePostings, arg.TenantID, arg.PropertyID, arg.StayIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScopePostingsRow{}
	for rows.Next() {
		var i ListScopePostingsRow
		if err := rows.Scan(
			&i.StayID,
			&i.ServiceDate,
			&i.FolioItemID,
			&i.StayRoomID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopeSegments = `-- name: ListScopeSegments :many
SELECT sr.id, sr.stay_id, sr.room_id, r.room_number, sr.start_business_date, sr.end_business_date
FROM stay_rooms sr JOIN rooms r ON r.property_id = sr.property_id AND r.id = sr.room_id
WHERE sr.tenant_id = $1 AND sr.property_id = $2 AND sr.stay_id = ANY($3::bigint[])
ORDER BY sr.stay_id, sr.start_business_date, sr.id
`

type ListScopeSegmentsParams struct {
	TenantID   int64
	PropertyID int64
	StayIds    []int64
}

type ListScopeSegmentsRow struct {
	ID                int64
	StayID            int64
	RoomID            int64
	RoomNumber        string
	StartBusinessDate civil.Date
	EndBusinessDate   *civil.Date
}

func (q *Queries) ListScopeSegments(ctx context.Context, arg ListScopeSegmentsParams) ([]ListScopeSegmentsRow, error) {
	rows, err := q.db.Query(ctx, listScopeSegments, arg.TenantID, arg.PropertyID, arg.StayIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScopeSegmentsRow{}
	for rows.Next() {
		var i ListScopeSegmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StayID,
			&i.RoomID,
			&i.RoomNumber,
			&i.StartBusinessDate,
			&i.EndBusinessDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopeStays = `-- name: ListScopeStays :many
SELECT s.id, s.stay_number, s.status, s.arrival_date, s.departure_date, s.reservation_room_id, l.status AS line_status,
       g.first_name AS guest_first_name, g.last_name AS guest_last_name
FROM stays s
JOIN reservation_rooms l ON l.property_id = s.property_id AND l.id = s.reservation_room_id
JOIN guests g ON g.tenant_id = s.tenant_id AND g.id = s.guest_id
WHERE s.tenant_id = $1 AND s.property_id = $2
  AND ((cardinality($3::bigint[]) = 0 AND s.status = 'OPEN') OR s.id = ANY($3::bigint[]))
ORDER BY s.id
`

type ListScopeStaysParams struct {
	TenantID   int64
	PropertyID int64
	StayIds    []int64
}

type ListScopeStaysRow struct {
	ID                int64
	StayNumber        string
	Status            string
	ArrivalDate       civil.Date
	DepartureDate     civil.Date
	ReservationRoomID int64
	LineStatus        string
	GuestFirstName    *string
	GuestLastName     string
}

// Stays in scope: the listed ones, or every OPEN stay when the list is empty.
func (q *Queries) ListScopeStays(ctx context.Context, arg ListScopeStaysParams) ([]ListScopeStaysRow, error) {
	rows, err := q.db.Query(ctx, listScopeStays, arg.TenantID, arg.PropertyID, arg.StayIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScopeStaysRow{}
	for rows.Next() {
		var i ListScopeStaysRow
		if err := rows.Scan(
			&i.ID,
			&i.StayNumber,
			&i.Status,
			&i.ArrivalDate,
			&i.DepartureDate,
			&i.ReservationRoomID,
			&i.LineStatus,
			&i.GuestFirstName,
			&i.GuestLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
