#!/usr/bin/env bash
# Prepares a fresh Linux sandbox (Claude Code on the web, Codespaces, a CI VM) to build and
# test KamaraPMS WITHOUT Docker: a local PostgreSQL, Go modules, web dependencies and env vars.
#
# Idempotent and quiet when everything is already in place. Safe to run by hand:
#   scripts/cloud-setup.sh
# It runs automatically at the start of Claude Code web sessions (.claude/settings.json).
#
# Result:
#   - PostgreSQL on 127.0.0.1:5432, role pms/pms (CREATEDB), database pms (migrated)
#   - ./.env (gitignored) with PMS_DATABASE_URL, PMS_TEST_DATABASE_URL, PMS_JWT_SECRET, ...
#     read by cmd/* and by the database tests (internal/platform/dbtest)
#   - the same variables appended to $CLAUDE_ENV_FILE when Claude Code provides it
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
log() { echo "[cloud-setup] $*" >&2; }

if [ "$(uname -s)" != "Linux" ]; then
  log "not Linux: nothing to do (local development uses Docker; see README)"
  exit 0
fi

as_root() { if [ "$(id -u)" = 0 ]; then "$@"; else sudo -n "$@"; fi; }
as_postgres() { if [ "$(id -u)" = 0 ]; then runuser -u postgres -- "$@"; else sudo -n -u postgres "$@"; fi; }

# --- Toolchains ---------------------------------------------------------------
command -v go >/dev/null || { log "Go is not installed (any Go >= 1.21 works: GOTOOLCHAIN fetches the version in go.mod)"; exit 1; }
if command -v node >/dev/null; then
  node_major="$(node -p 'process.versions.node.split(".")[0]')"
  [ "$node_major" -ge 22 ] || log "warning: Node $(node -v) found; the web app needs Node 22.12+"
else
  log "warning: Node is not installed; web tests and builds will not run"
fi

# --- PostgreSQL -----------------------------------------------------------------
PGPORT=5432
if ! pg_isready -h 127.0.0.1 -p "$PGPORT" -q 2>/dev/null; then
  if ! ls /usr/lib/postgresql/*/bin/postgres >/dev/null 2>&1; then
    log "installing PostgreSQL (apt)"
    as_root apt-get update -qq
    DEBIAN_FRONTEND=noninteractive as_root apt-get install -y -qq postgresql postgresql-client >/dev/null
  fi
  log "starting PostgreSQL"
  if command -v pg_ctlcluster >/dev/null; then
    version="$(ls /usr/lib/postgresql | sort -V | tail -1)"
    as_root pg_ctlcluster "$version" main start 2>/dev/null || as_root service postgresql start
  else
    as_root service postgresql start
  fi
  for _ in $(seq 1 30); do pg_isready -h 127.0.0.1 -p "$PGPORT" -q && break; sleep 1; done
  pg_isready -h 127.0.0.1 -p "$PGPORT" -q || { log "PostgreSQL did not start"; exit 1; }
fi

as_postgres psql -X -q -v ON_ERROR_STOP=1 -d postgres <<'SQL'
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'pms') THEN
    CREATE ROLE pms LOGIN PASSWORD 'pms' CREATEDB;
  END IF;
END $$;
ALTER ROLE pms CREATEDB;
SQL
if [ "$(as_postgres psql -X -tA -d postgres -c "SELECT 1 FROM pg_database WHERE datname = 'pms'")" != "1" ]; then
  as_postgres createdb -O pms pms
fi

# --- Environment ------------------------------------------------------------------
DB_URL="postgres://pms:pms@127.0.0.1:$PGPORT/pms?sslmode=disable"
if [ ! -f .env ]; then
  secret="$(head -c 48 /dev/urandom | base64 | tr -d '\n/+=' | head -c 64)"
  cat > .env <<EOF
# Generated by scripts/cloud-setup.sh for this sandbox (gitignored).
PMS_ENV=development
PMS_HTTP_ADDR=127.0.0.1:18080
PMS_DATABASE_URL=$DB_URL
PMS_TEST_DATABASE_URL=$DB_URL
PMS_JWT_SECRET=$secret
PMS_LOG_FORMAT=text
EOF
  log "wrote .env"
elif ! grep -q '^PMS_TEST_DATABASE_URL=' .env; then
  printf '\nPMS_TEST_DATABASE_URL=%s\n' "$DB_URL" >> .env
fi

if [ -n "${CLAUDE_ENV_FILE:-}" ]; then
  grep -E '^PMS_[A-Z_]+=' .env | sed 's/^/export /' >> "$CLAUDE_ENV_FILE"
fi

# --- Dependencies and schema ----------------------------------------------------
go mod download
if command -v npm >/dev/null && [ ! -d web/node_modules ]; then
  log "installing web dependencies"
  (cd web && npm ci --no-fund --no-audit --loglevel=error)
fi
go run ./cmd/migrate up >/dev/null

echo "KamaraPMS sandbox ready: PostgreSQL on 127.0.0.1:$PGPORT (pms/pms), .env written, migrations applied. Run: go test ./..."
