// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package shiftsdb

import (
	"time"

	"github.com/shopspring/decimal"
	"kamarapms/internal/platform/civil"
)

type CashierShiftMovement struct {
	ID             int64
	TenantID       int64
	PropertyID     int64
	ShiftID        int64
	Kind           string
	Amount         decimal.Decimal
	AccountID      *int64
	Reason         string
	BusinessDate   civil.Date
	JournalID      *int64
	IdempotencyKey *string
	CreatedAt      time.Time
	CreatedBy      *int64
}

type PropertyCashierSetting struct {
	ID                  int64
	TenantID            int64
	PropertyID          int64
	RequireShiftForCash bool
	MaxVariance         decimal.Decimal
	BlockNightAudit     bool
	UpdatedAt           time.Time
	UpdatedBy           *int64
}
