// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tenancydb

import (
	"time"

	"kamarapms/internal/platform/civil"
)

type BusinessDay struct {
	ID           int64
	TenantID     int64
	PropertyID   int64
	BusinessDate civil.Date
	Status       string
	OpenedAt     time.Time
	OpenedBy     *int64
	ClosedAt     *time.Time
	ClosedBy     *int64
	Summary      []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Property struct {
	ID                              int64
	TenantID                        int64
	Code                            string
	Name                            string
	Address                         *string
	City                            *string
	CountryCode                     *string
	Timezone                        string
	CurrencyCode                    string
	CurrencyDecimals                int16
	CheckInTime                     civil.TimeOfDay
	CheckOutTime                    civil.TimeOfDay
	RequireRoomInspectionForCheckin bool
	NightAuditMarksOccupiedDirty    bool
	NightAuditEarliestTime          civil.TimeOfDay
	Status                          string
	CreatedAt                       time.Time
	CreatedBy                       *int64
	UpdatedAt                       time.Time
	UpdatedBy                       *int64
}

type Tenant struct {
	ID        int64
	Code      string
	Name      string
	Status    string
	Timezone  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
