// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package nightauditdb

import (
	"context"

	"github.com/shopspring/decimal"
	"kamarapms/internal/platform/civil"
)

const listBlocksEndingAt = `-- name: ListBlocksEndingAt :many
SELECT b.id AS block_id, b.block_type, r.room_number, b.end_date
FROM room_blocks b JOIN rooms r ON r.property_id = b.property_id AND r.id = b.room_id
WHERE b.tenant_id = $1 AND b.property_id = $2 AND b.status = 'ACTIVE' AND b.end_date = $3::date
ORDER BY b.id
`

type ListBlocksEndingAtParams struct {
	TenantID   int64
	PropertyID int64
	Bd         civil.Date
}

type ListBlocksEndingAtRow struct {
	BlockID    int64
	BlockType  string
	RoomNumber string
	EndDate    civil.Date
}

func (q *Queries) ListBlocksEndingAt(ctx context.Context, arg ListBlocksEndingAtParams) ([]ListBlocksEndingAtRow, error) {
	rows, err := q.db.Query(ctx, listBlocksEndingAt, arg.TenantID, arg.PropertyID, arg.Bd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlocksEndingAtRow{}
	for rows.Next() {
		var i ListBlocksEndingAtRow
		if err := rows.Scan(
			&i.BlockID,
			&i.BlockType,
			&i.RoomNumber,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOccupiedRoomIDs = `-- name: ListOccupiedRoomIDs :many
SELECT DISTINCT sr.room_id
FROM stay_rooms sr JOIN stays s ON s.property_id = sr.property_id AND s.id = sr.stay_id
WHERE sr.tenant_id = $1 AND sr.property_id = $2 AND sr.check_out_at IS NULL AND s.status = 'OPEN'
ORDER BY sr.room_id
`

type ListOccupiedRoomIDsParams struct {
	TenantID   int64
	PropertyID int64
}

// Housekeeping step: rooms that have an open segment of an OPEN stay.
func (q *Queries) ListOccupiedRoomIDs(ctx context.Context, arg ListOccupiedRoomIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listOccupiedRoomIDs, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var room_id int64
		if err := rows.Scan(&room_id); err != nil {
			return nil, err
		}
		items = append(items, room_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenFoliosOfDeadReservations = `-- name: ListOpenFoliosOfDeadReservations :many
SELECT f.id AS folio_id, f.folio_number, res.confirmation_number,
       COALESCE((SELECT sum(i.debit - i.credit) FROM folio_items i WHERE i.property_id = f.property_id AND i.folio_id = f.id), 0)::numeric AS balance
FROM folios f
JOIN reservations res ON res.property_id = f.property_id AND res.id = f.reservation_id
WHERE f.tenant_id = $1 AND f.property_id = $2 AND f.status = 'OPEN' AND f.stay_id IS NULL
  AND NOT EXISTS (SELECT 1 FROM reservation_rooms l WHERE l.property_id = f.property_id AND l.reservation_id = f.reservation_id
                  AND l.status NOT IN ('CANCELLED', 'NO_SHOW'))
  AND COALESCE((SELECT sum(i.debit - i.credit) FROM folio_items i WHERE i.property_id = f.property_id AND i.folio_id = f.id), 0) <> 0
ORDER BY f.id
`

type ListOpenFoliosOfDeadReservationsParams struct {
	TenantID   int64
	PropertyID int64
}

type ListOpenFoliosOfDeadReservationsRow struct {
	FolioID            int64
	FolioNumber        string
	ConfirmationNumber string
	Balance            decimal.Decimal
}

// OPEN folios without a stay, with a balance, whose reservation has only cancelled or no-show rooms.
func (q *Queries) ListOpenFoliosOfDeadReservations(ctx context.Context, arg ListOpenFoliosOfDeadReservationsParams) ([]ListOpenFoliosOfDeadReservationsRow, error) {
	rows, err := q.db.Query(ctx, listOpenFoliosOfDeadReservations, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenFoliosOfDeadReservationsRow{}
	for rows.Next() {
		var i ListOpenFoliosOfDeadReservationsRow
		if err := rows.Scan(
			&i.FolioID,
			&i.FolioNumber,
			&i.ConfirmationNumber,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleDrafts = `-- name: ListStaleDrafts :many
SELECT l.id AS reservation_room_id, l.reservation_id, res.confirmation_number, l.arrival_date
FROM reservation_rooms l
JOIN reservations res ON res.property_id = l.property_id AND res.id = l.reservation_id
WHERE l.tenant_id = $1 AND l.property_id = $2 AND l.status = 'DRAFT' AND l.arrival_date <= $3::date
ORDER BY l.arrival_date, l.id
`

type ListStaleDraftsParams struct {
	TenantID   int64
	PropertyID int64
	Bd         civil.Date
}

type ListStaleDraftsRow struct {
	ReservationRoomID  int64
	ReservationID      int64
	ConfirmationNumber string
	ArrivalDate        civil.Date
}

// Warnings.
func (q *Queries) ListStaleDrafts(ctx context.Context, arg ListStaleDraftsParams) ([]ListStaleDraftsRow, error) {
	rows, err := q.db.Query(ctx, listStaleDrafts, arg.TenantID, arg.PropertyID, arg.Bd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleDraftsRow{}
	for rows.Next() {
		var i ListStaleDraftsRow
		if err := rows.Scan(
			&i.ReservationRoomID,
			&i.ReservationID,
			&i.ConfirmationNumber,
			&i.ArrivalDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedArrivals = `-- name: ListUnresolvedArrivals :many

SELECT l.id AS reservation_room_id, l.reservation_id, res.confirmation_number, t.code AS room_type_code,
       r.room_number, l.arrival_date, g.first_name AS guest_first_name, g.last_name AS guest_last_name
FROM reservation_rooms l
JOIN reservations res ON res.property_id = l.property_id AND res.id = l.reservation_id
JOIN room_types t ON t.property_id = l.property_id AND t.id = l.room_type_id
LEFT JOIN rooms r ON r.property_id = l.property_id AND r.id = l.room_id
LEFT JOIN guests g ON g.tenant_id = res.tenant_id AND g.id = COALESCE(l.guest_id, res.guest_id)
WHERE l.tenant_id = $1 AND l.property_id = $2 AND l.status = 'CONFIRMED' AND l.arrival_date <= $3::date
ORDER BY l.arrival_date, l.id
`

type ListUnresolvedArrivalsParams struct {
	TenantID   int64
	PropertyID int64
	Bd         civil.Date
}

type ListUnresolvedArrivalsRow struct {
	ReservationRoomID  int64
	ReservationID      int64
	ConfirmationNumber string
	RoomTypeCode       string
	RoomNumber         *string
	ArrivalDate        civil.Date
	GuestFirstName     *string
	GuestLastName      *string
}

// Night audit queries (sqlc). Read-only: night audit writes nothing itself; it orchestrates the services that own
// the tables. Every query is scoped by tenant_id and property_id.
// Check 2: CONFIRMED room lines whose arrival is due.
func (q *Queries) ListUnresolvedArrivals(ctx context.Context, arg ListUnresolvedArrivalsParams) ([]ListUnresolvedArrivalsRow, error) {
	rows, err := q.db.Query(ctx, listUnresolvedArrivals, arg.TenantID, arg.PropertyID, arg.Bd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnresolvedArrivalsRow{}
	for rows.Next() {
		var i ListUnresolvedArrivalsRow
		if err := rows.Scan(
			&i.ReservationRoomID,
			&i.ReservationID,
			&i.ConfirmationNumber,
			&i.RoomTypeCode,
			&i.RoomNumber,
			&i.ArrivalDate,
			&i.GuestFirstName,
			&i.GuestLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedDepartures = `-- name: ListUnresolvedDepartures :many
SELECT s.id AS stay_id, s.stay_number, s.departure_date, r.room_number, g.first_name AS guest_first_name, g.last_name AS guest_last_name
FROM stays s
LEFT JOIN stay_rooms sr ON sr.property_id = s.property_id AND sr.stay_id = s.id AND sr.check_out_at IS NULL
LEFT JOIN rooms r ON r.property_id = sr.property_id AND r.id = sr.room_id
JOIN guests g ON g.tenant_id = s.tenant_id AND g.id = s.guest_id
WHERE s.tenant_id = $1 AND s.property_id = $2 AND s.status = 'OPEN' AND s.departure_date <= $3::date
ORDER BY s.departure_date, s.id
`

type ListUnresolvedDeparturesParams struct {
	TenantID   int64
	PropertyID int64
	Bd         civil.Date
}

type ListUnresolvedDeparturesRow struct {
	StayID         int64
	StayNumber     string
	DepartureDate  civil.Date
	RoomNumber     *string
	GuestFirstName *string
	GuestLastName  string
}

// Check 3: OPEN stays that should have left.
func (q *Queries) ListUnresolvedDepartures(ctx context.Context, arg ListUnresolvedDeparturesParams) ([]ListUnresolvedDeparturesRow, error) {
	rows, err := q.db.Query(ctx, listUnresolvedDepartures, arg.TenantID, arg.PropertyID, arg.Bd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnresolvedDeparturesRow{}
	for rows.Next() {
		var i ListUnresolvedDeparturesRow
		if err := rows.Scan(
			&i.StayID,
			&i.StayNumber,
			&i.DepartureDate,
			&i.RoomNumber,
			&i.GuestFirstName,
			&i.GuestLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryArrivals = `-- name: SummaryArrivals :one
SELECT count(*)::int FROM stays WHERE tenant_id = $1 AND property_id = $2 AND arrival_date = $3::date AND status <> 'CANCELLED'
`

type SummaryArrivalsParams struct {
	TenantID   int64
	PropertyID int64
	Bd         civil.Date
}

// Stays that arrived on the business date.
func (q *Queries) SummaryArrivals(ctx context.Context, arg SummaryArrivalsParams) (int32, error) {
	row := q.db.QueryRow(ctx, summaryArrivals, arg.TenantID, arg.PropertyID, arg.Bd)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const summaryDepartures = `-- name: SummaryDepartures :one
SELECT count(*)::int FROM stays s
WHERE s.tenant_id = $1 AND s.property_id = $2 AND s.status = 'CHECKED_OUT'
  AND (SELECT max(sr.end_business_date) FROM stay_rooms sr WHERE sr.property_id = s.property_id AND sr.stay_id = s.id) = $3::date
`

type SummaryDeparturesParams struct {
	TenantID   int64
	PropertyID int64
	Bd         civil.Date
}

// Stays whose last segment ended on the business date and that were checked out.
func (q *Queries) SummaryDepartures(ctx context.Context, arg SummaryDeparturesParams) (int32, error) {
	row := q.db.QueryRow(ctx, summaryDepartures, arg.TenantID, arg.PropertyID, arg.Bd)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const summaryNoShows = `-- name: SummaryNoShows :one
SELECT count(*)::int FROM audit_logs
WHERE tenant_id = $1 AND property_id = $2 AND business_date = $3::date AND action = 'reservation.no_show'
`

type SummaryNoShowsParams struct {
	TenantID   int64
	PropertyID *int64
	Bd         civil.Date
}

func (q *Queries) SummaryNoShows(ctx context.Context, arg SummaryNoShowsParams) (int32, error) {
	row := q.db.QueryRow(ctx, summaryNoShows, arg.TenantID, arg.PropertyID, arg.Bd)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const summaryPaymentsByMethod = `-- name: SummaryPaymentsByMethod :many
SELECT payment_method,
       COALESCE(sum(amount) FILTER (WHERE payment_type = 'PAYMENT'), 0)::numeric AS payments,
       COALESCE(sum(amount) FILTER (WHERE payment_type = 'REFUND'), 0)::numeric AS refunds
FROM payments
WHERE tenant_id = $1 AND property_id = $2 AND business_date = $3::date AND status = 'POSTED'
GROUP BY payment_method
ORDER BY payment_method
`

type SummaryPaymentsByMethodParams struct {
	TenantID   int64
	PropertyID int64
	Bd         civil.Date
}

type SummaryPaymentsByMethodRow struct {
	PaymentMethod string
	Payments      decimal.Decimal
	Refunds       decimal.Decimal
}

func (q *Queries) SummaryPaymentsByMethod(ctx context.Context, arg SummaryPaymentsByMethodParams) ([]SummaryPaymentsByMethodRow, error) {
	rows, err := q.db.Query(ctx, summaryPaymentsByMethod, arg.TenantID, arg.PropertyID, arg.Bd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummaryPaymentsByMethodRow{}
	for rows.Next() {
		var i SummaryPaymentsByMethodRow
		if err := rows.Scan(&i.PaymentMethod, &i.Payments, &i.Refunds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryRevenueByType = `-- name: SummaryRevenueByType :many
SELECT c.charge_type, sum(i.net_amount)::numeric AS net, sum(i.service_charge_total)::numeric AS service, sum(i.tax_total)::numeric AS tax
FROM folio_items i JOIN charge_codes c ON c.property_id = i.property_id AND c.id = i.charge_code_id
WHERE i.tenant_id = $1 AND i.property_id = $2 AND i.business_date = $3::date
  AND i.transaction_type IN ('CHARGE', 'ADJUSTMENT', 'REVERSAL')
GROUP BY c.charge_type
ORDER BY c.charge_type
`

type SummaryRevenueByTypeParams struct {
	TenantID   int64
	PropertyID int64
	Bd         civil.Date
}

type SummaryRevenueByTypeRow struct {
	ChargeType string
	Net        decimal.Decimal
	Service    decimal.Decimal
	Tax        decimal.Decimal
}

// Revenue posted on the business date by charge type (signed, so corrections net out).
func (q *Queries) SummaryRevenueByType(ctx context.Context, arg SummaryRevenueByTypeParams) ([]SummaryRevenueByTypeRow, error) {
	rows, err := q.db.Query(ctx, summaryRevenueByType, arg.TenantID, arg.PropertyID, arg.Bd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummaryRevenueByTypeRow{}
	for rows.Next() {
		var i SummaryRevenueByTypeRow
		if err := rows.Scan(
			&i.ChargeType,
			&i.Net,
			&i.Service,
			&i.Tax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryRoomNights = `-- name: SummaryRoomNights :one
SELECT count(*)::int FROM folio_items i
WHERE i.tenant_id = $1 AND i.property_id = $2 AND i.service_date = $3::date
  AND i.transaction_type = 'CHARGE' AND i.source = 'ROOM_POSTING'
  AND NOT EXISTS (SELECT 1 FROM folio_items rv WHERE rv.property_id = i.property_id AND rv.reverses_item_id = i.id)
`

type SummaryRoomNightsParams struct {
	TenantID   int64
	PropertyID int64
	Bd         civil.Date
}

// Room nights charged by the room posting service for the business date (and not reversed).
func (q *Queries) SummaryRoomNights(ctx context.Context, arg SummaryRoomNightsParams) (int32, error) {
	row := q.db.QueryRow(ctx, summaryRoomNights, arg.TenantID, arg.PropertyID, arg.Bd)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const summaryRooms = `-- name: SummaryRooms :one

SELECT
    (SELECT count(*) FROM rooms rm WHERE rm.tenant_id = $1 AND rm.property_id = $2 AND rm.is_active)::int AS total,
    (SELECT count(DISTINCT b.room_id) FROM room_blocks b JOIN rooms r ON r.property_id = b.property_id AND r.id = b.room_id AND r.is_active
      WHERE b.tenant_id = $1 AND b.property_id = $2 AND b.status = 'ACTIVE' AND b.block_type = 'OOO'
        AND b.start_date <= $3::date AND $3::date < b.end_date)::int AS out_of_order,
    (SELECT count(DISTINCT b.room_id) FROM room_blocks b JOIN rooms r ON r.property_id = b.property_id AND r.id = b.room_id AND r.is_active
      WHERE b.tenant_id = $1 AND b.property_id = $2 AND b.status = 'ACTIVE' AND b.block_type = 'OOS'
        AND b.start_date <= $3::date AND $3::date < b.end_date
        AND NOT EXISTS (SELECT 1 FROM room_blocks o WHERE o.property_id = b.property_id AND o.room_id = b.room_id AND o.status = 'ACTIVE'
                        AND o.block_type = 'OOO' AND o.start_date <= $3::date AND $3::date < o.end_date))::int AS out_of_service,
    (SELECT count(DISTINCT sr.room_id) FROM stay_rooms sr JOIN stays s ON s.property_id = sr.property_id AND s.id = sr.stay_id
      WHERE sr.tenant_id = $1 AND sr.property_id = $2 AND sr.check_out_at IS NULL AND s.status = 'OPEN')::int AS occupied
`

type SummaryRoomsParams struct {
	TenantID   int64
	PropertyID int64
	Bd         civil.Date
}

type SummaryRoomsRow struct {
	Total        int32
	OutOfOrder   int32
	OutOfService int32
	Occupied     int32
}

// ---------------------------------------------------------------- closing summary
func (q *Queries) SummaryRooms(ctx context.Context, arg SummaryRoomsParams) (SummaryRoomsRow, error) {
	row := q.db.QueryRow(ctx, summaryRooms, arg.TenantID, arg.PropertyID, arg.Bd)
	var i SummaryRoomsRow
	err := row.Scan(
		&i.Total,
		&i.OutOfOrder,
		&i.OutOfService,
		&i.Occupied,
	)
	return i, err
}
