// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package companiesdb

import (
	"time"

	"github.com/shopspring/decimal"
)

type Company struct {
	ID               int64
	TenantID         int64
	PropertyID       int64
	Code             string
	Name             string
	ContactName      *string
	Email            *string
	Phone            *string
	Address          *string
	City             *string
	TaxID            *string
	CreditLimit      *decimal.Decimal
	PaymentTermsDays int16
	Notes            *string
	IsActive         bool
	CreatedAt        time.Time
	CreatedBy        *int64
	UpdatedAt        time.Time
	UpdatedBy        *int64
}
