// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package companiesdb

import (
	"context"

	"github.com/shopspring/decimal"
)

const companyOwes = `-- name: CompanyOwes :one
SELECT (
    COALESCE((SELECT sum(p.amount) FROM payments p WHERE p.property_id = $1 AND p.company_id = $2 AND p.status = 'POSTED'), 0)
  - COALESCE((SELECT sum(r.amount) FROM city_ledger_receipts r WHERE r.property_id = $1 AND r.company_id = $2 AND r.status = 'POSTED'), 0)
)::numeric AS balance
`

type CompanyOwesParams struct {
	PropertyID int64
	ID         *int64
}

// Open balance of a company: transfers still owed less receipts (used to refuse deactivating an account that owes).
func (q *Queries) CompanyOwes(ctx context.Context, arg CompanyOwesParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, companyOwes, arg.PropertyID, arg.ID)
	var balance decimal.Decimal
	err := row.Scan(&balance)
	return balance, err
}

const createCompany = `-- name: CreateCompany :one

INSERT INTO companies (tenant_id, property_id, code, name, contact_name, email, phone, address, city, tax_id, credit_limit, payment_terms_days, notes, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15, $15)
RETURNING id, tenant_id, property_id, code, name, contact_name, email, phone, address, city, tax_id, credit_limit, payment_terms_days, notes, is_active, created_at, created_by, updated_at, updated_by
`

type CreateCompanyParams struct {
	TenantID         int64
	PropertyID       int64
	Code             string
	Name             string
	ContactName      *string
	Email            *string
	Phone            *string
	Address          *string
	City             *string
	TaxID            *string
	CreditLimit      *decimal.Decimal
	PaymentTermsDays int16
	Notes            *string
	IsActive         bool
	ActorID          *int64
}

// Companies (corporate accounts). Every query is scoped by tenant_id and property_id.
func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.TenantID,
		arg.PropertyID,
		arg.Code,
		arg.Name,
		arg.ContactName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.City,
		arg.TaxID,
		arg.CreditLimit,
		arg.PaymentTermsDays,
		arg.Notes,
		arg.IsActive,
		arg.ActorID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.TaxID,
		&i.CreditLimit,
		&i.PaymentTermsDays,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getCompany = `-- name: GetCompany :one
SELECT id, tenant_id, property_id, code, name, contact_name, email, phone, address, city, tax_id, credit_limit, payment_terms_days, notes, is_active, created_at, created_by, updated_at, updated_by FROM companies WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type GetCompanyParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) GetCompany(ctx context.Context, arg GetCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, arg.TenantID, arg.PropertyID, arg.ID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.TaxID,
		&i.CreditLimit,
		&i.PaymentTermsDays,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getCompanyForUpdate = `-- name: GetCompanyForUpdate :one
SELECT id, tenant_id, property_id, code, name, contact_name, email, phone, address, city, tax_id, credit_limit, payment_terms_days, notes, is_active, created_at, created_by, updated_at, updated_by FROM companies WHERE tenant_id = $1 AND property_id = $2 AND id = $3 FOR UPDATE
`

type GetCompanyForUpdateParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) GetCompanyForUpdate(ctx context.Context, arg GetCompanyForUpdateParams) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyForUpdate, arg.TenantID, arg.PropertyID, arg.ID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.TaxID,
		&i.CreditLimit,
		&i.PaymentTermsDays,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, tenant_id, property_id, code, name, contact_name, email, phone, address, city, tax_id, credit_limit, payment_terms_days, notes, is_active, created_at, created_by, updated_at, updated_by FROM companies
WHERE tenant_id = $1 AND property_id = $2 AND id > $3
  AND ($4::boolean IS NULL OR is_active = $4::boolean)
  AND ($5::text IS NULL OR code ILIKE '%' || $5::text || '%' OR name ILIKE '%' || $5::text || '%')
ORDER BY id
LIMIT $6
`

type ListCompaniesParams struct {
	TenantID   int64
	PropertyID int64
	AfterID    int64
	Active     *bool
	Q          *string
	RowLimit   int32
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies,
		arg.TenantID,
		arg.PropertyID,
		arg.AfterID,
		arg.Active,
		arg.Q,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PropertyID,
			&i.Code,
			&i.Name,
			&i.ContactName,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.City,
			&i.TaxID,
			&i.CreditLimit,
			&i.PaymentTermsDays,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies SET
    name = $1, contact_name = $2, email = $3, phone = $4, address = $5,
    city = $6, tax_id = $7, credit_limit = $8, payment_terms_days = $9,
    notes = $10, is_active = $11, updated_by = $12
WHERE tenant_id = $13 AND property_id = $14 AND id = $15
RETURNING id, tenant_id, property_id, code, name, contact_name, email, phone, address, city, tax_id, credit_limit, payment_terms_days, notes, is_active, created_at, created_by, updated_at, updated_by
`

type UpdateCompanyParams struct {
	Name             string
	ContactName      *string
	Email            *string
	Phone            *string
	Address          *string
	City             *string
	TaxID            *string
	CreditLimit      *decimal.Decimal
	PaymentTermsDays int16
	Notes            *string
	IsActive         bool
	ActorID          *int64
	TenantID         int64
	PropertyID       int64
	ID               int64
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.Name,
		arg.ContactName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.City,
		arg.TaxID,
		arg.CreditLimit,
		arg.PaymentTermsDays,
		arg.Notes,
		arg.IsActive,
		arg.ActorID,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.TaxID,
		&i.CreditLimit,
		&i.PaymentTermsDays,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
