// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package notificationsdb

import (
	"time"
)

type EmailOutbox struct {
	ID            int64
	TenantID      int64
	PropertyID    int64
	Kind          string
	ReservationID int64
	ToAddress     string
	Status        string
	Attempts      int16
	NextAttemptAt time.Time
	LastError     *string
	SentAt        *time.Time
	CreatedAt     time.Time
	CreatedBy     *int64
}
