// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package notificationsdb

import (
	"context"
	"time"
)

const bookerEmail = `-- name: BookerEmail :one

SELECT COALESCE(g.email, '')::text AS email
FROM reservations r LEFT JOIN guests g ON g.tenant_id = r.tenant_id AND g.id = r.guest_id
WHERE r.tenant_id = $1 AND r.property_id = $2 AND r.id = $3
`

type BookerEmailParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

// E-mail outbox queries (sqlc). Every query is scoped by tenant_id and property_id except the worker's claim, which
// works across properties and re-enters each one as its tenant.
// The e-mail address of the booker of a reservation (” when there is none).
func (q *Queries) BookerEmail(ctx context.Context, arg BookerEmailParams) (string, error) {
	row := q.db.QueryRow(ctx, bookerEmail, arg.TenantID, arg.PropertyID, arg.ID)
	var email string
	err := row.Scan(&email)
	return email, err
}

const claimDue = `-- name: ClaimDue :many
UPDATE email_outbox SET next_attempt_at = $1::timestamptz
WHERE id IN (
    SELECT id FROM email_outbox WHERE status = 'QUEUED' AND next_attempt_at <= $2::timestamptz
    ORDER BY next_attempt_at, id LIMIT $3 FOR UPDATE SKIP LOCKED
)
RETURNING id, tenant_id, property_id, kind, reservation_id, to_address, status, attempts, next_attempt_at, last_error, sent_at, created_at, created_by
`

type ClaimDueParams struct {
	LeaseUntil time.Time
	Now        time.Time
	RowLimit   int32
}

// A worker takes due messages and pushes their next attempt out (a lease), so a second worker, or a crash, never
// sends a message twice at once.
func (q *Queries) ClaimDue(ctx context.Context, arg ClaimDueParams) ([]EmailOutbox, error) {
	rows, err := q.db.Query(ctx, claimDue, arg.LeaseUntil, arg.Now, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailOutbox{}
	for rows.Next() {
		var i EmailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PropertyID,
			&i.Kind,
			&i.ReservationID,
			&i.ToAddress,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.SentAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutbox = `-- name: InsertOutbox :one
INSERT INTO email_outbox (tenant_id, property_id, kind, reservation_id, to_address, next_attempt_at, created_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6::timestamptz, $6::timestamptz, $7)
RETURNING id, tenant_id, property_id, kind, reservation_id, to_address, status, attempts, next_attempt_at, last_error, sent_at, created_at, created_by
`

type InsertOutboxParams struct {
	TenantID      int64
	PropertyID    int64
	Kind          string
	ReservationID int64
	ToAddress     string
	Now           time.Time
	ActorID       *int64
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) (EmailOutbox, error) {
	row := q.db.QueryRow(ctx, insertOutbox,
		arg.TenantID,
		arg.PropertyID,
		arg.Kind,
		arg.ReservationID,
		arg.ToAddress,
		arg.Now,
		arg.ActorID,
	)
	var i EmailOutbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Kind,
		&i.ReservationID,
		&i.ToAddress,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.SentAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listOutboxForReservation = `-- name: ListOutboxForReservation :many
SELECT id, tenant_id, property_id, kind, reservation_id, to_address, status, attempts, next_attempt_at, last_error, sent_at, created_at, created_by FROM email_outbox
WHERE tenant_id = $1 AND property_id = $2 AND reservation_id = $3
ORDER BY id DESC
LIMIT 20
`

type ListOutboxForReservationParams struct {
	TenantID      int64
	PropertyID    int64
	ReservationID int64
}

func (q *Queries) ListOutboxForReservation(ctx context.Context, arg ListOutboxForReservationParams) ([]EmailOutbox, error) {
	rows, err := q.db.Query(ctx, listOutboxForReservation, arg.TenantID, arg.PropertyID, arg.ReservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailOutbox{}
	for rows.Next() {
		var i EmailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PropertyID,
			&i.Kind,
			&i.ReservationID,
			&i.ToAddress,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.SentAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFailed = `-- name: MarkFailed :exec
UPDATE email_outbox SET status = 'FAILED', attempts = attempts + 1, last_error = $1 WHERE id = $2
`

type MarkFailedParams struct {
	LastError *string
	ID        int64
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) error {
	_, err := q.db.Exec(ctx, markFailed, arg.LastError, arg.ID)
	return err
}

const markRetry = `-- name: MarkRetry :exec
UPDATE email_outbox SET attempts = attempts + 1, next_attempt_at = $1::timestamptz, last_error = $2 WHERE id = $3
`

type MarkRetryParams struct {
	NextAttemptAt time.Time
	LastError     *string
	ID            int64
}

func (q *Queries) MarkRetry(ctx context.Context, arg MarkRetryParams) error {
	_, err := q.db.Exec(ctx, markRetry, arg.NextAttemptAt, arg.LastError, arg.ID)
	return err
}

const markSent = `-- name: MarkSent :exec
UPDATE email_outbox SET status = 'SENT', sent_at = $1::timestamptz, attempts = attempts + 1, last_error = NULL WHERE id = $2
`

type MarkSentParams struct {
	Now time.Time
	ID  int64
}

func (q *Queries) MarkSent(ctx context.Context, arg MarkSentParams) error {
	_, err := q.db.Exec(ctx, markSent, arg.Now, arg.ID)
	return err
}

const markSkipped = `-- name: MarkSkipped :exec
UPDATE email_outbox SET status = 'SKIPPED', last_error = $1 WHERE id = $2
`

type MarkSkippedParams struct {
	LastError *string
	ID        int64
}

func (q *Queries) MarkSkipped(ctx context.Context, arg MarkSkippedParams) error {
	_, err := q.db.Exec(ctx, markSkipped, arg.LastError, arg.ID)
	return err
}
