// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package groupsdb

import (
	"context"
	"time"

	"kamarapms/internal/platform/civil"
)

const companyActive = `-- name: CompanyActive :one
SELECT is_active FROM companies WHERE tenant_id = $1 AND property_id = $2 AND id = $3
`

type CompanyActiveParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) CompanyActive(ctx context.Context, arg CompanyActiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, companyActive, arg.TenantID, arg.PropertyID, arg.ID)
	var is_active bool
	err := row.Scan(&is_active)
	return is_active, err
}

const countLinesOutside = `-- name: CountLinesOutside :one
SELECT count(*)::int FROM reservation_rooms l JOIN reservations r ON r.id = l.reservation_id
WHERE r.property_id = $1 AND r.booking_group_id = $2 AND l.status <> 'CANCELLED'
  AND (l.arrival_date < $3 OR l.departure_date > $4)
`

type CountLinesOutsideParams struct {
	PropertyID    int64
	GroupID       *int64
	ArrivalDate   civil.Date
	DepartureDate civil.Date
}

// Lines of the group that would fall outside a new date window.
func (q *Queries) CountLinesOutside(ctx context.Context, arg CountLinesOutsideParams) (int32, error) {
	row := q.db.QueryRow(ctx, countLinesOutside,
		arg.PropertyID,
		arg.GroupID,
		arg.ArrivalDate,
		arg.DepartureDate,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countReservationsOfOtherCompany = `-- name: CountReservationsOfOtherCompany :one
SELECT count(*)::int FROM reservations r
WHERE r.property_id = $1 AND r.booking_group_id = $2 AND r.status <> 'CANCELLED'
  AND r.company_id IS DISTINCT FROM $3::bigint
`

type CountReservationsOfOtherCompanyParams struct {
	PropertyID int64
	GroupID    *int64
	CompanyID  *int64
}

// Reservations of the group that bill another company than the one the group is moved to.
func (q *Queries) CountReservationsOfOtherCompany(ctx context.Context, arg CountReservationsOfOtherCompanyParams) (int32, error) {
	row := q.db.QueryRow(ctx, countReservationsOfOtherCompany, arg.PropertyID, arg.GroupID, arg.CompanyID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO booking_groups (
    tenant_id, property_id, code, name, company_id, contact_name, contact_email, contact_phone,
    arrival_date, departure_date, notes, is_active, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $13
)
RETURNING id, tenant_id, property_id, code, name, company_id, contact_name, contact_email, contact_phone, arrival_date, departure_date, notes, is_active, created_at, created_by, updated_at, updated_by
`

type CreateGroupParams struct {
	TenantID      int64
	PropertyID    int64
	Code          string
	Name          string
	CompanyID     *int64
	ContactName   *string
	ContactEmail  *string
	ContactPhone  *string
	ArrivalDate   civil.Date
	DepartureDate civil.Date
	Notes         *string
	IsActive      bool
	ActorID       *int64
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (BookingGroup, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.TenantID,
		arg.PropertyID,
		arg.Code,
		arg.Name,
		arg.CompanyID,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.ArrivalDate,
		arg.DepartureDate,
		arg.Notes,
		arg.IsActive,
		arg.ActorID,
	)
	var i BookingGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.CompanyID,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.ArrivalDate,
		&i.DepartureDate,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT g.id, g.tenant_id, g.property_id, g.code, g.name, g.company_id, g.contact_name, g.contact_email, g.contact_phone, g.arrival_date, g.departure_date, g.notes, g.is_active, g.created_at, g.created_by, g.updated_at, g.updated_by, c.name AS company_name,
       (SELECT count(*) FROM reservations r WHERE r.property_id = g.property_id AND r.booking_group_id = g.id AND r.status <> 'CANCELLED')::int AS reservation_count,
       (SELECT count(*) FROM reservation_rooms l JOIN reservations r ON r.id = l.reservation_id
         WHERE r.property_id = g.property_id AND r.booking_group_id = g.id AND l.status <> 'CANCELLED')::int AS room_count
FROM booking_groups g
LEFT JOIN companies c ON c.property_id = g.property_id AND c.id = g.company_id
WHERE g.tenant_id = $1 AND g.property_id = $2 AND g.id = $3
`

type GetGroupParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

type GetGroupRow struct {
	ID               int64
	TenantID         int64
	PropertyID       int64
	Code             string
	Name             string
	CompanyID        *int64
	ContactName      *string
	ContactEmail     *string
	ContactPhone     *string
	ArrivalDate      civil.Date
	DepartureDate    civil.Date
	Notes            *string
	IsActive         bool
	CreatedAt        time.Time
	CreatedBy        *int64
	UpdatedAt        time.Time
	UpdatedBy        *int64
	CompanyName      *string
	ReservationCount int32
	RoomCount        int32
}

func (q *Queries) GetGroup(ctx context.Context, arg GetGroupParams) (GetGroupRow, error) {
	row := q.db.QueryRow(ctx, getGroup, arg.TenantID, arg.PropertyID, arg.ID)
	var i GetGroupRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.CompanyID,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.ArrivalDate,
		&i.DepartureDate,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.CompanyName,
		&i.ReservationCount,
		&i.RoomCount,
	)
	return i, err
}

const getGroupForUpdate = `-- name: GetGroupForUpdate :one
SELECT id, tenant_id, property_id, code, name, company_id, contact_name, contact_email, contact_phone, arrival_date, departure_date, notes, is_active, created_at, created_by, updated_at, updated_by FROM booking_groups WHERE tenant_id = $1 AND property_id = $2 AND id = $3 FOR UPDATE
`

type GetGroupForUpdateParams struct {
	TenantID   int64
	PropertyID int64
	ID         int64
}

func (q *Queries) GetGroupForUpdate(ctx context.Context, arg GetGroupForUpdateParams) (BookingGroup, error) {
	row := q.db.QueryRow(ctx, getGroupForUpdate, arg.TenantID, arg.PropertyID, arg.ID)
	var i BookingGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.CompanyID,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.ArrivalDate,
		&i.DepartureDate,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listGroups = `-- name: ListGroups :many
SELECT g.id, g.tenant_id, g.property_id, g.code, g.name, g.company_id, g.contact_name, g.contact_email, g.contact_phone, g.arrival_date, g.departure_date, g.notes, g.is_active, g.created_at, g.created_by, g.updated_at, g.updated_by, c.name AS company_name,
       (SELECT count(*) FROM reservations r WHERE r.property_id = g.property_id AND r.booking_group_id = g.id AND r.status <> 'CANCELLED')::int AS reservation_count,
       (SELECT count(*) FROM reservation_rooms l JOIN reservations r ON r.id = l.reservation_id
         WHERE r.property_id = g.property_id AND r.booking_group_id = g.id AND l.status <> 'CANCELLED')::int AS room_count
FROM booking_groups g
LEFT JOIN companies c ON c.property_id = g.property_id AND c.id = g.company_id
WHERE g.tenant_id = $1 AND g.property_id = $2 AND g.id < $3
  AND ($4::boolean IS NULL OR g.is_active = $4::boolean)
  AND ($5::bigint IS NULL OR g.company_id = $5::bigint)
  AND ($6::text IS NULL OR g.code ILIKE '%' || $6::text || '%' OR g.name ILIKE '%' || $6::text || '%')
ORDER BY g.id DESC
LIMIT $7
`

type ListGroupsParams struct {
	TenantID   int64
	PropertyID int64
	BeforeID   int64
	Active     *bool
	CompanyID  *int64
	Q          *string
	RowLimit   int32
}

type ListGroupsRow struct {
	ID               int64
	TenantID         int64
	PropertyID       int64
	Code             string
	Name             string
	CompanyID        *int64
	ContactName      *string
	ContactEmail     *string
	ContactPhone     *string
	ArrivalDate      civil.Date
	DepartureDate    civil.Date
	Notes            *string
	IsActive         bool
	CreatedAt        time.Time
	CreatedBy        *int64
	UpdatedAt        time.Time
	UpdatedBy        *int64
	CompanyName      *string
	ReservationCount int32
	RoomCount        int32
}

func (q *Queries) ListGroups(ctx context.Context, arg ListGroupsParams) ([]ListGroupsRow, error) {
	rows, err := q.db.Query(ctx, listGroups,
		arg.TenantID,
		arg.PropertyID,
		arg.BeforeID,
		arg.Active,
		arg.CompanyID,
		arg.Q,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsRow{}
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PropertyID,
			&i.Code,
			&i.Name,
			&i.CompanyID,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.ArrivalDate,
			&i.DepartureDate,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.CompanyName,
			&i.ReservationCount,
			&i.RoomCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT r.id, r.confirmation_number, r.status, r.company_id,
       agg.arrival_date::date AS arrival_date, agg.departure_date::date AS departure_date, agg.room_count::int AS room_count,
       COALESCE(NULLIF(trim(COALESCE(gu.first_name, '') || ' ' || COALESCE(gu.last_name, '')), ''), '')::text AS guest_name
FROM reservations r
CROSS JOIN LATERAL (
    SELECT COALESCE(min(l.arrival_date) FILTER (WHERE l.status <> 'CANCELLED'), min(l.arrival_date)) AS arrival_date,
           COALESCE(max(l.departure_date) FILTER (WHERE l.status <> 'CANCELLED'), max(l.departure_date)) AS departure_date,
           count(*) FILTER (WHERE l.status <> 'CANCELLED') AS room_count
    FROM reservation_rooms l WHERE l.reservation_id = r.id
) agg
LEFT JOIN guests gu ON gu.tenant_id = r.tenant_id AND gu.id = r.guest_id
WHERE r.tenant_id = $1 AND r.property_id = $2 AND r.booking_group_id = $3
ORDER BY r.id
`

type ListMembersParams struct {
	TenantID   int64
	PropertyID int64
	GroupID    *int64
}

type ListMembersRow struct {
	ID                 int64
	ConfirmationNumber string
	Status             string
	CompanyID          *int64
	ArrivalDate        civil.Date
	DepartureDate      civil.Date
	RoomCount          int32
	GuestName          string
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, arg.TenantID, arg.PropertyID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ConfirmationNumber,
			&i.Status,
			&i.CompanyID,
			&i.ArrivalDate,
			&i.DepartureDate,
			&i.RoomCount,
			&i.GuestName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE booking_groups SET
    name = $1, company_id = $2, contact_name = $3, contact_email = $4,
    contact_phone = $5, arrival_date = $6, departure_date = $7, notes = $8,
    is_active = $9, updated_by = $10
WHERE tenant_id = $11 AND property_id = $12 AND id = $13
RETURNING id, tenant_id, property_id, code, name, company_id, contact_name, contact_email, contact_phone, arrival_date, departure_date, notes, is_active, created_at, created_by, updated_at, updated_by
`

type UpdateGroupParams struct {
	Name          string
	CompanyID     *int64
	ContactName   *string
	ContactEmail  *string
	ContactPhone  *string
	ArrivalDate   civil.Date
	DepartureDate civil.Date
	Notes         *string
	IsActive      bool
	ActorID       *int64
	TenantID      int64
	PropertyID    int64
	ID            int64
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (BookingGroup, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.Name,
		arg.CompanyID,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.ArrivalDate,
		arg.DepartureDate,
		arg.Notes,
		arg.IsActive,
		arg.ActorID,
		arg.TenantID,
		arg.PropertyID,
		arg.ID,
	)
	var i BookingGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.Code,
		&i.Name,
		&i.CompanyID,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.ArrivalDate,
		&i.DepartureDate,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
