// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package auditdb

import (
	"context"
	"net/netip"
	"time"

	"kamarapms/internal/platform/civil"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (
    tenant_id, property_id, business_date, user_id, action, entity_type, entity_id,
    old_data, new_data, request_id, ip_address, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12
)
`

type InsertAuditLogParams struct {
	TenantID     int64
	PropertyID   *int64
	BusinessDate *civil.Date
	UserID       *int64
	Action       string
	EntityType   string
	EntityID     int64
	OldData      []byte
	NewData      []byte
	RequestID    *string
	IpAddress    *netip.Addr
	CreatedAt    time.Time
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.TenantID,
		arg.PropertyID,
		arg.BusinessDate,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.OldData,
		arg.NewData,
		arg.RequestID,
		arg.IpAddress,
		arg.CreatedAt,
	)
	return err
}

const listAuditLogsForEntity = `-- name: ListAuditLogsForEntity :many
SELECT id, tenant_id, property_id, business_date, user_id, action, entity_type, entity_id, old_data, new_data, request_id, ip_address, created_at FROM audit_logs
WHERE tenant_id = $1 AND entity_type = $2 AND entity_id = $3
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAuditLogsForEntityParams struct {
	TenantID   int64
	EntityType string
	EntityID   int64
	RowLimit   int32
}

func (q *Queries) ListAuditLogsForEntity(ctx context.Context, arg ListAuditLogsForEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsForEntity,
		arg.TenantID,
		arg.EntityType,
		arg.EntityID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PropertyID,
			&i.BusinessDate,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OldData,
			&i.NewData,
			&i.RequestID,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
